import {REVIEW_CATALOG} from './asset-review-catalog.js';
import {loadUpgrade,registerLoadedUpgrade} from './asset-upgrades.js';
import {createReviewModel,drawThumbnail,interactiveView,renderViews} from './asset-review-preview.js';
const $=s=>document.querySelector(s),safe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localErrors=new Map();
const list=$('#assetList'),dialog=$('#compareDialog'),cards=new Map(),signatures=new Map(),localBusy=new Set(),rotations=new Map(),preparedCache=new Map();let snapshot,online=false,filter='',category='',statusFilter='',priceFilter='',modalTarget=null,views=[],lastFocus,toastTimer;
const priceLabel=a=>a?.price?.free?'무료':a?.price?.amount!=null?'US $'+Number(a.price.amount).toFixed(2):'가격 확인 필요';
const absoluteURL=url=>{try{const u=new URL(url);return /^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),5500);}
async function api(route,data){const response=await fetch('./api/asset-review/'+route,{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':snapshot.token},body:JSON.stringify(data)});let result;try{result=await response.json();}catch{throw Error('검토 서버에 연결하지 못했습니다.');}if(!response.ok)throw Error(result.error||'요청에 실패했습니다.');return result;}
function row(id){return snapshot?.rows?.[id]||{};}
function approved(id){return snapshot?.approved?.[id];}
const busy=id=>localBusy.has(id)||snapshot?.busy?.includes(id)||row(id).status==='searching';
function showError(id,error){localErrors.set(id,error.message||error);const card=cards.get(id);if(card){card.querySelector('.row-error').textContent=error.message||error;card.querySelector('.row-error').hidden=false;}toast(error.message||error);}
async function action(id,task){if(localBusy.has(id))return;localErrors.delete(id);localBusy.add(id);renderRow(REVIEW_CATALOG.find(t=>t.id===id),true);try{await task();}catch(e){showError(id,e);}finally{localBusy.delete(id);await refresh();}}
async function refresh(){try{const response=await fetch('./api/asset-review/state',{cache:'no-store'});if(!response.ok)throw Error('offline');snapshot=await response.json();if(!snapshot.catalog)throw Error('offline');online=true;$('#connectionNotice').hidden=true;render();}catch{if(!snapshot){snapshot={catalog:REVIEW_CATALOG,rows:{},approved:{},scan:{}};try{const res=await fetch('./asset-upgrades/manifest.json');const m=await res.json();snapshot.approved=m.assets||{};}catch{}render();}online=false;$('#connectionNotice').hidden=false;$('#connectionNotice').textContent='이 페이지는 프로젝트의 로컬 검토 서버에서 검색과 승인을 저장합니다. 터미널에서 npm run review를 실행한 뒤 http://localhost:5175/asset-review.html을 여세요.';$('#scanAll').disabled=true;}}
function render(){const candidates=REVIEW_CATALOG.filter(t=>row(t.id).prepared?.audit?.compatible===true).length,applied=Object.keys(snapshot.approved).length;$('#counts').innerHTML=`<div class="count"><strong>${REVIEW_CATALOG.length}</strong><small>교체 대상</small></div><div class="count"><strong>${candidates}</strong><small>파일 검사 통과</small></div><div class="count"><strong>${applied}</strong><small>적용 완료</small></div>`;const scan=snapshot.scan;$('#scanAll').disabled=!online||scan?.running;$('#scanAll').innerHTML=scan?.running?'후보를 찾고 있습니다…':`미검색 항목 찾기 <span>↗</span>`;$('#scanStatus').textContent=scan?.running?`${scan.done} / ${scan.total} · ${scan.current}`:applied?`${applied}개 적용 · 열린 게임은 새로고침하세요.`:'아직 허용하지 않은 에셋은 그대로 유지됩니다.';for(const target of REVIEW_CATALOG)renderRow(target);filterRows();}
function renderRow(target,force=false){
 const r=row(target.id),candidate=r.candidate,a=approved(target.id),isBusy=busy(target.id);
 const options=[...new Map([...(snapshot.alternatives?.[target.id]||[]),...(r.pool||[]),...(candidate?[candidate]:[])].map(a=>[a.id,a])).values()];
 const signature=JSON.stringify([candidate?.id,r.status,r.error,localErrors.get(target.id),r.prepared,r.imports,a?.key,isBusy,options.map(a=>a.id)]);
 let card=cards.get(target.id);
 if(!card){card=document.createElement('article');card.className='asset-row';card.dataset.id=target.id;card.innerHTML=`<div class="original"><div class="asset-label"><span class="asset-number">${String(target.index+1).padStart(2,'0')}</span><h2>${safe(target.name)}</h2><span class="pill">${safe(target.category)}</span></div><div class="visual"><canvas aria-label="${safe(target.name)} 현재 모습"></canvas><span class="origin">${safe(target.origin)}</span></div><p class="asset-meta">${safe(target.usage)}</p></div><div class="candidate"></div><div class="actions"></div>`;list.append(card);cards.set(target.id,card);observer.observe(card);}
 if(!force&&signature===signatures.get(target.id))return;signatures.set(target.id,signature);
 const candidatePane=card.querySelector('.candidate'),actions=card.querySelector('.actions'),isApplied=candidate&&a?.source?.id===candidate.id;
 const imported=Boolean(r.imports?.[candidate?.id]),needsFile=candidate&&['purchase','manual'].includes(candidate.acquisition)&&!imported,paid=candidate?.price?.free===false;
 const readiness=!candidate?'추가 탐색 필요':needsFile?(paid?'구매 전 · 파일 미확보':'원본 다운로드 필요'):r.prepared?.audit?.compatible===true?'파일 검사 통과 · 외형을 확인하세요':r.prepared?.audit?.compatible===false?'수정 작업 필요':'파일 확인 전';
 candidatePane.innerHTML=`<div class="asset-label"><h2 class="candidate-title">${safe(candidate?.title||(r.status==='searching'?'새로운 후보를 찾는 중':'아직 맞는 모델을 찾지 못했습니다'))}</h2>${isApplied?'<span class="pill applied">적용 완료</span>':''}</div><div class="visual">${candidate?.thumbnailUrl?`<img loading="lazy" referrerpolicy="no-referrer" src="${safe(absoluteURL(candidate.thumbnailUrl))}" alt="${safe(candidate.title)} 교체 후보">`:`<span>${r.status==='searching'?'에셋 사이트에서 후보를 찾고 있습니다.':'차종·건물 형태·관절 구조에 맞는<br>후보를 추가로 찾아야 합니다.'}</span>`}${candidate&&!needsFile?'<button class="view-button" data-action="compare">3D로 비교 ↗</button>':''}</div>${candidate?`<div class="candidate-facts"><strong class="price ${paid?'paid':''}">${safe(priceLabel(candidate))}</strong><span>${safe(readiness)}</span></div><p class="match-reason">${safe(candidate.matchReason||'검색어와 모델 제목으로 찾은 후보입니다. 실제 외형은 직접 비교해주세요.')}</p><p class="asset-meta">${safe(candidate.provider)} · ${safe(candidate.license?.name||'라이선스 확인 필요')}<br>${safe(candidate.workNeeded||'')}${candidate.reviewedAt?`<br>${candidate.reviewedAt} 확인${paid?' · 세금·할인에 따라 가격 변동':''}`:''}<br><a href="${safe(absoluteURL(candidate.url))}" target="_blank" rel="noopener noreferrer">원본 ${paid?'판매':'배포'} 페이지 ↗</a></p>`:''}${options.length>1?`<div class="alternatives" aria-label="${safe(target.name)} 다른 후보">${options.slice(0,6).map(option=>`<button data-candidate="${safe(option.id)}" aria-pressed="${option.id===candidate?.id}" ${isBusy||!online?'disabled':''}><span>${safe(priceLabel(option))}</span>${safe(option.title)}</button>`).join('')}</div>`:''}`;
 candidatePane.querySelector('img')?.addEventListener('error',e=>{e.target.replaceWith(Object.assign(document.createElement('span'),{textContent:'원본 페이지에서 이미지를 확인해주세요.'}));});
 actions.innerHTML=`${needsFile?`<a class="source-button" href="${safe(absoluteURL(candidate.url))}" target="_blank" rel="noopener noreferrer">${paid?'판매 페이지 보기':'무료 다운로드 보기'} ↗</a><button data-action="import" ${isBusy||!online?'disabled':''}>보유 파일 가져오기</button><p class="row-note">${paid?'구매는 직접 선택하셔야 합니다.':'무료 원본을 직접 받아 가져올 수 있습니다.'} 가져온 파일을 비교한 뒤 허용합니다.</p>`:`<button class="primary" data-action="approve" ${!online||!candidate||isBusy||isApplied||r.prepared?.audit?.compatible===false?'disabled':''}>${isBusy?'처리 중…':isApplied?'게임에 적용됨':r.prepared?.audit?.compatible===false?'수정 작업 필요':'허용 · 적용'}</button>`}<button data-action="next" ${!online||isBusy?'disabled':''}>${candidate?'다른 거 찾기':'후보 찾기'} ↻</button>${a?'<button class="subtle" data-action="revert">원래대로 되돌리기</button>':''}<p class="row-note">${a&&!isApplied?'현재 적용: '+safe(a.source.title):safe(target.note||'허용하면 이 항목만 교체합니다.')}</p><p class="row-error" ${r.error||localErrors.has(target.id)||r.prepared?.audit?.compatible===false?'':'hidden'}>${safe(r.error||localErrors.get(target.id)||r.prepared?.audit?.reasons?.join(' ')||'')}</p><details class="query-edit"><summary>검색어 바꾸기</summary><form><input aria-label="${safe(target.name)} 검색어" maxlength="120" value="${safe(r.query||r.lastQuery||target.queries[0])}"><button type="submit" ${isBusy||!online?'disabled':''}>검색</button></form></details>`;
 card.querySelectorAll('[data-candidate]').forEach(button=>button.onclick=()=>action(target.id,()=>api('select',{id:target.id,candidateId:button.dataset.candidate})));
 card.querySelectorAll('[data-action]').forEach(button=>{button.onclick=()=>{const kind=button.dataset.action;if(kind==='compare')return compare(target);if(kind==='next')return action(target.id,()=>api('next',{id:target.id}));if(kind==='approve')return approveTarget(target);if(kind==='import')return importTarget(target);if(kind==='revert')return action(target.id,async()=>{await api('revert',{id:target.id});toast(target.name+'을 원래대로 되돌렸습니다.');});};});
 card.querySelector('form').onsubmit=e=>{e.preventDefault();const query=e.currentTarget.querySelector('input').value.trim();if(query)action(target.id,()=>api('next',{id:target.id,query}));};
}
function importTarget(target){const candidateId=row(target.id).candidate.id,input=document.createElement('input');input.type='file';input.accept='.glb,.blend';input.onchange=()=>{const file=input.files?.[0];if(!file)return;action(target.id,async()=>{if(file.size>64*1024*1024)throw Error('64MB 이하의 GLB 또는 Blender 파일을 선택해주세요.');toast('파일을 가져와 검사하고 있습니다. Blender 파일은 변환에 시간이 걸릴 수 있습니다.');const response=await fetch('./api/asset-review/import?'+new URLSearchParams({id:target.id,candidateId}),{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Review-Token':snapshot.token,'X-File-Name':encodeURIComponent(file.name)},body:file});const result=await response.json();if(!response.ok)throw Error(result.error);preparedCache.delete(target.id+':'+candidateId);toast('파일을 가져왔습니다. 3D로 비교한 뒤 허용해주세요.');});};input.click();}
function filterRows(){let visible=0;for(const target of REVIEW_CATALOG){const r=row(target.id),a=approved(target.id);const show=(!priceFilter||(priceFilter==='free'?r.candidate?.price?.free===true:r.candidate?.price?.free===false))&&(!category||target.category===category)&&(!filter||`${target.name} ${target.category} ${r.candidate?.title||''}`.toLowerCase().includes(filter))&&(!statusFilter||(statusFilter==='approved'?Boolean(a):statusFilter==='candidate'?Boolean(r.candidate)&&a?.source?.id!==r.candidate.id:!r.candidate&&['empty','error'].includes(r.status)));cards.get(target.id).hidden=!show;if(show)visible++;}$('#visibleCount').textContent=visible+'개 항목';$('#emptyList').hidden=Boolean(visible);}
// One shared WebGL renderer; thumbnails are drawn only when rows enter the viewport.
let previewQueue=Promise.resolve();const thumbnailDone=new Set();const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;const id=entry.target.dataset.id;if(thumbnailDone.has(id))continue;thumbnailDone.add(id);observer.unobserve(entry.target);previewQueue=previewQueue.then(async()=>{try{const target=REVIEW_CATALOG.find(t=>t.id===id),model=await createReviewModel(target,true);drawThumbnail(model,entry.target.querySelector('.original canvas'));}catch(e){const canvas=entry.target.querySelector('.original canvas');canvas.replaceWith(Object.assign(document.createElement('span'),{textContent:'원본 미리보기: '+e.message}));}});}}, {rootMargin:'250px'});
async function prepareTarget(target){const candidate=row(target.id).candidate;if(!candidate)throw Error('먼저 후보를 찾아주세요.');const key=target.id+':'+candidate.id;let promise=preparedCache.get(key);if(!promise){promise=(async()=>{const prepared=await api('prepare',{id:target.id,candidateId:candidate.id});const rotation=rotations.get(key)||[0,0,0],entry={file:prepared.file,maps:prepared.maps,rotation,audit:prepared.audit,source:prepared.candidate};const value=await loadUpgrade(entry,new URL(prepared.baseUrl,location.origin).href);return {prepared,value,key,candidateId:candidate.id};})();preparedCache.set(key,promise);promise.catch(()=>preparedCache.delete(key));}return promise;}
async function approveTarget(target){return action(target.id,async()=>{toast(target.name+'의 파일과 호환성을 확인하고 있습니다.');const result=await prepareTarget(target);if(!result.prepared.audit.compatible)throw Error(result.prepared.audit.reasons.join(' '));await api('approve',{id:target.id,candidateId:result.candidateId,rotation:rotations.get(result.key)||[0,0,0]});toast(target.name+'을 적용했습니다. 게임을 새로고침해서 확인하세요.');if(dialog.open)closeCompare();});}
async function compare(target){if(busy(target.id))return;lastFocus=document.activeElement;modalTarget=target;$('#compareTitle').textContent=target.name;$('#compareInfo').textContent='모델과 텍스처를 준비하고 있습니다…';$('#compareApprove').disabled=true;$('#compareNext').disabled=true;dialog.showModal();views.forEach(v=>v.controls.dispose());views=[];try{const result=await prepareTarget(target);if(modalTarget!==target||!dialog.open)return;registerLoadedUpgrade(target.id,result.value);const old=await createReviewModel(target,true),next=result.prepared.audit.compatible?await createReviewModel(target,false):result.value.gltf.scene.clone(true);views=[interactiveView(old,$('#beforeCanvas')),interactiveView(next,$('#afterCanvas'))];const a=result.prepared.audit;$('#compareInfo').textContent=`${result.prepared.candidate.title} · ${result.prepared.candidate.license.name} · ${(result.prepared.bytes/1024/1024).toFixed(1)}MB${a.triangles?' · 삼각형 '+a.triangles.toLocaleString()+'개':''}${a.compatible?' · 적용 가능한 파일입니다.':' · '+a.reasons.join(' ')}`;$('#compareApprove').disabled=!a.compatible;$('#compareNext').disabled=false;dialog.dataset.key=result.key;}catch(e){$('#compareInfo').textContent=e.message;$('#compareNext').disabled=false;}}
function closeCompare(){views.forEach(v=>v.controls.dispose());views=[];modalTarget=null;dialog.close();lastFocus?.focus();}
$('#closeCompare').onclick=closeCompare;dialog.addEventListener('cancel',event=>{event.preventDefault();closeCompare();});$('#compareApprove').onclick=()=>modalTarget&&approveTarget(modalTarget);$('#compareNext').onclick=()=>{const target=modalTarget;closeCompare();action(target.id,()=>api('next',{id:target.id}));};
document.querySelectorAll('[data-axis]').forEach(button=>button.onclick=async()=>{if(!modalTarget||!views.length)return;const key=dialog.dataset.key,current=rotations.get(key)||[0,0,0],axis=Number(button.dataset.axis);current[axis]=(current[axis]+90)%360;rotations.set(key,current);const result=await prepareTarget(modalTarget);result.value.gltf?.scene.rotation.fromArray([...current.map(n=>n*Math.PI/180),'XYZ']);if(result.value.gltf){const {sceneToTemplate}=await import('./asset-upgrades.js');result.value.template=sceneToTemplate(result.value.gltf.scene);}registerLoadedUpgrade(modalTarget.id,result.value);const next=result.prepared.audit.compatible?await createReviewModel(modalTarget,false):result.value.gltf.scene.clone(true);views[1].controls.dispose();views[1]=interactiveView(next,$('#afterCanvas'));});
$('#resetRotation').onclick=async()=>{if(!modalTarget)return;rotations.set(dialog.dataset.key,[0,0,0]);preparedCache.delete(dialog.dataset.key);const target=modalTarget;closeCompare();compare(target);};
$('#scanAll').onclick=async()=>{try{await api('scan',{});await refresh();}catch(e){toast(e.message);}};$('#filterText').oninput=e=>{filter=e.target.value.toLowerCase().trim();filterRows();};$('#category').innerHTML+=[...new Set(REVIEW_CATALOG.map(t=>t.category))].map(c=>`<option>${safe(c)}</option>`).join('');$('#category').onchange=e=>{category=e.target.value;filterRows();};$('#priceFilter').onchange=e=>{priceFilter=e.target.value;filterRows();};$('#statusFilter').onchange=e=>{statusFilter=e.target.value;filterRows();};
let lastFrame=0;function tick(time){if(views.length&&dialog.open&&time-lastFrame>33){renderViews(views);lastFrame=time;}requestAnimationFrame(tick);}requestAnimationFrame(tick);await refresh();setInterval(()=>{if(!document.hidden)refresh();},2500);
