import {hangarSlots,HANGAR_SLOT_COUNT} from './hangar-slots.js';
import {configureUpgradeLighting} from './asset-upgrades.js';
import * as THREE from 'three';
import {createRobot,disposeRobot} from './robot.js';
import {applyFrameVisual} from './frame-preview.js';
import {frameStats} from './salvage-campaign.js';
import {createThirdPersonView} from './third-person.js';
import {createWeaponModel} from './weapon-models.js';
import {createHangarRoom} from './hangar-room.js';
import {workshopMetal,dressConsole,bevelHousing,dressCarousel} from './hangar-workshop-details.js';
import {CHEST_SLOTS} from './salvage-chest.js';
import {disposeObjectResources} from './runtime-resources.js';

// One persistent scene: selection rotates the whole platform carousel.
export function createHangarScene(host,onAction=()=>{},onHover=()=>{},onLayout=()=>{}){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.setClearColor(0x070b10);host.appendChild(renderer.domElement);
 configureUpgradeLighting(renderer);
 const scene=new THREE.Scene();scene.fog=new THREE.Fog(0x070b10,15,34);const camera=new THREE.PerspectiveCamera(42,1,.05,45);camera.position.set(0,3.85,7.5);camera.lookAt(0,1.9,0);
 const steel=workshopMetal(),black=new THREE.MeshStandardMaterial({color:0x0d141c,roughness:.8}),edge=new THREE.MeshStandardMaterial({color:0x9abfc8,emissive:0x72d3e5,emissiveIntensity:1.2}),crate=new THREE.MeshStandardMaterial({color:0x39443b,metalness:.25,roughness:.8});
 const box=(parent,size,pos,mat=steel)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);m.position.set(...pos);m.castShadow=m.receiveShadow=true;parent.add(m);return m;};
 scene.add(new THREE.HemisphereLight(0xadc9de,0x030507,.07));for(const x of[-4,0,4]){const l=new THREE.SpotLight(x===0?0xb6deef:0x50718d,x===0?12:1.5,16,.62,.65);l.position.set(x,5,3);l.target.position.set(x,1.5,0);l.castShadow=x===0;scene.add(l,l.target);}
 // Broad, low intensity light over the whole carousel replaces the inspection pin.
 const platformGlow=new THREE.PointLight(0xb5d9df,9,8,2);platformGlow.position.set(0,2.7,1.5);scene.add(platformGlow);for(const x of [-2.5,2.5]){const fill=new THREE.PointLight(0x8ca9b7,2,5,2);fill.position.set(x,.5,-2);scene.add(fill);}

 const consoleLight=new THREE.PointLight(0xc6e0e7,6,10,2);consoleLight.position.set(0,3.2,5);scene.add(consoleLight);
 const room=createHangarRoom();room.root.traverse(o=>{if(o.isLight)o.intensity*=.12;});scene.add(room.root);for(const x of [-3,3]){const sunlight=new THREE.SpotLight(0xffd9a0,70,13,.5,.8,2);sunlight.position.set(x,4.4,-7.9);sunlight.target.position.set(x*.2,.4,0);scene.add(sunlight,sunlight.target);}
 const departureRig=new THREE.Group();departureRig.visible=false;scene.add(departureRig);for(const x of [-.35,.35]){const hook=new THREE.Mesh(new THREE.TorusGeometry(.15,.035,8,20),steel);hook.position.set(x,3.1,0);departureRig.add(hook);const cable=new THREE.Mesh(new THREE.CylinderGeometry(.022,.022,7,8),steel);cable.position.set(x,6.6,0);departureRig.add(cable);}let departure=null,prepareAmount=0,inventoryAmount=0,identityAmount=0;
 const wheel=new THREE.Group();wheel.position.z=-2.25;scene.add(wheel);const turntable=new THREE.Mesh(new THREE.CylinderGeometry(3.4,3.5,.16,80),steel);turntable.position.y=-.10;turntable.receiveShadow=true;wheel.add(turntable);const trackDetails=new THREE.Group();trackDetails.scale.set(.77,1,.77);wheel.add(trackDetails);dressCarousel(trackDetails,box,steel,black);const outerRing=new THREE.Mesh(new THREE.TorusGeometry(3.34,.035,6,80),edge);outerRing.rotation.x=Math.PI/2;outerRing.position.y=-.005;wheel.add(outerRing);let inspection=null,openAmount=0,rigs=[],signature='',stockSignature='',target=0,angle=0,last=performance.now();
 const screen=new THREE.MeshStandardMaterial({color:0x063356,emissive:0x168cdd,emissiveIntensity:1.4,roughness:.35});const sharedMaterials=[steel,black,edge,crate,screen];
 function clearRigs(){for(const r of rigs){if(r.robot)disposeRobot(r.robot);disposeObjectResources(r.group,{sharedMaterials});}rigs=[];}
 // Match the weapon wall across the room; each component rests on a shelf surface.
 for(const shelf of room.root.children.filter(o=>o.userData.action==='stash'))shelf.position.set(-4.35/1.05,0,2.2/1.05);
 const moduleHeap=new THREE.Group();moduleHeap.userData.action='stash';moduleHeap.position.set(-4.35,0,.2);moduleHeap.scale.setScalar(1);scene.add(moduleHeap);
 for(let i=0;i<96;i++){const tier=Math.floor(i/16),r=(i*2.399),radius=Math.max(.25,1-tier*.14)*(.35+(i%7)*.1),part=new THREE.Group();part.position.set(Math.cos(r)*.2,.34+Math.floor(i/20)*.94,-2.1+(i%20)*.22);part.rotation.set(i*.73,i*1.31,i*.46);moduleHeap.add(part);if(i%3===0){const coil=new THREE.Mesh(new THREE.TorusGeometry(.14,.045,6,12),steel);part.add(coil);box(part,[.09,.26,.09],[0,0,0],crate);}else if(i%3===1){box(part,[.36,.08,.24],[0,0,0],crate);for(let n=0;n<3;n++)box(part,[.06,.04,.08],[n*.09-.09,.06,0],n===1?edge:black);}else{const cell=new THREE.Mesh(new THREE.CylinderGeometry(.09,.09,.32,10),steel);part.add(cell);box(part,[.14,.04,.12],[0,.18,0],edge);}}
 for(const [i,part]of moduleHeap.children.entries()){part.updateWorldMatrix(true,true);const bounds=new THREE.Box3().setFromObject(part);part.position.y+=.225+Math.floor(i/20)*1.034-bounds.min.y;}
 const storage=new THREE.Group();storage.userData.action='guns';scene.add(storage);storage.position.set(4.35,0,.2);storage.rotation.y=Math.PI;storage.scale.setScalar(1);for(const y of [1.1,2.7,4.1])box(storage,[.4,.1,5.1],[.12,y,0],steel);for(let i=0;i<18;i++){const gun=createWeaponModel(['rapid','shotgun','sniper','rocket','flame','rail'][i%6]);gun.scale.setScalar(1.2);gun.position.set(.3,1.65+Math.floor(i/9)*1.65,-2.2+(i%9)*.52);gun.rotation.set(Math.PI/2+(i%3-1)*.12,0,(i%3-1)*.1);storage.add(gun);for(const y of [1.1,2.7]){box(storage,[.45,.065,.065],[.2,y,-2.2+(i%9)*.52],steel);box(storage,[.06,.18,.08],[.43,y+.06,-2.2+(i%9)*.52],black);}}for(const x of [-3.6,3.6]){const stockLight=new THREE.PointLight(0x7da5b5,2,4.5,2);stockLight.position.set(x,2.6,-3.5);scene.add(stockLight);}

 const monitorLeft=new THREE.Group();monitorLeft.position.set(-1.75,1.75,2.8);monitorLeft.rotation.y=.16;scene.add(monitorLeft);monitorLeft.add(new THREE.Mesh(bevelHousing(1.57,2.02,.3),steel));box(monitorLeft,[1.3,1.74,.03],[0,0,.12],screen);box(monitorLeft,[.13,1.5,.13],[0,-1.4,-.1]);
 const identityMonitor=new THREE.Group();identityMonitor.position.set(-1.5,3.35,-5.8);identityMonitor.scale.setScalar(1.7);scene.add(identityMonitor);identityMonitor.add(new THREE.Mesh(bevelHousing(1.7,1.12,.25),steel));box(identityMonitor,[1.48,.92,.03],[0,0,.14],screen);box(identityMonitor,[.08,3,.08],[0,2,-.1]);dressConsole(identityMonitor,box,steel,black,1.7,1.12);
 const inventoryMonitor=new THREE.Group();inventoryMonitor.position.set(0,9,2);scene.add(inventoryMonitor);inventoryMonitor.add(new THREE.Mesh(bevelHousing(4.3,3.1,.28),steel));box(inventoryMonitor,[4,2.8,.03],[0,0,.14],screen);dressConsole(inventoryMonitor,box,steel,black,4.3,3.1);for(const x of [-1.6,1.6])box(inventoryMonitor,[.08,6,.08],[x,4.5,-.12]);
 const service=new THREE.Group();service.position.set(1.75,1.75,2.8);service.rotation.y=-.16;service.userData.blockWorkshopAction=true;scene.add(service);service.add(new THREE.Mesh(bevelHousing(1.57,2.02,.3),steel));box(service,[1.3,1.74,.03],[0,0,.12],screen);box(service,[.16,1.45,.16],[0,-1.3,-.15]);
 // A real illuminated launch control on a short pedestal, with its DOM hit area projected like the monitors.
 const deployControl=new THREE.Group();deployControl.position.set(0,1.13,2.9);deployControl.rotation.x=-.28;scene.add(deployControl);box(deployControl,[1.38,.5,.22],[0,0,0],black);box(deployControl,[1.24,.36,.04],[0,0,.13],screen);box(scene,[.18,1,.18],[0,.5,2.8],steel);box(scene,[1.05,.07,.5],[0,.03,2.8],black);
 const launchCanvas=document.createElement('canvas');launchCanvas.width=640;launchCanvas.height=180;const launchInk=launchCanvas.getContext('2d');launchInk.fillStyle='#53300b';launchInk.fillRect(0,0,640,180);launchInk.strokeStyle='#ffb936';launchInk.lineWidth=8;launchInk.strokeRect(8,8,624,164);launchInk.fillStyle='#fff1bd';launchInk.font='bold 76px sans-serif';launchInk.textAlign='center';launchInk.textBaseline='middle';launchInk.fillText('출격 준비',320,92);const launchTexture=new THREE.CanvasTexture(launchCanvas);launchTexture.colorSpace=THREE.SRGBColorSpace;const launchFace=new THREE.Mesh(new THREE.PlaneGeometry(1.2,.34),new THREE.MeshBasicMaterial({map:launchTexture}));launchFace.position.z=.155;deployControl.add(launchFace);
 for(const [side,monitor]of [[-1,monitorLeft],[1,service]]){const arm=new THREE.Group();arm.name='offscreen-monitor-arm';monitor.add(arm);const points=[[0,0,-.28],[side*.95,-.3,-.45],[side*1.6,-1.1,.25],[side*2.8,-1.5,2.2]];for(let i=0;i<points.length-1;i++){const a=new THREE.Vector3(...points[i]),b=new THREE.Vector3(...points[i+1]),beam=box(arm,[.13,.13,a.distanceTo(b)],a.clone().add(b).multiplyScalar(.5).toArray(),steel);beam.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),b.sub(a).normalize());const joint=new THREE.Mesh(new THREE.SphereGeometry(.16,12,8),black);joint.position.copy(a);arm.add(joint);}}
 dressConsole(monitorLeft,box,steel,black);dressConsole(service,box,steel,black);dressConsole(deployControl,box,steel,black,1.38,.5);
 const launchButton=new THREE.Group();deployControl.add(launchButton);deployControl.remove(launchFace);launchButton.add(launchFace);launchFace.position.z=.08;launchButton.add(new THREE.Mesh(bevelHousing(1.25,.38,.14,.04),new THREE.MeshStandardMaterial({color:0xb56a12,metalness:.45,roughness:.4})));launchButton.position.z=.1;box(deployControl,[1.34,.47,.08],[0,0,.08],black);let buttonPress=0;
 const consoleBase=new THREE.Group();consoleBase.name='integrated-service-console';scene.add(consoleBase);box(consoleBase,[5,.4,.85],[0,.35,2.85],steel);box(consoleBase,[1.7,.8,.8],[0,.65,2.85],steel);
 const cableMat=new THREE.MeshStandardMaterial({color:0x171a17,roughness:1});
 for(const side of [-1,1]){for(let i=0;i<5;i++){const points=[[side*1.75,.75,2.8],[side*(1.5+i*.08),.35,3.1],[side*.9,.3,3.3],[side*.65,.7,2.8]].map(p=>new THREE.Vector3(...p));consoleBase.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),20,.028,6,false),cableMat));}for(const y of [.45])box(consoleBase,[.4,.12,.3],[side*1.05,y,2.82],steel);}
 for(let i=0;i<28;i++){const t=i/28*Math.PI*2;const stripe=box(wheel,[.2,.02,.1],[Math.sin(t)*3.28,.01,Math.cos(t)*3.28],i%2?black:new THREE.MeshStandardMaterial({color:0xc39837,roughness:.9}));stripe.rotation.y=t;}

 const clamp=new THREE.Group();clamp.userData.action='equipment';scene.add(clamp);
 const armSegment=(a,b,width)=>{const start=new THREE.Vector3(...a),end=new THREE.Vector3(...b),m=box(clamp,[width,start.distanceTo(end),width],start.clone().add(end).multiplyScalar(.5).toArray());m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),end.sub(start).normalize());return m;};
 armSegment([2.1,.1,5.6],[1.85,.8,3.5],.22);armSegment([1.85,.8,3.5],[1.12,1.35,1.15],.17);for(const p of [[1.85,.8,3.5],[1.12,1.35,1.15]]){const joint=new THREE.Mesh(new THREE.SphereGeometry(.18,12,8),steel);joint.position.set(...p);clamp.add(joint);}for(const side of [-1,1]){armSegment([1.12,1.35,1.15],[1.12+side*.23,1.4,.78],.09);armSegment([1.12+side*.23,1.4,.78],[1.12+side*.13,1.42,.53],.08);}
 // UI pixels live on depth-tested mesh surfaces; transparent DOM retains keyboard and button semantics.
 const monitorSurfaces=new Map();
 for(const [key,group,width,height] of [['monitor:left',monitorLeft,1.3,1.74],['monitor:right',service,1.3,1.74],['monitor:identity',identityMonitor,1.48,.92],['monitor:inventory',inventoryMonitor,4,2.8]]){
  const material=new THREE.MeshBasicMaterial({color:0xffffff,toneMapped:false});
  const mesh=new THREE.Mesh(new THREE.PlaneGeometry(width,height),material);mesh.position.z=.16;mesh.visible=false;group.add(mesh);monitorSurfaces.set(key,{mesh,material,signature:null,element:null});
 }
 function paintScreen(key,element,width,height){
  if(key==='monitor:equipment')key='monitor:left';
  const surface=monitorSurfaces.get(key);if(!surface)return;
  const signature=element.innerHTML+'|'+width+'|'+height+'|'+[...element.querySelectorAll('*')].map(e=>e.scrollTop+','+e.scrollLeft).join(';');
  if(surface.signature===signature&&surface.element===element){element.style.opacity=element.contains(document.activeElement)&&document.activeElement.tagName==='INPUT'?'1':'0';return;}
  const clone=element.cloneNode(true);Object.assign(clone.style,{position:'fixed',left:'-10000px',top:'0',width:width+'px',height:height+'px',transform:'none',opacity:'1',visibility:'visible',display:'block',pointerEvents:'none',zIndex:'-1'});element.parentElement.appendChild(clone);
  const sourceNodes=[element,...element.querySelectorAll('*')],nodes=[clone,...clone.querySelectorAll('*')];nodes.forEach((e,i)=>{e.scrollTop=sourceNodes[i].scrollTop;e.scrollLeft=sourceNodes[i].scrollLeft;});
  const base=clone.getBoundingClientRect(),canvas=document.createElement('canvas');canvas.width=width*2;canvas.height=height*2;const ctx=canvas.getContext('2d');ctx.scale(2,2);ctx.fillStyle='#06313d';ctx.fillRect(0,0,width,height);
  function paint(node){
   if(node.nodeType===3){const text=node.textContent;if(!text.trim())return;const style=getComputedStyle(node.parentElement);ctx.font=style.font||`${style.fontWeight} ${style.fontSize} ${style.fontFamily}`;ctx.fillStyle=style.color;ctx.textBaseline='top';const range=document.createRange();for(let i=0;i<text.length;i++){range.setStart(node,i);range.setEnd(node,i+1);const r=range.getBoundingClientRect();if(r.width&&r.height)ctx.fillText(text[i],r.left-base.left,r.top-base.top);}return;}
   if(node.nodeType!==1)return;const style=getComputedStyle(node);if(style.display==='none'||style.visibility==='hidden')return;const r=node.getBoundingClientRect(),x=r.left-base.left,y=r.top-base.top;
   ctx.save();if(node!==clone&&(style.overflowY==='auto'||style.overflow==='hidden')){ctx.beginPath();ctx.rect(x,y,r.width,r.height);ctx.clip();}
   if(style.backgroundColor!=='rgba(0, 0, 0, 0)'){ctx.fillStyle=style.backgroundColor;ctx.fillRect(x,y,r.width,r.height);}const border=parseFloat(style.borderTopWidth);if(border){ctx.strokeStyle=style.borderTopColor;ctx.lineWidth=border;ctx.strokeRect(x,y,r.width,r.height);}
   if(node.tagName==='IMG'){const image=sourceNodes[nodes.indexOf(node)];if(image?.complete&&image.naturalWidth)ctx.drawImage(image,x,y,r.width,r.height);}else if(node.tagName==='svg'){ctx.strokeStyle='#83dfe5';ctx.lineWidth=2;const cx=x+r.width/2;ctx.beginPath();ctx.arc(cx,y+r.height*.15,r.width*.11,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(cx-r.width*.12,y+r.height*.28);ctx.lineTo(cx+r.width*.12,y+r.height*.28);ctx.lineTo(cx+r.width*.17,y+r.height*.57);ctx.lineTo(cx-r.width*.17,y+r.height*.57);ctx.closePath();ctx.moveTo(cx-r.width*.16,y+r.height*.32);ctx.lineTo(cx-r.width*.32,y+r.height*.72);ctx.moveTo(cx+r.width*.16,y+r.height*.32);ctx.lineTo(cx+r.width*.32,y+r.height*.72);ctx.moveTo(cx-r.width*.1,y+r.height*.6);ctx.lineTo(cx-r.width*.16,y+r.height*.91);ctx.moveTo(cx+r.width*.1,y+r.height*.6);ctx.lineTo(cx+r.width*.16,y+r.height*.91);ctx.stroke();}else for(const child of node.childNodes)paint(child);ctx.restore();
  }
  paint(clone);clone.remove();
  surface.material.map?.dispose();const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());surface.material.map=texture;surface.material.needsUpdate=true;surface.mesh.visible=true;surface.signature=signature;surface.element=element;element.style.opacity='0';requestDraw();
 }
 let highlighted=null;const outline=new THREE.Group();scene.add(outline);const outlineMaterial=new THREE.ShaderMaterial({uniforms:{},vertexShader:'void main(){vec3 p=position+normal*0.018;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}',fragmentShader:'void main(){gl_FragColor=vec4(0.55,0.94,1.0,1.0);}',side:THREE.BackSide});
 function highlight(node){if(node===highlighted)return;highlighted=node;outline.clear();if(node){const nodes=node.userData.action==='stash'?[moduleHeap,...room.root.children.filter(o=>o.userData.action==='stash')]:[node];for(const root of nodes){root.updateWorldMatrix(true,true);root.traverse(o=>{if(o.isMesh&&o.visible){const shell=new THREE.Mesh(o.geometry,outlineMaterial);shell.matrixAutoUpdate=false;const matrix=o.matrixWorld.clone();shell.matrix.copy(matrix);shell.raycast=()=>{};outline.add(shell);}});}}requestDraw();}

 for(const x of [-2.55,2.55]){const light=new THREE.PointLight(0x2d9eff,2.5,3,2);light.position.set(x,1.9,2.4);scene.add(light);}
 let selectedRobot=null,drag=null,suppressClick=false;const rotations=new Map(),canvas=renderer.domElement;canvas.style.touchAction='none';
 function hitAction(hit){let node=hit?.object;while(node&&!node.userData.action)node=node.parent;return ['stash','guns','gramophone'].includes(node?.userData.action)?{node,action:node.userData.action}:{node:null,action:null};}
 function hits(event){const rect=canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);scene.updateMatrixWorld(true);ray.setFromCamera(pointer,camera);return ray.intersectObjects(scene.children,true);}
 canvas.addEventListener('pointerdown',event=>{if(event.button!==0||!selectedRobot)return;const hit=hits(event)[0];if(!hit?.object.userData.rotateUnit||inspection==='modules')return;drag={id:event.pointerId,x:event.clientX,start:event.clientX};suppressClick=false;canvas.setPointerCapture(event.pointerId);canvas.style.cursor='grabbing';});
 canvas.addEventListener('pointermove',event=>{if(drag&&drag.id===event.pointerId){selectedRobot.rotation.y+=(event.clientX-drag.x)*.012;rotations.set(selectedRobot.userData.frameId,selectedRobot.rotation.y);drag.x=event.clientX;if(Math.abs(event.clientX-drag.start)>4)suppressClick=true;requestDraw();}else {const hit=hits(event)[0];const {node,action}=hitAction(hit);canvas.style.cursor=action?'pointer':hit?.object.userData.rotateUnit?'grab':'';highlight(node);onHover(action||null,{x:event.clientX,y:event.clientY});}});
 function endDrag(event){if(!drag||drag.id!==event.pointerId)return;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);drag=null;canvas.style.cursor='';}
 canvas.addEventListener('pointerleave',()=>{if(!drag){highlight(null);onHover(null);}});canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);
 // Scene props are clickable as well as their labels.
 const pointer=new THREE.Vector2(),ray=new THREE.Raycaster();renderer.domElement.addEventListener('click',event=>{if(suppressClick){suppressClick=false;return;}for(const hit of hits(event)){const {action}=hitAction(hit);let obstruction=hit.object;while(obstruction&&!obstruction.userData.blockWorkshopAction)obstruction=obstruction.parent;if(obstruction)break;if(action){if(action==='deploy')buttonPress=1;onAction(action);break;}}});

 function update(frames,selected,stash=[],slot=null){
 const occupants=hangarSlots(frames);
  if(disposed)return;
  // Selection, HP, names and inventory IDs do not change mesh geometry.
  const key=JSON.stringify(occupants.map(f=>f?[f.id,frameStats(f),f.weaponSlots?.map(w=>w?.type)]:null)),stockKey=JSON.stringify(stash.slice(0,24).map(w=>w.type));
  const n=HANGAR_SLOT_COUNT,index=slot??Math.max(0,occupants.findIndex(f=>f?.id===selected));let desired=-index*Math.PI*2/n;desired+=Math.round((angle-desired)/(Math.PI*2))*Math.PI*2;
  const selectionChanged=selectedRobot?.userData.frameId!==occupants[index]?.id;
  if(target!==desired||selectionChanged)requestDraw();target=desired;
  if(stockKey!==stockSignature){stockSignature=stockKey;for(const gun of [...storage.children].filter(o=>o.userData.storedGun))disposeObjectResources(gun);for(const [i,item]of stash.slice(0,24).entries()){const gun=createWeaponModel(item.type);gun.userData.storedGun=true;gun.scale.setScalar(.6);gun.position.set(.36,1.65+Math.floor(i/12)*1.65,-2.2+(i%12)*.39);gun.rotation.set(Math.PI/2,0,(i%3-1)*.08);storage.add(gun);}requestDraw();}
  if(key!==signature){selectedRobot=null;drag=null;signature=key;clearRigs();const ids=new Set(frames.map(f=>f.id));for(const id of rotations.keys())if(!ids.has(id))rotations.delete(id);
  for(let i=0;i<n;i++){const holder=new THREE.Group(),t=i*Math.PI*2/n;holder.position.set(Math.sin(t)*2.25,0,Math.cos(t)*2.25);holder.rotation.y=t;wheel.add(holder);const plate=new THREE.Mesh(new THREE.CylinderGeometry(.88,.94,.18,48),steel);plate.position.y=.09;plate.receiveShadow=true;plate.userData.rotateUnit=i===index&&!!occupants[i];holder.add(plate);const rim=new THREE.Mesh(new THREE.TorusGeometry(.88,.018,6,48),i===index?edge:steel);rim.rotation.x=Math.PI/2;rim.position.y=.19;rim.userData.rotateUnit=i===index&&!!occupants[i];holder.add(rim);
   let robot=null;if(occupants[i]){robot=createRobot(false,'player',1.25);robot.mixer.stopAllAction();robot.skeleton.pose();robot.root.updateMatrixWorld(true);const torso=robot.body.children.find(o=>o.isMesh&&!o.userData.cosmetic)||robot.body,sockets=robot.arms.map(a=>torso.worldToLocal(a.shoulder.getWorldPosition(new THREE.Vector3()))),socketX=(Math.abs(sockets[0].x)+Math.abs(sockets[1].x))/2,socketY=(sockets[0].y+sockets[1].y)/2;for(const [j,arm]of robot.arms.entries()){const target=torso.localToWorld(new THREE.Vector3(Math.sign(sockets[j].x)*socketX,socketY,0));arm.shoulder.position.copy(arm.shoulder.parent.worldToLocal(target));arm.shoulder.updateWorldMatrix(false,true);}robot.blaster.visible=false;if(robot.backpack)robot.backpack.visible=false;applyFrameVisual(robot,frameStats(occupants[i]));holder.add(robot.root);robot.root.scale.multiplyScalar(1.5);robot.root.position.y=0;
    for(const side of['l','r'])for(const [a,b]of[['upperarm_','lowerarm_'],['lowerarm_','hand_'],['thigh_','calf_'],['calf_','foot_']]){const bone=robot.bones.find(b=>b.name===a+side),end=robot.bones.find(node=>node.name===b+side);if(!bone||!end)continue;robot.root.updateMatrixWorld(true);const direction=end.getWorldPosition(new THREE.Vector3()).sub(bone.getWorldPosition(new THREE.Vector3())).normalize(),world=bone.getWorldQuaternion(new THREE.Quaternion());world.premultiply(new THREE.Quaternion().setFromUnitVectors(direction,new THREE.Vector3((side==='l'?1:-1)*(a==='upperarm_'?.22:a==='lowerarm_'?.12:a==='thigh_'?.16:.08),-1,0).normalize().applyQuaternion(robot.root.getWorldQuaternion(new THREE.Quaternion()))));bone.quaternion.copy(bone.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(world));}
    robot.root.updateMatrixWorld(true);const soles=robot.bones.filter(b=>b.name==='foot_l'||b.name==='foot_r');const footBounds=new THREE.Box3();for(const foot of soles)footBounds.union(new THREE.Box3().setFromObject(foot));robot.root.position.y+=.18-footBounds.min.y;robot.root.updateMatrixWorld(true);
    robot.root.userData.frameId=occupants[i].id;robot.root.rotation.y=rotations.get(occupants[i].id)||0;if(i===index)selectedRobot=robot.root;
    const unitRack=new THREE.Group();holder.add(unitRack);
    for(let slot=0;slot<2;slot++){const rack=new THREE.Group();rack.userData.action='weapon:'+slot;rack.position.set(slot===0?-1.05:1.05,0,.15);unitRack.add(rack);box(rack,[.12,2.4,.12],[0,1.4,0],black);box(rack,[.5,.08,.4],[0,.2,0]);const item=occupants[i].weaponSlots?.[slot];if(item){const gun=createWeaponModel(item.type);gun.scale.setScalar(1.1);gun.position.set(0,2,.15);gun.rotation.set(-Math.PI/2,Math.PI/2,0,'YXZ');rack.add(gun);}else box(rack,[.4,.2,.12],[0,2,.15],black);}
    for(const [boneName,key]of [['head','head'],['spine_03','chest'],['upperarm_l','arms'],['upperarm_r','arms'],['thigh_l','legs'],['thigh_r','legs']]){const bone=robot.salvageFrame?.anchors[boneName]||robot.bones.find(b=>b.name===boneName)|| (key==='head'?robot.head:null);if(bone)bone.traverse(o=>{if(o.isMesh)o.userData.action='gear:'+key;});}
    rigs.push({group:holder,robot,plate,rim,unitRack,weapon:occupants[i].weaponSlots?.find(Boolean)?.type||'pistol'});continue;



   }rigs.push({group:holder,robot,plate,rim});
  }

   requestDraw();
  }
  if(selectionChanged)drag=null;
  for(const [i,r]of rigs.entries()){const selected=i===index;r.plate.userData.rotateUnit=r.rim.userData.rotateUnit=selected&&!!r.robot;r.rim.material=selected?edge:steel;}
  selectedRobot=rigs[index]?.robot?.root||null;
 }
 let raf=null,animationTimer=null,disposed=false;
 function requestDraw(){if(!disposed&&raf===null)raf=requestAnimationFrame(draw);}
 function draw(now){
  raf=null;if(document.hidden||!host.isConnected||host.closest('[hidden]')){last=now;return;}
  const w=host.clientWidth,h=host.clientHeight;if(!w||!h){last=now;return;}
  const dt=Math.min((now-last)/1000,.05);last=now;buttonPress=Math.max(0,buttonPress-dt*5);launchButton.position.z=.1-buttonPress*.055;angle=THREE.MathUtils.damp(angle,target,6,dt);if(Math.abs(angle-target)<.0001)angle=target;wheel.rotation.y=angle;
  if(canvas.width!==Math.floor(w*renderer.getPixelRatio())||canvas.height!==Math.floor(h*renderer.getPixelRatio())){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
  const robot=rigs.find(r=>r.robot?.root===selectedRobot)?.robot;const focused=false,preparing=inspection==='prepare',inventory=inspection==='stash'||inspection==='guns',equipping=['equipment','mountWeapons','modules'].includes(inspection);inventoryAmount=THREE.MathUtils.damp(inventoryAmount,inventory?1:0,7,dt);prepareAmount=THREE.MathUtils.damp(prepareAmount,preparing?1:0,5,dt);monitorLeft.position.x=-1.75-prepareAmount*4-inventoryAmount*3;service.position.x=1.75+prepareAmount*4+inventoryAmount*3;monitorLeft.position.y=service.position.y=1.75-inventoryAmount*3;deployControl.position.y=1.13-inventoryAmount*3;inventoryMonitor.position.y=9-inventoryAmount*6.6;inventoryMonitor.visible=inventoryAmount>.001;identityAmount=THREE.MathUtils.damp(identityAmount,1,4,dt);identityMonitor.position.y=8-identityAmount*4.65;identityMonitor.visible=!preparing&&!inventory;monitorLeft.position.x=equipping?-2.1:monitorLeft.position.x;monitorLeft.position.y=equipping?2.3:monitorLeft.position.y;monitorLeft.scale.setScalar(equipping?1.6:1);consoleBase.visible=prepareAmount<.01&&inventoryAmount<.01&&!focused;monitorLeft.visible=service.visible=prepareAmount<.99;clamp.visible=false;deployControl.visible=!preparing&&!focused&&inventoryAmount<.99;
  const selectedRig=rigs.find(r=>r.robot===robot);if(robot&&preparing){if(!selectedRig.carry){selectedRig.rest=robot.bones.map(b=>({bone:b,p:b.position.clone(),q:b.quaternion.clone()}));selectedRig.baseY=robot.root.position.y;const before=new Set();robot.root.traverse(o=>before.add(o));selectedRig.carry=createThirdPersonView(robot,[selectedRig.weapon]);selectedRig.carryNodes=[];robot.root.traverse(o=>{if(!before.has(o)&&before.has(o.parent))selectedRig.carryNodes.push(o);});}selectedRig.carryNodes.forEach(o=>o.visible=true);selectedRig.carry.pose({position:new THREE.Vector3(0,selectedRig.baseY+1.7,0),yaw:Math.PI,pitch:0,weapon:selectedRig.weapon,speed:0,grounded:true,dt,time:now/1000});selectedRig.unitRack.visible=false;}else if(selectedRig?.carry){selectedRig.rest.forEach(({bone,p,q})=>{bone.position.copy(p);bone.quaternion.copy(q);});selectedRig.carryNodes.forEach(o=>o.visible=false);robot.root.position.y=selectedRig.baseY;selectedRig.unitRack.visible=true;robot.root.updateMatrixWorld(true);}
  const desiredPosition=new THREE.Vector3(equipping?-1:prepareAmount*1.35,4.65-prepareAmount*1.5,8.3-prepareAmount*2.9),look=new THREE.Vector3(equipping?-.8:prepareAmount*1.35,2,0);
  if(focused){robot.root.rotation.y=0;(robot.salvageFrame?.anchors.spine_03||robot.body).getWorldPosition(look);desiredPosition.copy(look).add(new THREE.Vector3(0,.08,1.6));}
  if(departure&&robot){const t=Math.min(1,(now-departure.start)/departure.duration),ease=t*t*(3-2*t);if(departure.mode==='recovery'){departureRig.visible=true;const lift=Math.max(0,(t-.4)/.6)**2*7;robot.root.position.y=departure.baseY+lift;departureRig.position.y=(1-Math.min(1,t/.4))*3+lift;}else{const head=robot.head.getWorldPosition(new THREE.Vector3());desiredPosition.lerp(head.clone().add(new THREE.Vector3(0,.02,.2)),ease);look.lerp(head,ease);}if(t===1&&departure.done){const done=departure.done;departure.done=null;done();}}
  camera.position.lerp(desiredPosition,1-Math.exp(-7*dt));camera.lookAt(look);openAmount=THREE.MathUtils.damp(openAmount,focused?1:0,6,dt);robot?.salvageFrame?.chestMechanism.setOpen(openAmount);
  scene.updateMatrixWorld(true);const targets=[];const put=(key,world)=>{const p=world.clone().project(camera);if(p.z>-1&&p.z<1)targets.push({key,x:(p.x*.5+.5)*w,y:(-.5*p.y+.5)*h});};
  if(robot){if(focused){const chest=robot.salvageFrame?.anchors.spine_03||robot.body;for(const slot of CHEST_SLOTS)put('module:'+slot.index,chest.localToWorld(new THREE.Vector3(...slot.position).add(new THREE.Vector3(0,0,.04))));}
   else{for(const [name,key]of [['head','head'],['spine_03','chest'],['upperarm_l','arms'],['thigh_r','legs']]){const bone=robot.salvageFrame?.anchors[name]||robot.bones.find(b=>b.name===name)||(key==='head'?robot.head:null);if(bone)put('gear:'+key,bone.getWorldPosition(new THREE.Vector3()));}
   for(let slot=0;slot<2;slot++){const rack=rigs.find(r=>r.robot===robot).unitRack;put('weapon:'+slot,rack.localToWorld(new THREE.Vector3(slot===0?-1.05:1.05,2,.3)));}}
  }
  if(!focused&&!preparing){for(const [key,group,sx,sy]of [[equipping?'monitor:equipment':'monitor:inventory',equipping?monitorLeft:inventoryMonitor,equipping?1.3:4,equipping?1.74:2.8],['monitor:identity',identityMonitor,1.48,.92],['monitor:left',monitorLeft,1.3,1.74],['monitor:right',service,1.3,1.74],['control:deploy',deployControl,1.2,.34]]){const points=[[-sx/2,-sy/2],[sx/2,sy/2],[-sx/2,sy/2],[sx/2,-sy/2]].map(([x,y])=>group.localToWorld(new THREE.Vector3(x,y,.14)).project(camera));const xs=points.map(p=>(p.x*.5+.5)*w),ys=points.map(p=>(-.5*p.y+.5)*h);targets.push({key,corners:[2,1,3,0].map(i=>({x:xs[i],y:ys[i]})),x:Math.min(...xs),y:Math.min(...ys),width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys)});}}
  onLayout(targets);room.update(dt);renderer.render(scene,camera);clearTimeout(animationTimer);animationTimer=setTimeout(requestDraw,50);if(angle!==target||Math.abs(openAmount-(focused?1:0))>.001||camera.position.distanceTo(desiredPosition)>.001)requestDraw();
 }
 const resize=new ResizeObserver(requestDraw);resize.observe(host);document.addEventListener('visibilitychange',requestDraw);window.addEventListener('resize',requestDraw);canvas.addEventListener('webglcontextrestored',requestDraw);requestDraw();
 return {update,paintScreen,pressLaunch(){buttonPress=1;requestDraw();},setRecordSpeed(speed){room.setRecordSpeed(speed);},depart(mode){return new Promise(done=>{const robot=rigs.find(r=>r.robot?.root===selectedRobot)?.robot;if(!robot){done();return;}departure={mode,start:performance.now(),duration:mode==='recovery'?1800:850,baseY:robot.root.position.y,done};requestDraw();});},resetDeparture(){if(departure){const robot=rigs.find(r=>r.robot?.root===selectedRobot)?.robot;if(robot)robot.root.position.y=departure.baseY;departure.done?.();departure=null;}departureRig.visible=false;departureRig.position.y=0;requestDraw();},inspect(mode){inspection=mode;if(mode!=='prepare')this.resetDeparture();highlight(null);requestDraw();},attach(next){if(disposed)return;resize.unobserve(host);host=next;host.appendChild(canvas);resize.observe(host);requestDraw();},dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(raf);clearTimeout(animationTimer);room.dispose();launchTexture.dispose();steel.map.dispose();resize.disconnect();document.removeEventListener('visibilitychange',requestDraw);window.removeEventListener('resize',requestDraw);canvas.removeEventListener('webglcontextrestored',requestDraw);drag=null;selectedRobot=null;rotations.clear();highlight(null);outlineMaterial.dispose();clearRigs();disposeObjectResources(scene,{sharedMaterials});sharedMaterials.forEach(m=>m.dispose());renderer.dispose();canvas.remove();}};
}
