import * as THREE from 'three';
import {createRobot,disposeRobot} from './robot.js';

// Static reclaimed room props share two small textures; only the fan blades and a small dust point cloud move.
export function createHangarRoom(){
 const root=new THREE.Group();root.name='boarded-residential-workshop';
 let seed=127;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 function surface(wood=false){const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const c=canvas.getContext('2d');c.fillStyle=wood?'#554333':'#77736a';c.fillRect(0,0,256,256);for(let i=0;i<3200;i++){const v=Math.floor(wood?45+random()*35:85+random()*55);c.fillStyle=`rgba(${v+12},${v+6},${v},${.08+random()*.25})`;c.fillRect(random()*256,random()*256,wood?15+random()*85:2+random()*20,wood?.5+random():1+random()*7);}c.strokeStyle=wood?'#241d1688':'#302e2944';for(let i=0;i<14;i++){c.beginPath();let x=random()*256,y=random()*256;c.moveTo(x,y);for(let n=0;n<5;n++){x+=wood?20:random()*20-10;y+=wood?random()*3-1.5:15;c.lineTo(x,y);}c.stroke();}const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;return t;}
 const plasterTexture=surface(),woodTexture=surface(true),plaster=new THREE.MeshStandardMaterial({map:plasterTexture,color:0x716b61,roughness:1}),wood=new THREE.MeshStandardMaterial({map:woodTexture,color:0x9d8771,roughness:.95}),metal=new THREE.MeshStandardMaterial({color:0x454b47,metalness:.45,roughness:.85}),dark=new THREE.MeshStandardMaterial({color:0x111a20,roughness:1}),sun=new THREE.MeshBasicMaterial({color:0xffe6b0});
 const box=(parent,size,pos,mat=plaster)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);mesh.position.set(...pos);mesh.receiveShadow=true;parent.add(mesh);return mesh;};
 // Wall strips leave actual window recesses, rather than painting windows on a wall.
 box(root,[14,1.8,.24],[0,.9,-6]);box(root,[14,1.1,.24],[0,5.85,-6]);for(const [x,w]of [[-5.5,3],[0,3.8],[5.5,3]])box(root,[w,3.5,.24],[x,3.55,-6]);
 for(const side of [-1,1]){box(root,[.2,6.4,10],[side*7,3.2,-1]);box(root,[.13,.18,10],[side*6.83,.15,-1],wood);}box(root,[14,.18,11],[0,6.4,-1],plaster);box(root,[14,.035,12],[0,-.03,-1],plaster);box(root,[14,.16,.18],[0,.15,-5.8],wood);
 const dustFields=[];
 const shaftMaterial=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{tint:{value:new THREE.Color(0xffe2ad)}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform vec3 tint;varying vec2 vUv;void main(){float edge=smoothstep(0.,.18,vUv.x)*smoothstep(0.,.18,1.-vUv.x);float fade=pow(1.-vUv.y,2.);gl_FragColor=vec4(tint,edge*fade*.16);}`});
 function shaft(parent,x,y,width,length=3){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute([x-width/2,y,.22,x+width/2,y,.22,x+width*.8-.65,y-1.1,length,x-width*.8-.65,y-1.1,length],3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute([0,0,1,0,1,1,0,1],2));geometry.setIndex([0,1,2,0,2,3]);const mesh=new THREE.Mesh(geometry,shaftMaterial);mesh.raycast=()=>{};parent.add(mesh);}
 function dust(parent,x,y,width,count){const data=new Float32Array(count*3),origins=[];for(let i=0;i<count;i++)origins.push({x:x+(random()-.5)*width,y:y+(random()-.5)*.25,z:.25+random()*2.8,phase:random()*6.28,speed:.04+random()*.06});const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(data,3));const material=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,vertexShader:`varying float glow;void main(){vec4 view=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*view;gl_PointSize=clamp(18./-view.z,1.,3.);glow=clamp(1.-position.z/3.3,.12,1.);}`,fragmentShader:`varying float glow;void main(){float r=length(gl_PointCoord-.5);gl_FragColor=vec4(1.,.86,.62,smoothstep(.5,.1,r)*glow*.8);}`});const points=new THREE.Points(geometry,material);points.frustumCulled=false;points.raycast=()=>{};parent.add(points);dustFields.push({geometry,data,origins});}
 let fan,record,time=0;
 for(const side of [-1,1]){const window=new THREE.Group();window.position.set(side*2.95,3.55,-5.85);root.add(window);const w=2.1,h=3.4;box(window,[w,h,.04],[0,0,-.3],dark);for(const x of [-w/2,w/2])box(window,[.12,h+.2,.18],[x,0,0],wood);for(const y of [-h/2,h/2])box(window,[w+.2,.12,.2],[0,y,0],wood);
  for(let i=0;i<7;i++){const y=-1.43+i*.47,board=box(window,[w+.08,.43,.1],[0,y,.13+(i%2)*.018],wood);board.rotation.z=(random()-.5)*.045;for(const x of [-.85,.85])box(window,[.025,.025,.018],[x,y,.2],metal);}
  const brace=box(window,[.11,3.25,.07],[side*.17,0,.23],wood);brace.rotation.z=side*.38;
  // Light begins at the board gaps; the haze never lights surfaces or casts shadows.
  for(const y of [-1.195,-.725,.215,.685]){box(window,[1.8,.025,.012],[0,y,.09],sun);shaft(window,0,y,1.8);dust(window,0,y,1.65,28);}
  if(side===1){const vent=new THREE.Group();vent.position.set(.56,1.12,.39);window.add(vent);box(vent,[.95,.95,.12],[0,0,0],metal);const ventGlow=new THREE.Mesh(new THREE.CircleGeometry(.39,24),sun);ventGlow.position.z=.07;vent.add(ventGlow);shaft(vent,0,0,.64,3.4);dust(vent,0,0,.65,48);const opening=new THREE.Mesh(new THREE.CircleGeometry(.4,24),dark);opening.material=new THREE.MeshBasicMaterial({color:0x584a32,transparent:true,opacity:.35});opening.position.z=.08;vent.add(opening);fan=new THREE.Group();fan.position.z=.11;vent.add(fan);for(let i=0;i<4;i++){const blade=box(fan,[.17,.43,.035],[0,.19,0],metal);const pivot=new THREE.Group();pivot.rotation.z=i*Math.PI/2;fan.remove(blade);pivot.add(blade);fan.add(pivot);}const hub=new THREE.Mesh(new THREE.SphereGeometry(.09,10,8),metal);hub.scale.z=.45;hub.position.z=.04;fan.add(hub);for(const radius of [.16,.29,.41]){const ring=new THREE.Mesh(new THREE.TorusGeometry(radius,.009,4,24),metal);ring.position.z=.17;vent.add(ring);}for(let i=0;i<4;i++){const bar=box(vent,[.015,.84,.015],[0,0,.18],metal);bar.rotation.z=i*Math.PI/4;}}
 }
 const donor=createRobot(false,'player',1);donor.root.updateMatrixWorld(true);
 function spare(bone,parent,pos,rotation){const source=donor.salvageFrame?.anchors[bone];if(!source)return;const part=source.clone(true);if(bone==='Head'&&donor.head){const mask=donor.head.clone();mask.position.set(0,0,0);mask.quaternion.identity();part.add(mask);}part.traverse(o=>{if(o.isMesh){o.geometry=o.geometry.clone();o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();o.castShadow=false;}});part.position.set(0,0,0);part.quaternion.identity();part.scale.setScalar(1);const bounds=new THREE.Box3().setFromObject(part),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());part.position.sub(center);const holder=new THREE.Group();holder.add(part);holder.scale.setScalar(.68/Math.max(size.x,size.y,size.z));holder.rotation.set(...rotation);holder.position.set(...pos);parent.add(holder);}
 for(const side of [-1,1]){const cabinet=new THREE.Group();cabinet.position.set(side*3.15,0,-3.85);cabinet.rotation.y=side*-.12;root.add(cabinet);const shelfLight=new THREE.PointLight(0xb7c8ca,1.3,2.8,2);shelfLight.position.set(0,2.3,1.05);cabinet.add(shelfLight);if(side===1){spare('Head',cabinet,[-.45,3.02,.12],[0,-side*.3,0]);spare('upperarm_l',cabinet,[.33,2.86,.13],[0,.3,Math.PI/2]);}else{const deck=new THREE.Group();deck.position.set(0,2.76,.12);deck.rotation.x=.24;cabinet.add(deck);box(deck,[1.75,.2,.95],[0,0,0],wood);box(deck,[1.65,.035,.87],[0,.12,0],new THREE.MeshStandardMaterial({color:0xb49a73,roughness:.8,metalness:.15}));record=new THREE.Group();record.position.set(-.2,.16,0);deck.add(record);const vinyl=new THREE.Mesh(new THREE.CylinderGeometry(.59,.59,.025,48),new THREE.MeshStandardMaterial({color:0x101316,roughness:.42,metalness:.15}));record.add(vinyl);for(let r=.21;r<.58;r+=.035){const groove=new THREE.Mesh(new THREE.TorusGeometry(r,.003,3,48),metal);groove.rotation.x=Math.PI/2;groove.position.y=.015;record.add(groove);}const label=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.03,24),new THREE.MeshStandardMaterial({color:0x9d5532,roughness:.8}));label.position.y=.01;record.add(label);box(record,[.04,.004,.12],[.06,.028,0],sun);const arm=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3([new THREE.Vector3(.65,.23,-.29),new THREE.Vector3(.56,.28,-.12),new THREE.Vector3(.2,.23,.22)]),12,.018,6,false),metal);deck.add(arm);box(deck,[.1,.06,.13],[.2,.23,.22],dark);for(const x of [.56,.75]){const dial=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,.04,12),metal);dial.rotation.x=Math.PI/2;dial.position.set(x,-.01,.49);deck.add(dial);}const lid=box(deck,[1.72,.025,.87],[0,.53,-.36],new THREE.MeshStandardMaterial({color:0xb5a077,transparent:true,opacity:.14,roughness:.3,depthWrite:false}));lid.rotation.x=-1.15;const deckLight=new THREE.PointLight(0xffd39b,10,2.5,2);deckLight.position.set(0,.9,.5);deck.add(deckLight);}for(const x of [-.83,.83])box(cabinet,[.1,2.7,.75],[x,1.35,0],wood);box(cabinet,[1.76,2.7,.07],[0,1.35,-.36],wood);for(const y of [.2,1,1.8,2.65])box(cabinet,[1.75,.08,.8],[0,y,0],wood);const door=box(cabinet,[.79,2.35,.055],[side*1.02,1.4,.5],wood);door.rotation.y=side*.6;for(let i=0;i<3;i++)spare(i===0?'Head':i===1?'upperarm_l':'calf_r',cabinet,[-.47+i*.48,1.15,.03],[0,i*.8,i===0?0:Math.PI/2]);spare('Head',cabinet,[.3,2.08,0],[0,-.5,.15]);spare('thigh_l',cabinet,[-.35,.48,0],[0,.3,Math.PI/2]);for(let i=0;i<6;i++)box(cabinet,[.18,.12,.22],[-.6+(i%3)*.23,1.91+Math.floor(i/3)*.13,.03],metal);}
 disposeRobot(donor);
 root.position.z=-5;root.scale.set(1.2,1.1,1.3);
 return {root,update(dt){time+=dt;if(record)record.rotation.y-=dt*Math.PI*2*33.333/60;if(fan)fan.rotation.z-=dt*.38;for(const field of dustFields){field.origins.forEach((p,i)=>{const z=(p.z+time*p.speed)%2.8+.22;field.data[i*3]=p.x-z*.2+Math.sin(time*.35+p.phase)*.08;field.data[i*3+1]=p.y-z*.35+Math.sin(time*.5+p.phase)*.07;field.data[i*3+2]=z;});field.geometry.attributes.position.needsUpdate=true;}},dispose(){plasterTexture.dispose();woodTexture.dispose();}};
}
