import {configureUpgradeLighting} from './asset-upgrades.js';
import * as THREE from 'three';
import {createRobot,disposeRobot} from './robot.js';
import {applyFrameVisual} from './frame-preview.js';
import {frameStats} from './salvage-campaign.js';
import {createThirdPersonView} from './third-person.js';
import {createWeaponModel} from './weapon-models.js';
import {createHangarRoom} from './hangar-room.js';
import {CHEST_SLOTS} from './salvage-chest.js';
import {disposeObjectResources} from './runtime-resources.js';

// One persistent scene: selection rotates the whole platform carousel.
export function createHangarScene(host,onAction=()=>{},onHover=()=>{},onLayout=()=>{}){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.setClearColor(0x070b10);host.appendChild(renderer.domElement);
 configureUpgradeLighting(renderer);
 const scene=new THREE.Scene();scene.fog=new THREE.Fog(0x070b10,15,34);const camera=new THREE.PerspectiveCamera(42,1,.05,45);camera.position.set(0,3.85,7.5);camera.lookAt(0,1.9,0);
 const steel=new THREE.MeshStandardMaterial({color:0x252e38,metalness:.75,roughness:.45}),black=new THREE.MeshStandardMaterial({color:0x0d141c,roughness:.8}),edge=new THREE.MeshStandardMaterial({color:0x9abfc8,emissive:0x72d3e5,emissiveIntensity:1.2}),crate=new THREE.MeshStandardMaterial({color:0x39443b,metalness:.25,roughness:.8});
 const box=(parent,size,pos,mat=steel)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);m.position.set(...pos);m.castShadow=m.receiveShadow=true;parent.add(m);return m;};
 scene.add(new THREE.HemisphereLight(0xadc9de,0x030507,.22));for(const x of[-4,0,4]){const l=new THREE.SpotLight(x===0?0xb6deef:0x50718d,x===0?24:7,16,.62,.65);l.position.set(x,5,3);l.target.position.set(x,1.5,0);l.castShadow=x===0;scene.add(l,l.target);}
 const pin=new THREE.SpotLight(0xffedcf,95,9,.31,.45,1.6);pin.position.set(0,4.65,.5);pin.target.position.set(0,1.3,0);pin.castShadow=false;scene.add(pin,pin.target);const lamp=new THREE.Mesh(new THREE.CylinderGeometry(.16,.29,.32,16),steel);lamp.position.copy(pin.position);scene.add(lamp);const lampFace=new THREE.Mesh(new THREE.CircleGeometry(.23,16),new THREE.MeshBasicMaterial({color:0xffe8ba}));lampFace.rotation.x=Math.PI/2;lampFace.position.set(0,4.48,.5);scene.add(lampFace);
 const room=createHangarRoom();scene.add(room.root);
 const departureRig=new THREE.Group();departureRig.visible=false;scene.add(departureRig);for(const x of [-.35,.35]){const hook=new THREE.Mesh(new THREE.TorusGeometry(.15,.035,8,20),steel);hook.position.set(x,3.1,0);departureRig.add(hook);const cable=new THREE.Mesh(new THREE.CylinderGeometry(.022,.022,7,8),steel);cable.position.set(x,6.6,0);departureRig.add(cable);}let departure=null,prepareAmount=0;
 const wheel=new THREE.Group();wheel.position.z=-3;scene.add(wheel);const turntable=new THREE.Mesh(new THREE.CylinderGeometry(4.4,4.5,.16,80),steel);turntable.position.y=-.10;turntable.receiveShadow=true;wheel.add(turntable);const outerRing=new THREE.Mesh(new THREE.TorusGeometry(4.34,.035,6,80),edge);outerRing.rotation.x=Math.PI/2;outerRing.position.y=-.005;wheel.add(outerRing);let inspection=null,openAmount=0,rigs=[],signature='',stockSignature='',target=0,angle=0,last=performance.now();
 const screen=new THREE.MeshStandardMaterial({color:0x063356,emissive:0x168cdd,emissiveIntensity:1.4,roughness:.35});const sharedMaterials=[steel,black,edge,crate,screen];
 function clearRigs(){for(const r of rigs){if(r.robot)disposeRobot(r.robot);disposeObjectResources(r.group,{sharedMaterials});}rigs=[];}
 for(let i=0;i<16;i++){const stack=new THREE.Group();stack.userData.action='stash';scene.add(stack);stack.position.set(-3.35+(i%4)*.42,1.4+Math.floor(i/4)*.45,.15+(i%3)*.3);stack.rotation.set((i%3-1)*.07,i*1.71,(i%4-1.5)*.07);box(stack,[.57,.35,.5],[0,0,0],crate);box(stack,[.6,.04,.52],[0,.18,0]);box(stack,[.13,.06,.02],[0,0,.26],edge);}
 for(const x of [-2.75,2.75]){box(scene,[2.1,.16,1.55],[x,.8,.3],steel);for(const leg of [-.8,.8])box(scene,[.1,.8,.1],[x+leg,.35,.3],black);}
 // The loose weapon pile is warehouse stock; each unit's rack lives on its holder.
 const storage=new THREE.Group();storage.userData.action='guns';scene.add(storage);storage.position.set(2.75,0,.05);box(storage,[2.1,.2,1.1],[0,.95,0],black);for(let i=0;i<10;i++){const gun=createWeaponModel(['rapid','shotgun','sniper'][i%3]);gun.scale.setScalar(.85);gun.position.set((i%3-1)*.48,1.4+Math.floor(i/3)*.4,(i%2)*.3);gun.rotation.set(-Math.PI/2,.3*i,.25);storage.add(gun);}for(const x of [-2.75,2.75]){const stockLight=new THREE.PointLight(0x7da5b5,10,3.5,2);stockLight.position.set(x,3.1,1.2);scene.add(stockLight);}

 const monitorLeft=new THREE.Group();monitorLeft.position.set(-1.75,1.55,2.8);monitorLeft.rotation.y=.16;scene.add(monitorLeft);box(monitorLeft,[1.45,1.9,.2],[0,0,0],black);box(monitorLeft,[1.3,1.74,.03],[0,0,.12],screen);box(monitorLeft,[.13,1.5,.13],[0,-1.4,-.1]);
 const service=new THREE.Group();service.position.set(1.75,1.55,2.8);service.rotation.y=-.16;service.userData.action='supplies';scene.add(service);box(service,[1.45,1.9,.2],[0,0,0],black);box(service,[1.3,1.74,.03],[0,0,.12],screen);box(service,[.16,1.45,.16],[0,-1.3,-.15]);
 const clamp=new THREE.Group();clamp.userData.action='equipment';scene.add(clamp);
 const armSegment=(a,b,width)=>{const start=new THREE.Vector3(...a),end=new THREE.Vector3(...b),m=box(clamp,[width,start.distanceTo(end),width],start.clone().add(end).multiplyScalar(.5).toArray());m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),end.sub(start).normalize());return m;};
 armSegment([2.1,.1,5.6],[1.85,.8,3.5],.22);armSegment([1.85,.8,3.5],[1.12,1.35,1.15],.17);for(const p of [[1.85,.8,3.5],[1.12,1.35,1.15]]){const joint=new THREE.Mesh(new THREE.SphereGeometry(.18,12,8),steel);joint.position.set(...p);clamp.add(joint);}for(const side of [-1,1]){armSegment([1.12,1.35,1.15],[1.12+side*.23,1.4,.78],.09);armSegment([1.12+side*.23,1.4,.78],[1.12+side*.13,1.42,.53],.08);}
 let highlighted=null;const outline=new THREE.Group();scene.add(outline);const outlineMaterial=new THREE.LineBasicMaterial({color:0x95edff,transparent:true,opacity:.7,depthTest:true});
 function highlight(node){if(node===highlighted)return;highlighted=node;for(const edge of [...outline.children]){edge.geometry.dispose();outline.remove(edge);}if(node){node.updateWorldMatrix(true,true);let count=0;node.traverse(o=>{if(o.isMesh&&o.visible&&count++<64){const edge=new THREE.LineSegments(new THREE.EdgesGeometry(o.geometry,35),outlineMaterial);edge.matrixAutoUpdate=false;edge.matrix.copy(o.matrixWorld);outline.add(edge);}});}requestDraw();}
 for(const x of [-2.55,2.55]){const light=new THREE.PointLight(0x2d9eff,2.5,3,2);light.position.set(x,1.9,2.4);scene.add(light);}
 let selectedRobot=null,drag=null,suppressClick=false;const rotations=new Map(),canvas=renderer.domElement;canvas.style.touchAction='none';
 function hitAction(hit){let node=hit?.object;while(node&&!node.userData.action)node=node.parent;if(inspection==='modules'&&hit&&selectedRobot){const robot=rigs.find(r=>r.robot?.root===selectedRobot)?.robot,chest=robot?.salvageFrame?.anchors.spine_03;if(chest){const p=chest.worldToLocal(hit.point.clone());for(const slot of CHEST_SLOTS){if(Math.abs(p.x-slot.position[0])<slot.size[0]*.7&&Math.abs(p.y-slot.position[1])<slot.size[1]*.7&&Math.abs(p.z-slot.position[2])<.08)return {node:hit.object,action:'module:'+slot.index};}}}return {node,action:node?.userData.action};}
 function hits(event){const rect=canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);scene.updateMatrixWorld(true);ray.setFromCamera(pointer,camera);return ray.intersectObjects(scene.children,true);}
 canvas.addEventListener('pointerdown',event=>{if(event.button!==0||!selectedRobot)return;const hit=hits(event)[0];if(!hit?.object.userData.rotateUnit||inspection==='modules')return;drag={id:event.pointerId,x:event.clientX,start:event.clientX};suppressClick=false;canvas.setPointerCapture(event.pointerId);canvas.style.cursor='grabbing';});
 canvas.addEventListener('pointermove',event=>{if(drag&&drag.id===event.pointerId){selectedRobot.rotation.y+=(event.clientX-drag.x)*.012;rotations.set(selectedRobot.userData.frameId,selectedRobot.rotation.y);drag.x=event.clientX;if(Math.abs(event.clientX-drag.start)>4)suppressClick=true;requestDraw();}else {const hit=hits(event)[0];const {node,action}=hitAction(hit);canvas.style.cursor=action?'pointer':hit?.object.userData.rotateUnit?'grab':'';highlight(node);onHover(action||null);}});
 function endDrag(event){if(!drag||drag.id!==event.pointerId)return;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);drag=null;canvas.style.cursor='';}
 canvas.addEventListener('pointerleave',()=>{if(!drag){highlight(null);onHover(null);}});canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);
 // Scene props are clickable as well as their labels.
 const pointer=new THREE.Vector2(),ray=new THREE.Raycaster();renderer.domElement.addEventListener('click',event=>{if(suppressClick){suppressClick=false;return;}for(const hit of hits(event)){const {action}=hitAction(hit);if(action){onAction(action);break;}}});

 function update(frames,selected,stash=[]){
  if(disposed)return;
  // Selection, HP, names and inventory IDs do not change mesh geometry.
  const key=JSON.stringify(frames.map(f=>[f.id,frameStats(f),f.weaponSlots?.map(w=>w?.type)])),stockKey=JSON.stringify(stash.slice(0,24).map(w=>w.type));
  const n=Math.max(4,frames.length),index=Math.max(0,frames.findIndex(f=>f.id===selected));let desired=-index*Math.PI*2/n;desired+=Math.round((angle-desired)/(Math.PI*2))*Math.PI*2;
  const selectionChanged=selectedRobot?.userData.frameId!==frames[index]?.id;
  if(target!==desired||selectionChanged)requestDraw();target=desired;
  if(stockKey!==stockSignature){stockSignature=stockKey;for(const gun of [...storage.children].filter(o=>o.userData.storedGun))disposeObjectResources(gun);for(const [i,item]of stash.slice(0,24).entries()){const gun=createWeaponModel(item.type);gun.userData.storedGun=true;gun.scale.setScalar(.6);gun.position.set(-.7+(i%4)*.4,.55+Math.floor(i/4)*.25,-.35+(i%3)*.3);gun.rotation.set((i%3-1)*.35,i*2.39,(i%2?1:-1)*(.25+(i%4)*.18));storage.add(gun);}requestDraw();}
  if(key!==signature){selectedRobot=null;drag=null;signature=key;clearRigs();const ids=new Set(frames.map(f=>f.id));for(const id of rotations.keys())if(!ids.has(id))rotations.delete(id);
  for(let i=0;i<n;i++){const holder=new THREE.Group(),t=i*Math.PI*2/n;holder.position.set(Math.sin(t)*3,0,Math.cos(t)*3);holder.rotation.y=t;wheel.add(holder);const plate=new THREE.Mesh(new THREE.CylinderGeometry(1.12,1.2,.18,48),steel);plate.position.y=.09;plate.receiveShadow=true;plate.userData.rotateUnit=i===index&&!!frames[i];holder.add(plate);const rim=new THREE.Mesh(new THREE.TorusGeometry(1.12,.018,6,48),i===index?edge:steel);rim.rotation.x=Math.PI/2;rim.position.y=.19;rim.userData.rotateUnit=i===index&&!!frames[i];holder.add(rim);
   let robot=null;if(frames[i]){robot=createRobot(false,'player',1.25);robot.mixer.stopAllAction();robot.skeleton.pose();robot.root.updateMatrixWorld(true);const torso=robot.body.children.find(o=>o.isMesh&&!o.userData.cosmetic)||robot.body,sockets=robot.arms.map(a=>torso.worldToLocal(a.shoulder.getWorldPosition(new THREE.Vector3()))),socketX=(Math.abs(sockets[0].x)+Math.abs(sockets[1].x))/2,socketY=(sockets[0].y+sockets[1].y)/2;for(const [j,arm]of robot.arms.entries()){const target=torso.localToWorld(new THREE.Vector3(Math.sign(sockets[j].x)*socketX,socketY,0));arm.shoulder.position.copy(arm.shoulder.parent.worldToLocal(target));arm.shoulder.updateWorldMatrix(false,true);}robot.blaster.visible=false;if(robot.backpack)robot.backpack.visible=false;applyFrameVisual(robot,frameStats(frames[i]));holder.add(robot.root);robot.root.scale.multiplyScalar(1.5);robot.root.position.y=0;
    for(const side of['l','r'])for(const [a,b]of[['upperarm_','lowerarm_'],['lowerarm_','hand_'],['thigh_','calf_'],['calf_','foot_']]){const bone=robot.bones.find(b=>b.name===a+side),end=robot.bones.find(node=>node.name===b+side);if(!bone||!end)continue;robot.root.updateMatrixWorld(true);const direction=end.getWorldPosition(new THREE.Vector3()).sub(bone.getWorldPosition(new THREE.Vector3())).normalize(),world=bone.getWorldQuaternion(new THREE.Quaternion());world.premultiply(new THREE.Quaternion().setFromUnitVectors(direction,new THREE.Vector3((side==='l'?1:-1)*(a==='upperarm_'?.22:a==='lowerarm_'?.12:a==='thigh_'?.16:.08),-1,0).normalize().applyQuaternion(robot.root.getWorldQuaternion(new THREE.Quaternion()))));bone.quaternion.copy(bone.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(world));}
    robot.root.updateMatrixWorld(true);const soles=robot.bones.filter(b=>b.name==='foot_l'||b.name==='foot_r');const footBounds=new THREE.Box3();for(const foot of soles)footBounds.union(new THREE.Box3().setFromObject(foot));robot.root.position.y+=.18-footBounds.min.y;robot.root.updateMatrixWorld(true);
    robot.root.userData.frameId=frames[i].id;robot.root.rotation.y=rotations.get(frames[i].id)||0;if(i===index)selectedRobot=robot.root;
    const unitRack=new THREE.Group();holder.add(unitRack);
    for(let slot=0;slot<2;slot++){const rack=new THREE.Group();rack.userData.action='weapon:'+slot;rack.position.set(slot===0?-1.05:1.05,0,.15);unitRack.add(rack);box(rack,[.12,2.4,.12],[0,1.4,0],black);box(rack,[.5,.08,.4],[0,.2,0]);const item=frames[i].weaponSlots?.[slot];if(item){const gun=createWeaponModel(item.type);gun.scale.setScalar(1.1);gun.position.set(0,2,.15);gun.rotation.set(-Math.PI/2,Math.PI/2,0,'YXZ');rack.add(gun);}else box(rack,[.4,.2,.12],[0,2,.15],black);}
    for(const [boneName,key]of [['head','head'],['spine_03','chest'],['upperarm_l','arms'],['upperarm_r','arms'],['thigh_l','legs'],['thigh_r','legs']]){const bone=robot.salvageFrame?.anchors[boneName]||robot.bones.find(b=>b.name===boneName)|| (key==='head'?robot.head:null);if(bone)bone.traverse(o=>{if(o.isMesh)o.userData.action='gear:'+key;});}
    rigs.push({group:holder,robot,plate,rim,unitRack,weapon:frames[i].weaponSlots?.find(Boolean)?.type||'pistol'});continue;



   }rigs.push({group:holder,robot,plate,rim});
  }

   requestDraw();
  }
  if(selectionChanged)drag=null;
  for(const [i,r]of rigs.entries()){const selected=i===index;r.plate.userData.rotateUnit=r.rim.userData.rotateUnit=selected&&!!r.robot;r.rim.material=selected?edge:steel;}
  selectedRobot=rigs[index]?.robot?.root||null;
 }
 let raf=null,animationTimer=null,disposed=false;
 function requestDraw(){if(!disposed&&raf===null)raf=requestAnimationFrame(draw);}
 function draw(now){
  raf=null;if(document.hidden||!host.isConnected||host.closest('[hidden]')){last=now;return;}
  const w=host.clientWidth,h=host.clientHeight;if(!w||!h){last=now;return;}
  const dt=Math.min((now-last)/1000,.05);last=now;angle=THREE.MathUtils.damp(angle,target,6,dt);if(Math.abs(angle-target)<.0001)angle=target;wheel.rotation.y=angle;
  if(canvas.width!==Math.floor(w*renderer.getPixelRatio())||canvas.height!==Math.floor(h*renderer.getPixelRatio())){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
  const robot=rigs.find(r=>r.robot?.root===selectedRobot)?.robot;const focused=inspection==='modules'&&robot,preparing=inspection==='prepare';prepareAmount=THREE.MathUtils.damp(prepareAmount,preparing?1:0,5,dt);monitorLeft.position.x=-1.75-prepareAmount*4;service.position.x=1.75+prepareAmount*4;monitorLeft.visible=service.visible=prepareAmount<.99;clamp.visible=!preparing;
  const selectedRig=rigs.find(r=>r.robot===robot);if(robot&&preparing){if(!selectedRig.carry){selectedRig.rest=robot.bones.map(b=>({bone:b,p:b.position.clone(),q:b.quaternion.clone()}));selectedRig.baseY=robot.root.position.y;const before=new Set();robot.root.traverse(o=>before.add(o));selectedRig.carry=createThirdPersonView(robot,[selectedRig.weapon]);selectedRig.carryNodes=[];robot.root.traverse(o=>{if(!before.has(o)&&before.has(o.parent))selectedRig.carryNodes.push(o);});}selectedRig.carryNodes.forEach(o=>o.visible=true);selectedRig.carry.pose({position:new THREE.Vector3(0,selectedRig.baseY+1.7,0),yaw:Math.PI,pitch:0,weapon:selectedRig.weapon,speed:0,grounded:true,dt,time:now/1000});selectedRig.unitRack.visible=false;}else if(selectedRig?.carry){selectedRig.rest.forEach(({bone,p,q})=>{bone.position.copy(p);bone.quaternion.copy(q);});selectedRig.carryNodes.forEach(o=>o.visible=false);robot.root.position.y=selectedRig.baseY;selectedRig.unitRack.visible=true;robot.root.updateMatrixWorld(true);}
  const desiredPosition=new THREE.Vector3(prepareAmount*1.35,3.85-prepareAmount*.7,7.5-prepareAmount*2.1),look=new THREE.Vector3(prepareAmount*1.35,1.9,0);
  if(focused){robot.root.rotation.y=0;(robot.salvageFrame?.anchors.spine_03||robot.body).getWorldPosition(look);desiredPosition.copy(look).add(new THREE.Vector3(0,.08,1.6));}
  if(departure&&robot){const t=Math.min(1,(now-departure.start)/departure.duration),ease=t*t*(3-2*t);if(departure.mode==='recovery'){departureRig.visible=true;const lift=Math.max(0,(t-.4)/.6)**2*7;robot.root.position.y=departure.baseY+lift;departureRig.position.y=(1-Math.min(1,t/.4))*3+lift;}else{const head=robot.head.getWorldPosition(new THREE.Vector3());desiredPosition.lerp(head.clone().add(new THREE.Vector3(0,.02,.2)),ease);look.lerp(head,ease);}if(t===1&&departure.done){const done=departure.done;departure.done=null;done();}}
  camera.position.lerp(desiredPosition,1-Math.exp(-7*dt));camera.lookAt(look);openAmount=THREE.MathUtils.damp(openAmount,focused?1:0,6,dt);robot?.salvageFrame?.chestMechanism.setOpen(openAmount);
  scene.updateMatrixWorld(true);const targets=[];const put=(key,world)=>{const p=world.clone().project(camera);if(p.z>-1&&p.z<1)targets.push({key,x:(p.x*.5+.5)*w,y:(-.5*p.y+.5)*h});};
  if(robot){if(focused){const chest=robot.salvageFrame?.anchors.spine_03||robot.body;for(const slot of CHEST_SLOTS)put('module:'+slot.index,chest.localToWorld(new THREE.Vector3(...slot.position).add(new THREE.Vector3(0,0,.04))));}
   else{for(const [name,key]of [['head','head'],['spine_03','chest'],['upperarm_l','arms'],['thigh_r','legs']]){const bone=robot.salvageFrame?.anchors[name]||robot.bones.find(b=>b.name===name)||(key==='head'?robot.head:null);if(bone)put('gear:'+key,bone.getWorldPosition(new THREE.Vector3()));}
   for(let slot=0;slot<2;slot++){const rack=rigs.find(r=>r.robot===robot).unitRack;put('weapon:'+slot,rack.localToWorld(new THREE.Vector3(slot===0?-1.05:1.05,2,.3)));}}
  }
  if(!focused&&!preparing){for(const [key,group,sx,sy]of [['monitor:left',monitorLeft,1.3,1.74],['monitor:right',service,1.3,1.74]]){const points=[[-sx/2,-sy/2],[sx/2,sy/2],[-sx/2,sy/2],[sx/2,-sy/2]].map(([x,y])=>group.localToWorld(new THREE.Vector3(x,y,.14)).project(camera));const xs=points.map(p=>(p.x*.5+.5)*w),ys=points.map(p=>(-.5*p.y+.5)*h);targets.push({key,corners:[2,1,3,0].map(i=>({x:xs[i],y:ys[i]})),x:Math.min(...xs),y:Math.min(...ys),width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys)});}}
  onLayout(targets);room.update(dt);renderer.render(scene,camera);clearTimeout(animationTimer);animationTimer=setTimeout(requestDraw,50);if(angle!==target||Math.abs(openAmount-(focused?1:0))>.001||camera.position.distanceTo(desiredPosition)>.001)requestDraw();
 }
 const resize=new ResizeObserver(requestDraw);resize.observe(host);document.addEventListener('visibilitychange',requestDraw);window.addEventListener('resize',requestDraw);canvas.addEventListener('webglcontextrestored',requestDraw);requestDraw();
 return {update,depart(mode){return new Promise(done=>{const robot=rigs.find(r=>r.robot?.root===selectedRobot)?.robot;if(!robot){done();return;}departure={mode,start:performance.now(),duration:mode==='recovery'?1800:850,baseY:robot.root.position.y,done};requestDraw();});},resetDeparture(){if(departure){const robot=rigs.find(r=>r.robot?.root===selectedRobot)?.robot;if(robot)robot.root.position.y=departure.baseY;departure.done?.();departure=null;}departureRig.visible=false;departureRig.position.y=0;requestDraw();},inspect(mode){inspection=mode;if(mode!=='prepare')this.resetDeparture();highlight(null);requestDraw();},attach(next){if(disposed)return;resize.unobserve(host);host=next;host.appendChild(canvas);resize.observe(host);requestDraw();},dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(raf);clearTimeout(animationTimer);room.dispose();resize.disconnect();document.removeEventListener('visibilitychange',requestDraw);window.removeEventListener('resize',requestDraw);canvas.removeEventListener('webglcontextrestored',requestDraw);drag=null;selectedRobot=null;rotations.clear();highlight(null);outlineMaterial.dispose();clearRigs();disposeObjectResources(scene,{sharedMaterials});sharedMaterials.forEach(m=>m.dispose());renderer.dispose();canvas.remove();}};
}
