// A single looping track survives hangar/briefing transitions without restarting.
export function createHangarMusic(){
 const audio=new Audio();const extension=audio.canPlayType?.('audio/ogg; codecs=vorbis')===''?'mp3':'ogg';audio.src=new URL(`./audio/hangar-chanson-dans-la-nuit.${extension}`,document.baseURI).href;audio.loop=true;audio.volume=.35;audio.preload='none';audio.hidden=true;audio.setAttribute?.('aria-label','정비실 BGM');document.body?.append(audio);let enabled=false,phase='hangar',fadeTimer=null,returned=false;
 const track=(name,loop=false)=>{const a=new Audio(new URL('./audio/'+name,document.baseURI).href);a.loop=loop;a.preload='none';a.volume=loop ? .35 : .75;a.hidden=true;a.setAttribute?.('aria-label',name);document.body?.append(a);return a;};
 const click=track('sortie-click.wav'),entry=track('sortie-entry.wav'),game=track('sortie-game.'+extension,true),exit=track('sortie-return.wav');const tracks=[audio,click,entry,game,exit];
 const play=a=>{if(!document.hidden)a.play().catch(()=>{});};
 const stop=a=>{a.pause();a.currentTime=0;};
 const fade=(a,to,ms=1800)=>{const from=a.volume,start=performance.now();return {a,from,to,start,ms};};
 let fades=[];const crossfade=(next)=>{clearInterval(fadeTimer);fades=tracks.filter(a=>a.loop).map(a=>fade(a,a===next ? .35 : 0));next.volume=0;play(next);fadeTimer=setInterval(()=>{let done=true;for(const f of fades){const t=Math.min(1,(performance.now()-f.start)/f.ms);f.a.volume=f.from+(f.to-f.from)*t;if(t<1)done=false;else if(f.to===0)f.a.pause();}if(done){clearInterval(fadeTimer);fadeTimer=null;}},40);};
 entry.addEventListener?.('ended',()=>{if(phase==='entry'){phase='game';audio.pause();audio.volume=.35;game.volume=.35;play(game);}});

 const sync=()=>{if(phase!=='hangar'){if(document.hidden)tracks.forEach(a=>a.pause());else if(phase==='game')play(game);else if(phase==='entry')play(entry);return;}if(enabled&&!document.hidden)audio.play().catch(error=>{audio.setAttribute?.('data-playback-error',error.name);});else audio.pause();};
 document.addEventListener('click',sync);document.addEventListener('pointerdown',sync);document.addEventListener('keydown',sync);document.addEventListener('visibilitychange',sync);
 return {startGame(){clearInterval(fadeTimer);fadeTimer=null;returned=false;enabled=false;phase='game';audio.pause();stop(entry);stop(exit);game.volume=.35;play(game);},launchClick(){returned=false;clearInterval(fadeTimer);for(const a of [entry,game,exit])stop(a);phase='hangar';enabled=true;audio.volume=.35;play(audio);for(const a of [entry,game]){a.preload='auto';a.load();}stop(click);play(click);},enter(){phase='entry';enabled=false;audio.pause();stop(entry);stop(game);play(entry);},returnHome(){if(returned)return;returned=true;phase='hangar';enabled=true;stop(entry);stop(exit);play(exit);crossfade(audio);},setActive(active){enabled=active;if(active&&phase==='game')this.returnHome();sync();},dispose(){clearInterval(fadeTimer);for(const a of tracks.slice(1)){a.pause();a.removeAttribute('src');a.load();a.remove?.();}enabled=false;audio.pause();audio.removeAttribute('src');audio.load();audio.remove?.();document.removeEventListener('click',sync);document.removeEventListener('pointerdown',sync);document.removeEventListener('keydown',sync);document.removeEventListener('visibilitychange',sync);}};
}
