import * as THREE from 'three';
import {createRobot,disposeRobot} from './robot.js';
import {workshopMetal,addWorkshopDetails,refineWorkshop} from './hangar-workshop-details.js';

// Static reclaimed room props share two small textures; only the fan blades and a small dust point cloud move.
export function createHangarRoom(){
 const root=new THREE.Group();root.name='boarded-residential-workshop';
 let seed=127;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 function surface(wood=false){const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const c=canvas.getContext('2d');c.fillStyle=wood?'#554333':'#77736a';c.fillRect(0,0,256,256);for(let i=0;i<3200;i++){const v=Math.floor(wood?45+random()*35:85+random()*55);c.fillStyle=`rgba(${v+12},${v+6},${v},${.08+random()*.25})`;c.fillRect(random()*256,random()*256,wood?15+random()*85:2+random()*20,wood?.5+random():1+random()*7);}c.strokeStyle=wood?'#241d1688':'#302e2944';for(let i=0;i<14;i++){c.beginPath();let x=random()*256,y=random()*256;c.moveTo(x,y);for(let n=0;n<5;n++){x+=wood?20:random()*20-10;y+=wood?random()*3-1.5:15;c.lineTo(x,y);}c.stroke();}const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;return t;}
 const plasterTexture=surface(),woodTexture=surface(true),plaster=new THREE.MeshStandardMaterial({map:plasterTexture,color:0x716b61,roughness:1}),wood=new THREE.MeshStandardMaterial({map:woodTexture,color:0x9d8771,roughness:.95}),metal=new THREE.MeshStandardMaterial({color:0x454b47,metalness:.45,roughness:.85}),dark=new THREE.MeshStandardMaterial({color:0x111a20,roughness:1}),sun=new THREE.MeshBasicMaterial({color:0xffe6b0});
 const box=(parent,size,pos,mat=plaster)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);mesh.position.set(...pos);mesh.receiveShadow=true;parent.add(mesh);return mesh;};
 // Wall strips leave actual window recesses, rather than painting windows on a wall.
 box(root,[10,1.8,.24],[0,.9,-6]);box(root,[10,1.1,.24],[0,5.85,-6]);for(const [x,w]of [[-4.5,1],[0,3.8],[4.5,1]])box(root,[w,3.5,.24],[x,3.55,-6]);
 for(const side of [-1,1]){box(root,[.2,6.4,10],[side*5,3.2,-1]);box(root,[.13,.18,10],[side*4.83,.15,-1],wood);}box(root,[10,.18,11],[0,6.4,-1],plaster);box(root,[10,.035,12],[0,-.03,-1],plaster);box(root,[10,.16,.18],[0,.15,-5.8],wood);
 const dustFields=[];
 const shaftMaterial=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{tint:{value:new THREE.Color(0xffe2ad)}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform vec3 tint;varying vec2 vUv;void main(){float edge=smoothstep(0.,.18,vUv.x)*smoothstep(0.,.18,1.-vUv.x);float fade=pow(1.-vUv.y,2.);gl_FragColor=vec4(tint,edge*fade*.16);}`});
 function shaft(parent,x,y,width,length=3){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute([x-width/2,y,.22,x+width/2,y,.22,x+width*.8-.65,y-1.1,length,x-width*.8-.65,y-1.1,length],3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute([0,0,1,0,1,1,0,1],2));geometry.setIndex([0,1,2,0,2,3]);const mesh=new THREE.Mesh(geometry,shaftMaterial);mesh.raycast=()=>{};parent.add(mesh);return mesh;}
 function dust(parent,x,y,width,count){const data=new Float32Array(count*3),origins=[];for(let i=0;i<count;i++)origins.push({x:x+(random()-.5)*width,y:y+(random()-.5)*.25,z:.25+random()*2.8,phase:random()*6.28,speed:.04+random()*.06});const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(data,3));const material=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,vertexShader:`varying float glow;void main(){vec4 view=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*view;gl_PointSize=clamp(62./-view.z,2.5,6.5);glow=clamp(1.-position.z/3.3,.12,1.);}`,fragmentShader:`varying float glow;void main(){float r=length(gl_PointCoord-.5);gl_FragColor=vec4(1.,.86,.62,smoothstep(.5,.1,r)*glow*.95);}`});const points=new THREE.Points(geometry,material);points.frustumCulled=false;points.raycast=()=>{};parent.add(points);dustFields.push({geometry,data,origins});}
 let fan,record,ventBeam,time=0;
 for(const side of [-1,1]){const window=new THREE.Group();window.position.set(side*2.95,3.55,-5.85);root.add(window);const w=2.1,h=3.4;box(window,[w,h,.04],[0,0,-.3],dark);for(const x of [-w/2,w/2])box(window,[.12,h+.2,.18],[x,0,0],wood);for(const y of [-h/2,h/2])box(window,[w+.2,.12,.2],[0,y,0],wood);
  for(let i=0;i<7;i++){const y=-1.43+i*.47,board=box(window,[w+.08,.43,.1],[0,y,.13+(i%2)*.018],wood);board.rotation.z=(random()-.5)*.045;for(const x of [-.85,.85])box(window,[.025,.025,.018],[x,y,.2],metal);}
  const brace=box(window,[.11,3.25,.07],[side*.17,0,.23],wood);brace.rotation.z=side*.38;
  // Light begins at the board gaps; the haze never lights surfaces or casts shadows.
  for(const y of [-1.195,-.725,.215,.685]){box(window,[1.8,.025,.012],[0,y,.09],sun);shaft(window,0,y,1.8);dust(window,0,y,1.65,42);}
  if(side===1){const vent=new THREE.Group();vent.position.set(.56,1.12,.39);window.add(vent);box(vent,[.95,.95,.12],[0,0,0],metal);const ventGlow=new THREE.Mesh(new THREE.CircleGeometry(.39,24),sun);ventGlow.position.z=.07;vent.add(ventGlow);ventBeam=shaft(vent,0,0,.85,3.4);ventBeam.material=shaftMaterial.clone();ventBeam.material.uniforms.rotation={value:0};ventBeam.material.fragmentShader=`uniform vec3 tint;uniform float rotation;varying vec2 vUv;void main(){float edge=smoothstep(0.,.18,vUv.x)*smoothstep(0.,.18,1.-vUv.x);float angle=atan((vUv.x-.5)*2.,.2+vUv.y*.55)-rotation;float shadow=pow(max(0.,cos(angle*4.)),5.);float fade=pow(1.-vUv.y,1.6);gl_FragColor=vec4(tint,edge*fade*(1.-shadow*.92)*.32);}`;dust(vent,0,0,.65,48);const opening=new THREE.Mesh(new THREE.CircleGeometry(.4,24),dark);opening.material=new THREE.MeshBasicMaterial({color:0x584a32,transparent:true,opacity:.35});opening.position.z=.08;vent.add(opening);fan=new THREE.Group();fan.position.z=.11;vent.add(fan);for(let i=0;i<4;i++){const blade=box(fan,[.25,.5,.035],[0,.2,0],metal);const pivot=new THREE.Group();pivot.rotation.z=i*Math.PI/2;fan.remove(blade);pivot.add(blade);fan.add(pivot);}const hub=new THREE.Mesh(new THREE.SphereGeometry(.09,10,8),metal);hub.scale.z=.45;hub.position.z=.04;fan.add(hub);for(const radius of [.16,.29,.41]){const ring=new THREE.Mesh(new THREE.TorusGeometry(radius,.009,4,24),metal);ring.position.z=.17;vent.add(ring);}for(let i=0;i<4;i++){const bar=box(vent,[.015,.84,.015],[0,0,.18],metal);bar.rotation.z=i*Math.PI/4;}}
 }
 const donor=createRobot(false,'player',1);donor.root.updateMatrixWorld(true);
 function spare(bone,parent,pos,rotation){const source=donor.salvageFrame?.anchors[bone];if(!source)return;const part=source.clone(true);if(bone==='Head'&&donor.head){const mask=donor.head.clone();mask.position.set(0,0,0);mask.quaternion.identity();part.add(mask);}part.traverse(o=>{if(o.isMesh){o.geometry=o.geometry.clone();o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();o.castShadow=false;}});part.position.set(0,0,0);part.quaternion.identity();part.scale.setScalar(1);const bounds=new THREE.Box3().setFromObject(part),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());part.position.sub(center);const holder=new THREE.Group();holder.add(part);holder.scale.setScalar(.68/Math.max(size.x,size.y,size.z));holder.rotation.set(...rotation);holder.position.set(...pos);parent.add(holder);}
 const cabinet=new THREE.Group();cabinet.name='assembly-workbench';cabinet.position.set(0,0,-4.55);root.add(cabinet);box(cabinet,[4.8,.15,1.5],[0,1.98,0],wood);for(const x of [-2.15,2.15])for(const z of [-.55,.55])box(cabinet,[.13,1.95,.13],[x,.98,z],metal);
 const deck=new THREE.Group();deck.position.set(-1.42,2.12,.12);deck.scale.setScalar(.7);deck.rotation.y=-.18;cabinet.add(deck);
 const walnut=new THREE.MeshStandardMaterial({map:woodTexture,color:0x573722,roughness:.65}),brass=new THREE.MeshStandardMaterial({color:0xb88a45,metalness:.72,roughness:.38,side:THREE.DoubleSide});
 box(deck,[1.45,.65,1.15],[0,.33,0],walnut);for(const [w,h,d,y]of [[1.62,.09,1.28,.02],[1.55,.08,1.22,.12],[1.57,.08,1.25,.68]])box(deck,[w,h,d],[0,y,0],walnut);for(const x of [-.67,.67])for(const z of [-.52,.52])box(deck,[.07,.54,.07],[x,.37,z],brass);
 box(deck,[.84,.4,.025],[.18,.36,.59],brass);for(let i=0;i<5;i++){const knob=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,.035,12),metal);knob.rotation.x=Math.PI/2;knob.position.set(-.12+i*.14,.3,.62);deck.add(knob);}box(deck,[.55,.05,.02],[.18,.48,.61],dark);
 const speaker=new THREE.Mesh(new THREE.CircleGeometry(.24,32),dark);speaker.position.set(-.47,.37,.604);deck.add(speaker);for(let i=0;i<8;i++){const petal=new THREE.Mesh(new THREE.TorusGeometry(.09,.012,4,16,Math.PI*1.5),brass);petal.position.set(-.47+Math.cos(i*Math.PI/4)*.12,.37+Math.sin(i*Math.PI/4)*.12,.616);petal.rotation.z=i*Math.PI/4;deck.add(petal);}const grille=new THREE.Mesh(new THREE.TorusGeometry(.25,.018,6,32),brass);grille.position.set(-.47,.37,.615);deck.add(grille);
 record=new THREE.Group();record.position.set(0,.75,0);deck.add(record);const vinyl=new THREE.Mesh(new THREE.CylinderGeometry(.48,.48,.025,48),new THREE.MeshStandardMaterial({color:0x101316,roughness:.42,metalness:.15}));record.add(vinyl);for(let r=.15;r<.47;r+=.035){const groove=new THREE.Mesh(new THREE.TorusGeometry(r,.003,3,48),metal);groove.rotation.x=Math.PI/2;groove.position.y=.015;record.add(groove);}const label=new THREE.Mesh(new THREE.CylinderGeometry(.12,.12,.03,24),brass);label.position.y=.01;record.add(label);box(record,[.03,.004,.07],[.04,.028,0],sun);
 const tube=points=>new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p))),24,.045,8,false),brass);deck.add(tube([[-.56,.74,-.3],[-.58,1.02,-.3],[-.45,1.25,-.3],[-.2,1.4,-.27]]));deck.add(tube([[-.56,.84,-.3],[-.45,.88,.12],[.12,.83,.28]]));const needle=new THREE.Mesh(new THREE.SphereGeometry(.09,12,8),metal);needle.position.set(.12,.81,.28);deck.add(needle);
 const hornGeometry=new THREE.LatheGeometry([new THREE.Vector2(.055,0),new THREE.Vector2(.08,.18),new THREE.Vector2(.16,.37),new THREE.Vector2(.34,.58),new THREE.Vector2(.59,.76),new THREE.Vector2(.7,.84)],64);const hp=hornGeometry.attributes.position;for(let i=0;i<hp.count;i++){const y=hp.getY(i),theta=Math.atan2(hp.getZ(i),hp.getX(i)),petal=1+.095*Math.cos(theta*10)*Math.pow(y/.84,3);hp.setXYZ(i,hp.getX(i)*petal,y+.055*Math.cos(theta*10)*Math.pow(y/.84,4),hp.getZ(i)*petal);}hornGeometry.computeVertexNormals();const horn=new THREE.Mesh(hornGeometry,brass);horn.position.set(-.2,1.4,-.27);horn.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(.2,.65,.73).normalize());deck.add(horn);
 const rimPoints=[];for(let i=0;i<=100;i++){const t=i/100*Math.PI*2,r=.7*(1+.095*Math.cos(t*10));rimPoints.push(new THREE.Vector3(Math.cos(t)*r,.84+.055*Math.cos(t*10),Math.sin(t)*r));}horn.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(rimPoints),100,.012,5,false),brass));const deckLight=new THREE.PointLight(0xffd39b,1.8,2.5,2);deckLight.position.set(0,1.8,.8);deck.add(deckLight);
 // Pegboard and hand tools directly behind the assembly table.
 const toolWall=new THREE.Group();toolWall.position.z=4.55;cabinet.add(toolWall);box(toolWall,[3.2,1.45,.09],[0,2.9,-5.72],wood);for(let x=-1.4;x<1.5;x+=.23)for(let y=2.35;y<3.5;y+=.23)box(toolWall,[.025,.025,.012],[x,y,-5.66],dark);
 const deskLamp=new THREE.Group();deskLamp.position.set(1.85,2.1,-.3);cabinet.add(deskLamp);const foot=new THREE.Mesh(new THREE.CylinderGeometry(.23,.28,.06,20),metal);deskLamp.add(foot);const lampArm=tube([[0,0,0],[0,.55,0],[-.28,.95,.05],[-.48,1.02,.12]]);deskLamp.add(lampArm);const shade=new THREE.Mesh(new THREE.ConeGeometry(.27,.3,24,1,true),metal);shade.position.set(-.48,.94,.12);deskLamp.add(shade);const bulb=new THREE.Mesh(new THREE.CircleGeometry(.23,24),sun);bulb.rotation.x=-Math.PI/2;bulb.position.set(-.48,.79,.12);deskLamp.add(bulb);const deskLight=new THREE.PointLight(0xffd8a6,18,3.5,2);deskLight.position.set(-.48,.76,.12);deskLamp.add(deskLight);
 const plan=document.createElement('canvas');plan.width=512;plan.height=384;const ink=plan.getContext('2d');ink.fillStyle='#16415b';ink.fillRect(0,0,512,384);ink.strokeStyle='#86c3d0';ink.lineWidth=2;for(let x=0;x<512;x+=24){ink.beginPath();ink.moveTo(x,0);ink.lineTo(x,384);ink.stroke();}for(let y=0;y<384;y+=24){ink.beginPath();ink.moveTo(0,y);ink.lineTo(512,y);ink.stroke();}ink.lineWidth=4;ink.strokeRect(210,110,92,110);ink.beginPath();ink.arc(256,72,30,0,Math.PI*2);ink.stroke();for(const side of [-1,1]){ink.strokeRect(256+side*90-12,125,24,100);ink.strokeRect(256+side*28-12,235,24,112);}ink.fillStyle='#c3e5e7';ink.font='18px monospace';ink.fillText('FRAME / ASSEMBLY 07',20,30);const blueprintTexture=new THREE.CanvasTexture(plan);blueprintTexture.colorSpace=THREE.SRGBColorSpace;const paper=new THREE.MeshStandardMaterial({map:blueprintTexture,roughness:1});for(let i=0;i<3;i++){const sheet=box(cabinet,[1.05,.006,.75],[.2+i*.45,2.06,.2-i*.25],paper);sheet.rotation.y=i*.6-.3;}
 for(let i=0;i<13;i++){const tool=new THREE.Group();tool.position.set(-.35+(i%5)*.45,2.09,-.4+(i%3)*.3);tool.rotation.y=i*2.4;cabinet.add(tool);box(tool,[.08,.05,.35],[0,0,0],i%2?metal:wood);box(tool,[.22,.07,.1],[0,0,.2],metal);if(i%3===0)box(tool,[.07,.12,.07],[0,.08,-.18],dark);}
 const workLight=new THREE.PointLight(0xffd2a1,13,4,2);workLight.position.set(0,3.7,.9);cabinet.add(workLight);
 for(const side of [-1,1])for(let i=0;i<9;i++){const bone=['Head','upperarm_l','calf_r','thigh_l','spine_03'][i%5];spare(bone,root,[side*(2.1+(i%3)*.75),.25+(i%2)*.16,-3.5-Math.floor(i/3)*.55],[Math.PI/2,i*1.7,i*.4]);}

 disposeRobot(donor);
 const wornMetal=workshopMetal();addWorkshopDetails(root,box,wornMetal,wood,dark,sun);refineWorkshop(root,box,wornMetal,wood,dark);
 for(let i=0;i<4;i++){box(cabinet,[.85,.36,.95],[-1.5+i, .24,.1],wornMetal);for(let n=0;n<3;n++){box(cabinet,[.84,.03,.98],[-1.5+i,.28+n*.12,.1],metal);box(cabinet,[.22,.025,.04],[-1.5+i,.33+n*.12,.61],metal);}}
 root.position.z=-2;root.scale.set(1.05,1.1,1.05);
 return {root,update(dt){time+=dt;if(record)record.rotation.y-=dt*Math.PI*2*33.333/60;if(fan){fan.rotation.z-=dt*.38;if(ventBeam)ventBeam.material.uniforms.rotation.value=fan.rotation.z;}for(const field of dustFields){field.origins.forEach((p,i)=>{const z=(p.z+time*p.speed)%2.8+.22;field.data[i*3]=p.x-z*.2+Math.sin(time*.35+p.phase)*.08;field.data[i*3+1]=p.y-z*.35+Math.sin(time*.5+p.phase)*.07;field.data[i*3+2]=z;});field.geometry.attributes.position.needsUpdate=true;}},dispose(){plasterTexture.dispose();woodTexture.dispose();blueprintTexture.dispose();wornMetal.map.dispose();}};
}
