import {FPS,frameTime,frameAt,totalFrames,normalizeFrameClip,resizeFrameClip} from './motion-frame-timeline.js';
import * as THREE from 'three';
import {bindNumberDrag,createPartMap} from './motion-editor-controls.js';
import {plantFeet,footAnchors,connectedEdit,editReference} from './motion-pose-tools.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {createRobot} from './robot.js';
import {createThirdPersonView} from './third-person.js';
import {weapons,actions,actionList,actionState,capturePose,applyPose,samplePose,readProject,saveProject,validateProject} from './motion-settings.js';
const $=id=>document.getElementById(id),viewport=$('viewport');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));viewport.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#18232f');scene.add(new THREE.HemisphereLight(0xe9f6ff,0x61707e,2.5));const light=new THREE.DirectionalLight(0xffead6,3);light.position.set(-3,6,-4);scene.add(light);scene.add(new THREE.GridHelper(14,28,0x577383,0x314454));
const camera=new THREE.PerspectiveCamera(43,1,.02,100);camera.position.set(-3,2.2,-4);const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1,0);orbit.enableDamping=true;orbit.update();
const avatar=createRobot();scene.add(avatar.root);const view=createThirdPersonView(avatar,Object.keys(weapons));for(const [type,model]of Object.entries(view.models))model.userData.editorWeapon=type;const skeleton=new THREE.SkeletonHelper(avatar.motion);skeleton.visible=false;scene.add(skeleton);
const weaponHandle=new THREE.Object3D();avatar.motion.add(weaponHandle);
const transform=new TransformControls(camera,renderer.domElement);transform.setMode('rotate');transform.setSpace('local');scene.add(transform.getHelper());
const partNames={pelvis:'골반',spine_01:'허리',spine_02:'몸통',spine_03:'가슴',neck_01:'목',Head:'머리',clavicle_l:'왼쪽 어깨',upperarm_l:'왼쪽 위팔',lowerarm_l:'왼쪽 아래팔',hand_l:'왼손',clavicle_r:'오른쪽 어깨',upperarm_r:'오른쪽 위팔',lowerarm_r:'오른쪽 아래팔',hand_r:'오른손',thigh_l:'왼쪽 허벅지',calf_l:'왼쪽 종아리',foot_l:'왼발',thigh_r:'오른쪽 허벅지',calf_r:'오른쪽 종아리',foot_r:'오른발',$weapon:'무기'};
let project=readProject();for(const [k,c]of Object.entries(project.clips))project.clips[k]=normalizeFrameClip(c);
let weapon='knife',action='knife',time=0,frameIndex=0,playing=false,dirty=false,dragging=false,undo=[],redo=[],editStart=null,numberDrag=false;
const fields={};for(const [prop,label]of [['p','위치'],['r','회전'],['s','크기']]){const row=document.createElement('div');row.className='fieldRow';const title=document.createElement('span');title.textContent=label;row.append(title);fields[prop]=[];for(const [i,axis]of ['X','Y','Z'].entries()){const labelEl=document.createElement('label');labelEl.textContent=axis;const input=document.createElement('input');input.type='number';input.step=prop==='r'?'1':'.01';input.setAttribute('aria-label',`${label} ${axis}`);labelEl.append(input);row.append(labelEl);fields[prop].push(input);input.addEventListener('input',()=>editTransform(prop,i,input));input.addEventListener('change',()=>editTransform(prop,i,input));}$('fields').append(row);}
for(const [id,label]of Object.entries(weapons))$('weapon').add(new Option(label,id));$('weapon').value=weapon;for(const [id,label]of Object.entries(partNames))$('part').add(new Option(label,id));$('part').value='spine_03';
const length=()=>totalFrames(clip(),actions[action].duration);
const key=()=>weapon+':'+action,clip=()=>project.clips[key()],selected=()=>clip()?.frames[frameIndex],object=()=> $('part').value==='$weapon'&&$('connected').checked?weaponHandle:$('part').value==='$weapon'?view.models[weapon]:avatar.bones.find(b=>b.name===$('part').value);
const highlightPart=createPartMap($('partMap'),id=>{$('part').value=id;$('part').onchange();});
function syncWeaponHandle(){const model=view.models[weapon];model.updateWorldMatrix(true,false);weaponHandle.position.copy(avatar.motion.worldToLocal(model.getWorldPosition(new THREE.Vector3())));weaponHandle.quaternion.copy(avatar.motion.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(model.getWorldQuaternion(new THREE.Quaternion())));weaponHandle.scale.copy(model.getWorldScale(new THREE.Vector3()).divide(avatar.motion.getWorldScale(new THREE.Vector3())));weaponHandle.updateWorldMatrix(true,false);}
function commitEdit(reference){object().scale.clampScalar(.01,10);object().updateWorldMatrix(true,true);connectedEdit(avatar,view.models[weapon],$('part').value,reference,{ground:$('footLock').checked&&!['jump','roll'].includes(action),follow:$('connected').checked,control:object()});selected().pose=capturePose(avatar,view.models[weapon]);syncWeaponHandle();mark();}
function status(message){$('status').textContent=message;}
function mark(){dirty=true;$('save').textContent='저장 · 게임 적용'+' *';}
function checkpoint(){undo.push(JSON.stringify(project));if(undo.length>50)undo.shift();redo=[];}
function baseline(t){const s=actionState(weapon,action,t/actions[action].duration);for(let i=0;i<2;i++)view.pose(s);return capturePose(avatar,view.models[weapon]);}
function ensureEditableFrame(){
 playing=false;
 let c=clip();const total=length(),n=frameAt(time,total),t=frameTime(n);
 if(!c){
  checkpoint();const indices=new Set([1,total,n]);const step=Math.max(1,Math.ceil(total/117));for(let f=1;f<=total;f+=step)indices.add(f);
  const frames=[...indices].sort((a,b)=>a-b).map(f=>({t:frameTime(f),easing:'smooth',pose:baseline(frameTime(f)/ (total/FPS)*actions[action].duration)}));
  c=project.clips[key()]={fps:FPS,totalFrames:total,duration:total/FPS,loop:!!actions[action].loop,enabled:true,followAim:true,footLock:$('footLock').checked,frames};mark();
 }
 let index=c.frames.findIndex(f=>Math.abs(f.t-t)<.001);
 if(index<0){
  if(c.frames.length>=120){status('키프레임은 최대 120개입니다. 기존 키를 선택하거나 삭제해주세요.');return false;}
  checkpoint();time=t;drawPose();c.frames.push({t,easing:'smooth',pose:capturePose(avatar,view.models[weapon])});c.frames.sort((a,b)=>a.t-b.t);index=c.frames.findIndex(f=>Math.abs(f.t-t)<.001);mark();
 }
 frameIndex=index;time=t;return true;
}
function drawPose(){const c=clip(),duration=c?.duration||actions[action].duration;const phase=time/duration;baseline(phase*actions[action].duration);if(c)applyPose(avatar,view.models[weapon],samplePose({...c,loop:false},time));
 if(c?.footLock&& !['jump','roll'].includes(action))plantFeet(avatar);
 syncWeaponHandle();
 if($('travel').checked&&action==='knife')avatar.root.position.z=-Math.min(1,Math.max(0,(phase-.12)/.43))*1.6;
 avatar.root.updateMatrixWorld(true);
 if(weapon==='bow'&&['draw','hold'].includes(action)){const model=view.models.bow,pull=model.worldToLocal(avatar.arms[1].hand.getWorldPosition(new THREE.Vector3())),pos=model.userData.string.geometry.attributes.position;pos.setXYZ(1,pull.x,pull.y,pull.z);pos.needsUpdate=true;model.userData.string.geometry.computeBoundingSphere();model.userData.nockedArrow.position.copy(pull).sub(new THREE.Vector3(0,0,.14));model.userData.nockedArrow.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),new THREE.Vector3(0,0,-.43).sub(pull).normalize());}
 skeleton.updateMatrixWorld(true);$('scrub').max=length();$('scrub').value=frameAt(time,length());$('currentFrame').max=length();$('currentFrame').value=frameAt(time,length());$('timeLabel').textContent=length()+'F · '+(length()/FPS).toFixed(2)+'초';for(const b of $('frames').children)b.classList.toggle('selected',Number(b.dataset.frame)===frameAt(time,length()));if($('timelineCursor'))$('timelineCursor').style.left=(Math.min(100,time/frameTime(length())*100))+'%';
 const editable=!!c&&!playing&&Math.abs(time-selected().t)<.002;transform.visible=editable;transform.enabled=editable;if(editable)transform.attach(object());else transform.detach();
}
function refreshFields(){const o=object();if(!o)return;const values={p:o.position.toArray(),r:[o.rotation.x,o.rotation.y,o.rotation.z].map(THREE.MathUtils.radToDeg),s:o.scale.toArray()};for(const prop of Object.keys(fields))fields[prop].forEach((input,i)=>{if(document.activeElement!==input)input.value=values[prop][i].toFixed(prop==='r'?1:3);input.disabled=playing;});}
function selectFrame(i){const c=clip();if(!c)return;playing=false;frameIndex=Math.max(0,Math.min(c.frames.length-1,i));time=selected().t;refresh();}
function drawTimeline(){const c=clip(),track=$('keyTimeline');track.replaceChildren();if(!c)return;for(const [i,f]of c.frames.entries()){const marker=document.createElement('button');marker.className='keyMarker';marker.style.left=(f.t/frameTime(length())*100)+'%';marker.textContent='◆';marker.title=frameAt(f.t,length())+'프레임';marker.setAttribute('aria-label',frameAt(f.t,length())+'프레임 키로 이동');marker.classList.toggle('selected',i===frameIndex);marker.onclick=()=>selectFrame(i);track.append(marker);}const cursor=document.createElement('i');cursor.id='timelineCursor';cursor.style.left=(Math.min(100,time/frameTime(length())*100))+'%';track.append(cursor);}
$('prevFrame').onclick=()=>selectFrame(frameIndex-1);$('nextFrame').onclick=()=>selectFrame(frameIndex+1);
$('keyTimeline').ondblclick=e=>{if(!clip()||e.target.closest('button'))return;const rect=$('keyTimeline').getBoundingClientRect();time=frameTime(frameAt((e.clientX-rect.left)/rect.width*frameTime(length()),length()));insertFrame();};
function refresh(){const c=clip(),f=selected(),onKey=!!f&&Math.abs(time-f.t)<.001;$('frameCount').value=length();$('loop').checked=c?.loop??!!actions[action].loop;$('enabled').checked=c?.enabled??true;$('followAim').checked=c?.followAim??true;$('footLock').checked=c?!!c.footLock:!['jump','roll','move'].includes(action);highlightPart($('part').value);$('partLabel').textContent=partNames[$('part').value];$('clipStatus').textContent=c?'편집 모션 · '+c.frames.length+' 키프레임':'기본 모션 · 프레임을 만들면 편집할 수 있습니다.';$('frames').replaceChildren();for(let n=1;n<=length();n++){const index=c?.frames.findIndex(f=>frameAt(f.t,length())===n)??-1,button=document.createElement('button');button.dataset.frame=n;button.textContent=String(n);button.classList.toggle('hasKey',index>=0);button.classList.toggle('selected',n===frameAt(time,length()));button.title=n+'프레임'+(index>=0?' · 키프레임':'');button.setAttribute('aria-label',n+'프레임으로 이동');button.onclick=()=>seekFrame(n);$('frames').append(button);}
 const cell=[...$('frames').children].find(b=>Number(b.dataset.frame)===frameAt(time,length()));if(cell){const left=cell.offsetLeft-$('frames').offsetLeft;if(left<$('frames').scrollLeft)$('frames').scrollLeft=left;else if(left+cell.offsetWidth>$('frames').scrollLeft+$('frames').clientWidth)$('frames').scrollLeft=left+cell.offsetWidth-$('frames').clientWidth;}
 drawTimeline();
 for(const id of ['addFrame','copyFrame','deleteFrame','frameTime','easing','resetFrame','loop','enabled','followAim','resetClip'])$(id).disabled=!c;
 $('frameTime').max=length();$('frameTime').value=onKey?frameAt(f.t,length()):frameAt(time,length());$('easing').value=f?.easing||'smooth';$('frameTime').disabled=!onKey||frameIndex===0||frameIndex===c?.frames.length-1;$('copyFrame').disabled=!onKey;$('resetFrame').disabled=!onKey;$('easing').disabled=!onKey;$('deleteFrame').disabled=!onKey||!c||c.frames.length<=2||frameIndex===0||frameIndex===c.frames.length-1;$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;$('play').textContent=playing?'❚❚ 정지':'▶ 재생';drawPose();refreshFields();}
function chooseAction(){const list=actionList(weapon);if(!list.includes(action))action='idle';$('action').replaceChildren();for(const id of list)$('action').add(new Option(actions[id].name,id));$('action').value=action;time=0;frameIndex=0;playing=false;refresh();}
$('weapon').onchange=()=>{weapon=$('weapon').value;chooseAction();};$('action').onchange=()=>{action=$('action').value;chooseAction();};
$('generate').onclick=()=>{const total=Number($('frameCount').value);if(!Number.isInteger(total)||total<3||total>900)return status('총 길이는 3~900프레임입니다.');if(clip()&&!confirm('현재 편집 동작을 기본 모션에서 다시 만드시겠습니까?'))return;checkpoint();project.clips[key()]={fps:FPS,totalFrames:total,duration:total/FPS,loop:!!actions[action].loop,enabled:true,followAim:true,footLock:$('footLock').checked,frames:[{t:0,easing:'smooth',pose:baseline(0)},{t:frameTime(total),easing:'smooth',pose:baseline(actions[action].duration)}]};frameIndex=0;time=0;playing=false;mark();refresh();status('첫·마지막 키만 만들었습니다. 원하는 프레임에 전체 자세를 저장해주세요.');};
$('frameCount').onchange=()=>{const total=Number($('frameCount').value);if(!Number.isInteger(total)||total<3||total>900){status('총 길이는 3~900프레임입니다.');refresh();return;}if(!clip())return;checkpoint();project.clips[key()]=resizeFrameClip(clip(),total);time=frameTime(Math.min(total,frameAt(time,total)));frameIndex=Math.min(frameIndex,clip().frames.length-1);mark();refresh();};
for(const id of ['loop','enabled','followAim'])$(id).onchange=()=>{if(!clip())return;checkpoint();clip()[id]=$(id).checked;mark();refresh();};
$('easing').onchange=()=>{if(!selected())return;checkpoint();selected().easing=$('easing').value;mark();refresh();};
$('frameTime').onchange=()=>{const c=clip(),n=Number($('frameTime').value),t=frameTime(n);if(!c||frameIndex===0||frameIndex===c.frames.length-1)return;if(!Number.isInteger(n)||n<1||n>length()||c.frames.some((f,i)=>i!==frameIndex&&Math.abs(f.t-t)<.001)){status('비어 있는 프레임 번호를 지정해주세요.');refresh();return;}checkpoint();const f=selected();f.t=t;c.frames.sort((a,b)=>a.t-b.t);frameIndex=c.frames.indexOf(f);time=t;mark();refresh();};
function insertFrame(copy=false){const c=clip();if(!c)return;let n=frameAt(time,length());if(copy){n=frameAt(selected().t,length())+1;while(n<=length()&&c.frames.some(f=>frameAt(f.t,length())===n))n++;}if(n>length())return status('뒤에 비어 있는 프레임이 없습니다.');const t=frameTime(n),existing=c.frames.findIndex(f=>Math.abs(f.t-t)<.001);if(existing>=0){selectFrame(existing);return status('이미 키가 있는 프레임입니다. 자세를 바로 수정해주세요.');}if(c.frames.length>=120)return status('키프레임은 최대 120개입니다.');checkpoint();time=t;drawPose();const pose=copy?structuredClone(selected().pose):capturePose(avatar,view.models[weapon]);c.frames.push({t,easing:'smooth',pose});c.frames.sort((a,b)=>a.t-b.t);frameIndex=c.frames.findIndex(f=>f.t===t);time=t;playing=false;mark();refresh();status(n+'프레임에 전체 파트의 키 자세를 저장했습니다.');}
$('addFrame').onclick=()=>insertFrame();$('copyFrame').onclick=()=>insertFrame(true);$('deleteFrame').onclick=()=>{const c=clip();if(!c||frameIndex===0||frameIndex===c.frames.length-1)return;checkpoint();c.frames.splice(frameIndex,1);frameIndex=Math.min(frameIndex,c.frames.length-1);time=selected().t;mark();refresh();};
function editTransform(prop,index,input){if(input.value.trim()==='')return;const value=Number(input.value);if(!Number.isFinite(value)||Math.abs(value)>999||(prop==='s'&&(value<.01||value>10))){status('올바른 숫자를 입력해주세요. 크기는 0.01~10입니다.');refreshFields();return;}if(!ensureEditableFrame())return;drawPose();const o=object(),current=prop==='r'?THREE.MathUtils.radToDeg(o.rotation[['x','y','z'][index]]):o[prop==='p'?'position':'scale'].getComponent(index);if(Math.abs(current-value)<.000001)return;const reference=editReference(avatar,view.models[weapon],o);if(!numberDrag)checkpoint();if(prop==='r')o.rotation[['x','y','z'][index]]=THREE.MathUtils.degToRad(value);else o[prop==='p'?'position':'scale'].setComponent(index,value);commitEdit(reference);refresh();}
$('part').onchange=()=>{ensureEditableFrame();refresh();};
for(const button of document.querySelectorAll('[data-mode]'))button.onclick=()=>{transform.setMode(button.dataset.mode);for(const b of document.querySelectorAll('[data-mode]'))b.classList.toggle('selected',b===button);};
$('local').onchange=()=>transform.setSpace($('local').checked?'local':'world');
transform.addEventListener('dragging-changed',e=>{dragging=e.value;orbit.enabled=!e.value;if(e.value&&selected()){playing=false;time=selected().t;drawPose();checkpoint();editStart=editReference(avatar,view.models[weapon],object());}else{editStart=null;refresh();}});
transform.addEventListener('objectChange',()=>{if(!dragging||!selected())return;if(editStart)commitEdit(editStart);refreshFields();});
let pointerStart;renderer.domElement.addEventListener('pointerdown',e=>{pointerStart=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(dragging||transform.axis||!pointerStart||Math.hypot(e.clientX-pointerStart[0],e.clientY-pointerStart[1])>4)return;const rect=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);for(const hit of ray.intersectObject(avatar.root,true)){let o=hit.object;while(o&&o!==avatar.root){if(o===view.models[weapon]){$('part').value='$weapon';$('part').onchange();return;}if(o.isBone&&partNames[o.name]){$('part').value=o.name;$('part').onchange();return;}o=o.parent;}}});
function seekFrame(n){playing=false;time=frameTime(Math.max(1,Math.min(length(),Math.round(n))));const index=clip()?.frames.findIndex(f=>Math.abs(f.t-time)<.001)??-1;if(index>=0)frameIndex=index;refresh();status(index>=0?'전체 파트의 키 자세를 편집합니다.':'중간 프레임입니다. 현재 프레임에 키 저장을 눌러 편집해주세요.');}
$('scrub').oninput=()=>seekFrame(Number($('scrub').value));$('currentFrame').onchange=()=>seekFrame(Number($('currentFrame').value)||1);
$('play').onclick=()=>{playing=!playing;if(playing&&time>=(clip()?.duration||actions[action].duration))time=0;refresh();};
addEventListener('keydown',e=>{if(e.code!=='Space'||e.repeat||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;e.preventDefault();$('play').onclick();});
$('resetFrame').onclick=()=>{if(!selected())return;checkpoint();selected().pose=baseline(selected().t/clip().duration*actions[action].duration);mark();refresh();};
$('resetClip').onclick=()=>{if(!clip()||!confirm('이 동작의 편집 모션을 지우고 기본 모션으로 복구하시겠습니까? 저장하면 게임에도 반영됩니다.'))return;checkpoint();delete project.clips[key()];frameIndex=0;time=0;playing=false;mark();refresh();};
function history(from,to){if(!from.length)return;to.push(JSON.stringify(project));project=JSON.parse(from.pop());frameIndex=Math.min(frameIndex,(clip()?.frames.length||1)-1);time=Math.min(time,clip()?.duration||actions[action].duration);mark();refresh();}
$('undo').onclick=()=>history(undo,redo);$('redo').onclick=()=>history(redo,undo);
$('save').onclick=()=>{try{project=saveProject(project);dirty=false;$('save').textContent='저장 · 게임 적용';status('저장했습니다. 같은 주소로 열린 게임의 3인칭 동작에 바로 적용됩니다.');}catch(e){status('저장 실패: '+e.message);}};
$('export').onclick=()=>{try{const json=JSON.stringify(validateProject(project),null,2),url=URL.createObjectURL(new Blob([json],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='last-spark-motions.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('모션 파일을 내보냈습니다.');}catch(e){status(e.message);}};
$('import').onchange=async()=>{const file=$('import').files[0];if(!file)return;try{if(file.size>8e6)throw Error('8MB 이하 파일을 사용해주세요.');const imported=validateProject(JSON.parse(await file.text()));checkpoint();project=imported;for(const [k,c]of Object.entries(project.clips))project.clips[k]=normalizeFrameClip(c);mark();chooseAction();status('파일을 불러왔습니다. 저장 · 게임 적용을 누르면 반영됩니다.');}catch(e){status('불러오기 실패: '+e.message);}$('import').value='';};
$('footLock').onchange=()=>{if(clip()){checkpoint();clip().footLock=$('footLock').checked;mark();refresh();}};$('connected').onchange=()=>{drawPose();refreshFields();};
$('skeleton').onchange=()=>skeleton.visible=$('skeleton').checked;$('travel').onchange=()=>{drawPose();refreshFields();};
for(const button of document.querySelectorAll('[data-view]'))button.onclick=()=>{const positions={front:[0,1.6,-4.7],side:[4.7,1.6,0],back:[0,1.6,4.7],reset:[-3,2.2,-4]};camera.position.fromArray(positions[button.dataset.view]);orbit.target.set(0,1,0);orbit.update();};
addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
for(const [prop,inputs]of Object.entries(fields))for(const [i,input]of inputs.entries())bindNumberDrag(input,{step:prop==='r'?.4:.003,begin:()=>{checkpoint();numberDrag=true;},change:()=>editTransform(prop,i,input),end:()=>{numberDrag=false;refresh();}});
const resize=new ResizeObserver(()=>{const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();});resize.observe(viewport);
let last=performance.now();function render(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(playing){const duration=clip()?.duration||actions[action].duration;time+=dt;if(time>=duration){if(clip()?.loop??actions[action].loop)time%=duration;else{time=duration;playing=false;refresh();}}drawPose();}orbit.update();renderer.render(scene,camera);requestAnimationFrame(render);}chooseAction();requestAnimationFrame(render);
