import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {createRobot} from './robot.js';
import {createThirdPersonView} from './third-person.js';
import {weapons,actions,actionList,actionState,capturePose,applyPose,samplePose,readProject,saveProject,validateProject} from './motion-settings.js';
const $=id=>document.getElementById(id),viewport=$('viewport');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));viewport.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#18232f');scene.add(new THREE.HemisphereLight(0xe9f6ff,0x61707e,2.5));const light=new THREE.DirectionalLight(0xffead6,3);light.position.set(-3,6,-4);scene.add(light);scene.add(new THREE.GridHelper(14,28,0x577383,0x314454));
const camera=new THREE.PerspectiveCamera(43,1,.02,100);camera.position.set(-3,2.2,-4);const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1,0);orbit.enableDamping=true;orbit.update();
const avatar=createRobot();scene.add(avatar.root);const view=createThirdPersonView(avatar,Object.keys(weapons));const skeleton=new THREE.SkeletonHelper(avatar.motion);skeleton.visible=false;scene.add(skeleton);
const transform=new TransformControls(camera,renderer.domElement);transform.setMode('rotate');transform.setSpace('local');scene.add(transform.getHelper());
const partNames={pelvis:'골반',spine_01:'허리',spine_02:'몸통',spine_03:'가슴',neck_01:'목',Head:'머리',clavicle_l:'왼쪽 어깨',upperarm_l:'왼쪽 위팔',lowerarm_l:'왼쪽 아래팔',hand_l:'왼손',clavicle_r:'오른쪽 어깨',upperarm_r:'오른쪽 위팔',lowerarm_r:'오른쪽 아래팔',hand_r:'오른손',thigh_l:'왼쪽 허벅지',calf_l:'왼쪽 종아리',foot_l:'왼발',thigh_r:'오른쪽 허벅지',calf_r:'오른쪽 종아리',foot_r:'오른발',$weapon:'무기'};
let project=readProject(),weapon='knife',action='knife',time=0,frameIndex=0,playing=false,dirty=false,dragging=false,undo=[],redo=[];
const fields={};for(const [prop,label]of [['p','위치'],['r','회전'],['s','크기']]){const row=document.createElement('div');row.className='fieldRow';const title=document.createElement('span');title.textContent=label;row.append(title);fields[prop]=[];for(const [i,axis]of ['X','Y','Z'].entries()){const labelEl=document.createElement('label');labelEl.textContent=axis;const input=document.createElement('input');input.type='number';input.step=prop==='r'?'1':'.01';input.setAttribute('aria-label',`${label} ${axis}`);labelEl.append(input);row.append(labelEl);fields[prop].push(input);input.addEventListener('input',()=>editTransform(prop,i,input));input.addEventListener('change',()=>editTransform(prop,i,input));}$('fields').append(row);}
for(const [id,label]of Object.entries(weapons))$('weapon').add(new Option(label,id));$('weapon').value=weapon;for(const [id,label]of Object.entries(partNames))$('part').add(new Option(label,id));$('part').value='spine_03';
const key=()=>weapon+':'+action,clip=()=>project.clips[key()],selected=()=>clip()?.frames[frameIndex],object=()=> $('part').value==='$weapon'?view.models[weapon]:avatar.bones.find(b=>b.name===$('part').value);
function status(message){$('status').textContent=message;}
function mark(){dirty=true;$('save').textContent='저장 · 게임 적용'+' *';}
function checkpoint(){undo.push(JSON.stringify(project));if(undo.length>50)undo.shift();redo=[];}
function baseline(t){const s=actionState(weapon,action,t/actions[action].duration);for(let i=0;i<2;i++)view.pose(s);return capturePose(avatar,view.models[weapon]);}
function drawPose(){const c=clip(),duration=c?.duration||actions[action].duration;const phase=time/duration;baseline(phase*actions[action].duration);if(c)applyPose(avatar,view.models[weapon],samplePose({...c,loop:false},time));
 if($('travel').checked&&action==='knife')avatar.root.position.z=-Math.min(1,Math.max(0,(phase-.12)/.43))*1.6;
 avatar.root.updateMatrixWorld(true);
 if(weapon==='bow'&&['draw','hold'].includes(action)){const model=view.models.bow,pull=model.worldToLocal(avatar.arms[1].hand.getWorldPosition(new THREE.Vector3())),pos=model.userData.string.geometry.attributes.position;pos.setXYZ(1,pull.x,pull.y,pull.z);pos.needsUpdate=true;model.userData.string.geometry.computeBoundingSphere();model.userData.nockedArrow.position.copy(pull).sub(new THREE.Vector3(0,0,.14));model.userData.nockedArrow.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),new THREE.Vector3(0,0,-.43).sub(pull).normalize());}
 skeleton.updateMatrixWorld(true);$('scrub').max=duration;$('scrub').value=time;$('timeLabel').textContent=time.toFixed(2)+'초';
 const editable=!!c&&!playing&&Math.abs(time-selected().t)<.002;transform.visible=editable;transform.enabled=editable;if(editable)transform.attach(object());else transform.detach();
}
function refreshFields(){const o=object();if(!o)return;const values={p:o.position.toArray(),r:[o.rotation.x,o.rotation.y,o.rotation.z].map(THREE.MathUtils.radToDeg),s:o.scale.toArray()};for(const prop of Object.keys(fields))fields[prop].forEach((input,i)=>{if(document.activeElement!==input)input.value=values[prop][i].toFixed(prop==='r'?1:3);input.disabled=!clip()||playing||Math.abs(time-selected().t)>=.002;});}
function refresh(){const c=clip(),f=selected();$('duration').value=c?.duration||actions[action].duration;$('loop').checked=c?.loop??!!actions[action].loop;$('enabled').checked=c?.enabled??true;$('followAim').checked=c?.followAim??true;$('clipStatus').textContent=c?'편집 모션 · '+c.frames.length+' 키프레임':'기본 모션 · 프레임을 만들면 편집할 수 있습니다.';$('frames').replaceChildren();for(const [i,fr]of (c?.frames||[]).entries()){const button=document.createElement('button');button.textContent=String(i+1);button.title=fr.t.toFixed(2)+'초';button.classList.toggle('selected',i===frameIndex);button.onclick=()=>{playing=false;frameIndex=i;time=fr.t;refresh();};$('frames').append(button);}
 for(const id of ['addFrame','copyFrame','deleteFrame','frameTime','easing','resetFrame','loop','enabled','followAim','resetClip'])$(id).disabled=!c;
 $('frameTime').value=f?.t.toFixed(3)||0;$('easing').value=f?.easing||'smooth';$('frameTime').disabled=!f||frameIndex===0||frameIndex===c?.frames.length-1;$('deleteFrame').disabled=!c||c.frames.length<=2||frameIndex===0||frameIndex===c.frames.length-1;$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;$('play').textContent=playing?'❚❚ 정지':'▶ 재생';drawPose();refreshFields();}
function chooseAction(){const list=actionList(weapon);if(!list.includes(action))action='idle';$('action').replaceChildren();for(const id of list)$('action').add(new Option(actions[id].name,id));$('action').value=action;time=0;frameIndex=0;playing=false;refresh();}
$('weapon').onchange=()=>{weapon=$('weapon').value;chooseAction();};$('action').onchange=()=>{action=$('action').value;chooseAction();};
$('generate').onclick=()=>{const count=Math.round(Number($('frameCount').value)),duration=Number($('duration').value);if(!Number.isFinite(count)||count<2||count>60||duration<.1||duration>30||!Number.isFinite(duration))return status('시간은 0.1~30초, 키프레임은 2~60개로 지정해주세요.');if(clip()&&!confirm('현재 동작의 편집 프레임을 기본 모션에서 다시 만드시겠습니까?'))return;checkpoint();project.clips[key()]={duration,loop:!!actions[action].loop,enabled:true,followAim:true,frames:Array.from({length:count},(_,i)=>({t:duration*i/(count-1),easing:'smooth',pose:baseline(actions[action].duration*i/(count-1))}))};frameIndex=0;time=0;playing=false;mark();refresh();status('프레임을 만들었습니다. 파트를 선택하고 자세를 조절해주세요.');};
$('duration').onchange=()=>{const c=clip(),value=Number($('duration').value);if(!c)return;if(!Number.isFinite(value)||value<.1||value>30){refresh();return;}checkpoint();const ratio=value/c.duration;for(const f of c.frames)f.t*=ratio;c.duration=value;time*=ratio;mark();refresh();};
for(const id of ['loop','enabled','followAim'])$(id).onchange=()=>{if(!clip())return;checkpoint();clip()[id]=$(id).checked;mark();refresh();};
$('easing').onchange=()=>{if(!selected())return;checkpoint();selected().easing=$('easing').value;mark();refresh();};
$('frameTime').onchange=()=>{const c=clip(),t=Number($('frameTime').value);if(!c||frameIndex===0||frameIndex===c.frames.length-1)return;if(!Number.isFinite(t)||t<=c.frames[frameIndex-1].t+.001||t>=c.frames[frameIndex+1].t-.001){status('프레임 시간은 앞뒤 프레임 사이로 지정해주세요.');refresh();return;}checkpoint();selected().t=t;time=t;mark();refresh();};
function insertFrame(copy=false){const c=clip();if(!c)return;let t=time;if(copy){const f=selected(),next=c.frames[frameIndex+1];if(!next)return status('마지막 프레임 대신 그 앞 프레임을 복제해주세요.');t=(f.t+next.t)/2;}if(c.frames.some(f=>Math.abs(f.t-t)<.002))return status('다른 시간으로 이동한 뒤 프레임을 추가해주세요.');if(c.frames.length>=120)return status('키프레임은 최대 120개입니다.');checkpoint();const pose=copy?structuredClone(selected().pose):samplePose({...c,loop:false},t);c.frames.push({t,easing:'smooth',pose});c.frames.sort((a,b)=>a.t-b.t);frameIndex=c.frames.findIndex(f=>f.t===t);time=t;mark();refresh();}
$('addFrame').onclick=()=>insertFrame();$('copyFrame').onclick=()=>insertFrame(true);$('deleteFrame').onclick=()=>{const c=clip();if(!c||frameIndex===0||frameIndex===c.frames.length-1)return;checkpoint();c.frames.splice(frameIndex,1);frameIndex=Math.min(frameIndex,c.frames.length-1);time=selected().t;mark();refresh();};
function editTransform(prop,index,input){if(!selected())return;if(input.value.trim()==='')return;const value=Number(input.value);if(!Number.isFinite(value)||Math.abs(value)>999||(prop==='s'&&(value<.01||value>10))){status('올바른 숫자를 입력해주세요. 크기는 0.01~10입니다.');refreshFields();return;}playing=false;time=selected().t;drawPose();const o=object(),current=prop==='r'?THREE.MathUtils.radToDeg(o.rotation[['x','y','z'][index]]):o[prop==='p'?'position':'scale'].getComponent(index);if(Math.abs(current-value)<.000001)return;checkpoint();if(prop==='r')o.rotation[['x','y','z'][index]]=THREE.MathUtils.degToRad(value);else o[prop==='p'?'position':'scale'].setComponent(index,value);selected().pose[$('part').value]={p:o.position.toArray(),q:o.quaternion.toArray(),s:o.scale.toArray()};mark();refresh();}
$('part').onchange=()=>{playing=false;if(clip())time=selected().t;refresh();};
for(const button of document.querySelectorAll('[data-mode]'))button.onclick=()=>{transform.setMode(button.dataset.mode);for(const b of document.querySelectorAll('[data-mode]'))b.classList.toggle('selected',b===button);};
$('local').onchange=()=>transform.setSpace($('local').checked?'local':'world');
transform.addEventListener('dragging-changed',e=>{dragging=e.value;orbit.enabled=!e.value;if(e.value&&selected()){playing=false;time=selected().t;drawPose();checkpoint();}else refresh();});
transform.addEventListener('objectChange',()=>{if(!dragging||!selected())return;const o=object();selected().pose[$('part').value]={p:o.position.toArray(),q:o.quaternion.toArray(),s:o.scale.toArray()};mark();refreshFields();});
let pointerStart;renderer.domElement.addEventListener('pointerdown',e=>{pointerStart=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(dragging||transform.axis||!pointerStart||Math.hypot(e.clientX-pointerStart[0],e.clientY-pointerStart[1])>4)return;const rect=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);for(const hit of ray.intersectObject(avatar.root,true)){let o=hit.object;while(o&&o!==avatar.root){if(o===view.models[weapon]){$('part').value='$weapon';$('part').onchange();return;}if(o.isBone&&partNames[o.name]){$('part').value=o.name;$('part').onchange();return;}o=o.parent;}}});
$('scrub').oninput=()=>{playing=false;time=Number($('scrub').value);drawPose();refreshFields();$('play').textContent='▶ 재생';status('재생 위치를 이동했습니다.');};
$('play').onclick=()=>{playing=!playing;if(playing&&time>=(clip()?.duration||actions[action].duration))time=0;refresh();};
$('resetFrame').onclick=()=>{if(!selected())return;checkpoint();selected().pose=baseline(selected().t/clip().duration*actions[action].duration);mark();refresh();};
$('resetClip').onclick=()=>{if(!clip()||!confirm('이 동작의 편집 모션을 지우고 기본 모션으로 복구하시겠습니까? 저장하면 게임에도 반영됩니다.'))return;checkpoint();delete project.clips[key()];frameIndex=0;time=0;playing=false;mark();refresh();};
function history(from,to){if(!from.length)return;to.push(JSON.stringify(project));project=JSON.parse(from.pop());frameIndex=Math.min(frameIndex,(clip()?.frames.length||1)-1);time=Math.min(time,clip()?.duration||actions[action].duration);mark();refresh();}
$('undo').onclick=()=>history(undo,redo);$('redo').onclick=()=>history(redo,undo);
$('save').onclick=()=>{try{project=saveProject(project);dirty=false;$('save').textContent='저장 · 게임 적용';status('저장했습니다. 같은 주소로 열린 게임의 3인칭 동작에 바로 적용됩니다.');}catch(e){status('저장 실패: '+e.message);}};
$('export').onclick=()=>{try{const json=JSON.stringify(validateProject(project),null,2),url=URL.createObjectURL(new Blob([json],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='last-spark-motions.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('모션 파일을 내보냈습니다.');}catch(e){status(e.message);}};
$('import').onchange=async()=>{const file=$('import').files[0];if(!file)return;try{if(file.size>8e6)throw Error('8MB 이하 파일을 사용해주세요.');const imported=validateProject(JSON.parse(await file.text()));checkpoint();project=imported;mark();chooseAction();status('파일을 불러왔습니다. 저장 · 게임 적용을 누르면 반영됩니다.');}catch(e){status('불러오기 실패: '+e.message);}$('import').value='';};
$('skeleton').onchange=()=>skeleton.visible=$('skeleton').checked;$('travel').onchange=()=>{drawPose();refreshFields();};
for(const button of document.querySelectorAll('[data-view]'))button.onclick=()=>{const positions={front:[0,1.6,-4.7],side:[4.7,1.6,0],back:[0,1.6,4.7],reset:[-3,2.2,-4]};camera.position.fromArray(positions[button.dataset.view]);orbit.target.set(0,1,0);orbit.update();};
addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
const resize=new ResizeObserver(()=>{const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();});resize.observe(viewport);
let last=performance.now();function render(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(playing){const duration=clip()?.duration||actions[action].duration;time+=dt*Number($('playRate').value);if(time>=duration){if(clip()?.loop??actions[action].loop)time%=duration;else{time=duration;playing=false;refresh();}}drawPose();}orbit.update();renderer.render(scene,camera);requestAnimationFrame(render);}chooseAction();requestAnimationFrame(render);
