import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createPillbug,pillbugDemoPose} from './pillbug-robot.js';
const $=id=>document.getElementById(id),scene=new THREE.Scene();scene.background=new THREE.Color('#172019');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;$('view').append(renderer.domElement);
const camera=new THREE.PerspectiveCamera(42,1,.05,100);camera.position.set(12,9,12);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.5,1.5);controls.enableDamping=true;controls.update();
scene.add(new THREE.HemisphereLight(0xe8f3d4,0x343729,2));const light=new THREE.DirectionalLight(0xffe3b5,3);light.position.set(4,10,5);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-13,right:13,top:13,bottom:-13});scene.add(light);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(45,45),new THREE.MeshStandardMaterial({color:0x344332,roughness:1}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);scene.add(new THREE.GridHelper(30,30,0x52664a,0x3e4d36));
const bug=createPillbug();scene.add(bug.root);
const lane=new THREE.Group();scene.add(lane);const red=new THREE.MeshBasicMaterial({color:0xff202c,transparent:true,opacity:.22,depthWrite:false,side:THREE.DoubleSide});const strip=new THREE.Mesh(new THREE.PlaneGeometry(2.1,11.8),red);strip.rotation.x=-Math.PI/2;strip.position.set(0,.025,2.2);lane.add(strip);
const arrowMaterial=new THREE.MeshBasicMaterial({color:0xff4850,transparent:true,opacity:.9,depthWrite:false,side:THREE.DoubleSide});
for(let z=-2.5;z<7.8;z+=1.5){const shape=new THREE.Shape();shape.moveTo(-.6,-.20);shape.lineTo(0,.4);shape.lineTo(.6,-.2);shape.lineTo(.6,-.48);shape.lineTo(0,.12);shape.lineTo(-.6,-.48);shape.closePath();const arrow=new THREE.Mesh(new THREE.ShapeGeometry(shape),arrowMaterial);arrow.rotation.x=Math.PI/2;arrow.position.set(0,.04,z);lane.add(arrow);}
const target=new THREE.Group();scene.add(target);const targetMat=new THREE.MeshStandardMaterial({color:0x95d59d,transparent:true,opacity:.65,emissive:0x1e4921});const dummy=new THREE.Mesh(new THREE.CapsuleGeometry(.32,.8,5,10),targetMat);dummy.position.y=.72;target.add(dummy);target.position.z=3;
const launchRing=new THREE.Mesh(new THREE.RingGeometry(.8,1,48),new THREE.MeshBasicMaterial({color:0xffd894,transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide}));launchRing.rotation.x=-Math.PI/2;launchRing.position.set(0,.05,-3.7);scene.add(launchRing);
const spinBands=new THREE.Group();scene.add(spinBands);for(const y of [-.22,.22]){const band=new THREE.Mesh(new THREE.TorusGeometry(1.03,.018,4,56,Math.PI*1.45),new THREE.MeshBasicMaterial({color:0xffbf71,transparent:true,opacity:.5,depthWrite:false}));band.position.x=y;band.rotation.y=Math.PI/2;spinBands.add(band);}
const wall=new THREE.Mesh(new THREE.BoxGeometry(4,2.6,.5),new THREE.MeshStandardMaterial({color:0x657063,roughness:.95}));wall.position.set(0,1.3,9);wall.castShadow=wall.receiveShadow=true;scene.add(wall);
let collision='player';$('collision').onchange=()=>{collision=$('collision').value;age=0;hit=false;hp=100;};
let age=0,paused=false,last=0,hit=false,hp=100,notice=0;
$('phase').onchange=()=>{age=Number($('phase').value);hit=pillbugDemoPose(age,collision).impactAge>=0;hp=hit&&collision==='player'?80:100;paused=true;$('pause').textContent='재생';};
$('restart').onclick=()=>{age=0;hit=false;hp=100;notice=0;};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'재생':'일시정지';};
$('shoot').onclick=()=>{const p=pillbugDemoPose(age,collision);$('hit').textContent=p.invulnerable?'튕! 무적 상태입니다. 배를 드러낼 때 공격하세요.':'적중! 드러난 배에 피해를 줬습니다.';notice=1.2;};
function resize(){const r=$('view').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.position.copy(controls.target).add(new THREE.Vector3(camera.aspect<1?5:12,11,15).multiplyScalar(Math.max(1,Math.sqrt(.95/camera.aspect))));camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('view'));resize();
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000||0);last=now;if(!paused)age+=dt*Number($('speed').value);if(age>=10.5){age%=10.5;hit=false;hp=100;}const p=pillbugDemoPose(age,collision);bug.root.position.set(0,p.hop+p.flip*1.02,p.z);bug.root.rotation.z=p.flip*Math.PI;bug.root.scale.y=p.squash;bug.pose(p.curl,p.roll,age*7,p.flail,age<2?1:0);wall.visible=collision==='wall';target.visible=collision==='player';spinBands.visible=age>=2.5&&p.impactAge<0;spinBands.position.copy(bug.root.position).add(new THREE.Vector3(0,1.15,0));spinBands.rotation.x=p.roll;const blast=(age-3.4)/.28;launchRing.visible=blast>=0&&blast<1;launchRing.scale.setScalar(1+Math.max(0,blast)*3);launchRing.material.opacity=Math.max(0,1-blast)*.55;lane.visible=p.warning;red.opacity=.18+.09*Math.sin(age*15);arrowMaterial.opacity=.65+.3*Math.sin(age*12);
if(p.impactAge>=0&&!hit){hit=true;if(collision==='player')hp-=20;notice=1.2;$('hit').textContent=collision==='player'?'퉁! 플레이어 피해 20 · 서로 튕겨납니다.':'퉁! 벽 충돌 · 뒤집혀 배가 드러납니다.';}
const knock=hit?Math.min(1,Math.max(0,p.impactAge/.45)):0;target.position.z=3+knock*2.6;target.position.y=hit?Math.sin(knock*Math.PI)*.6:0;target.rotation.x=knock*.65;targetMat.color.setHex(hit?0xff845b:0x95d59d);
$('status').textContent=p.stage;$('status').style.borderColor=p.invulnerable?'#ff5353':'#71825e';document.body.dataset.stage=p.stage;document.body.dataset.invulnerable=String(p.invulnerable);document.body.dataset.targetHp=String(hp);notice-=dt;if(notice<=0)$('hit').textContent=`플레이어 표적 HP ${hp} · 경로는 예고 이후 고정됩니다.`;controls.update();renderer.render(scene,camera);}requestAnimationFrame(frame);
