import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {loadPurchasedModels} from './purchased-model-library.js';
import {createStreetProps} from './street-props.js';
import {generateBrickBlock,validateBrickBlock,BRICK_STORAGE} from './brick-street-layout.js';
import {buildBrickStreet,disposeBrickStreet} from './brick-street-scene.js';
const $=id=>document.getElementById(id),seed=()=>crypto.getRandomValues(new Uint32Array(1))[0];let library,candidates=[],selected=null,saved=[],history=[],views=[];
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
function status(t){$('status').textContent=t;}function persist(){localStorage.setItem(BRICK_STORAGE,JSON.stringify(saved));}function choose(b){selected=b;$('chosen').textContent=`선택 · SEED ${b.seed} ${b.parentSeed!==null?' / 원본 '+b.parentSeed:''}`;for(const v of views){v.card.classList.toggle('selected',v.block.seed===b.seed);v.button.textContent=v.block.seed===b.seed?'선택됨 ✓':'이 거리 선택';}$('mutate').disabled=$('keep').disabled=$('export').disabled=false;}
function display(blocks){for(const v of views){v.controls.dispose();v.observer.disconnect();disposeBrickStreet(v.root);}views=[];candidates=blocks;selected=null;$('candidates').replaceChildren();$('mutate').disabled=$('keep').disabled=$('export').disabled=true;$('chosen').textContent='후보를 비교하고 하나를 선택하세요.';
 for(const [i,b]of blocks.entries()){const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="view"><span class="badge">CANDIDATE ${i+1} · SEED ${b.seed}</span><canvas aria-label="후보 ${i+1} · 드래그 회전"></canvas></div><div class="info"><div><strong>벽돌 거리 ${i+1}</strong><small>${Math.min(...b.buildings.map(v=>v.floors))}–${Math.max(...b.buildings.map(v=>v.floors))}층 · 전복 차량 ${b.vehicles.filter(v=>v.roll).length}대 · 붕괴 더미 ${b.rubble.length}곳</small></div><button>이 거리 선택</button></div>`;$('candidates').append(card);const canvas=card.querySelector('canvas'),context=canvas.getContext('2d'),scene=new T.Scene();scene.background=new T.Color(0x99a38d);scene.add(new T.HemisphereLight(0xfff3dd,0x647957,2.2));const light=new T.DirectionalLight(0xffedd0,3);light.position.set(-20,45,20);scene.add(light);const root=buildBrickStreet(b,library);scene.add(root);const camera=new T.PerspectiveCamera(42,1,.1,200);camera.position.set(0,38,47);const controls=new OrbitControls(camera,canvas);controls.target.set(0,4,0);controls.minDistance=9;controls.maxDistance=100;controls.maxPolarAngle=Math.PI*.49;controls.update();const v={card,canvas,context,scene,root,camera,controls,block:b,dirty:true,button:card.querySelector('button')};v.button.onclick=()=>choose(b);controls.addEventListener('change',()=>v.dirty=true);v.observer=new ResizeObserver(()=>v.dirty=true);v.observer.observe(canvas);views.push(v);}$('undo').disabled=!history.length;}
function regenerate(parent){if(candidates.length)history.push(candidates);if(history.length>12)history.shift();display(Array.from({length:6},()=>generateBrickBlock(seed(),parent)));status(parent?'선택한 건물 규격과 벽돌 색은 유지하고 파손·차량·잔해·식생을 다시 만들었습니다.':'붉은 벽돌 거리 후보 6개를 만들었습니다.');}
function renderSaved(){$('saved').replaceChildren();$('savedCount').textContent=saved.length;$('play').disabled=!saved.length;for(const b of saved){const card=document.createElement('div');card.className='saved-item';const title=document.createElement('strong');title.textContent=`벽돌 블록 · ${b.seed}`;const vary=document.createElement('button');vary.textContent='여기서 변형';vary.onclick=()=>regenerate(b);const remove=document.createElement('button');remove.textContent='보관 해제';remove.onclick=()=>{saved=saved.filter(v=>v.seed!==b.seed);persist();renderSaved();status('보관을 해제했습니다. 현재 후보와 내보낸 백업은 유지됩니다.');};card.append(title,vary,remove);$('saved').append(card);}}
$('fresh').onclick=()=>regenerate(null);$('mutate').onclick=()=>selected&&regenerate(selected);$('undo').onclick=()=>history.length&&display(history.pop());$('keep').onclick=()=>{if(!selected)return;try{if(!saved.some(b=>b.seed===selected.seed))saved.push(selected);persist();renderSaved();status('완성 블록으로 보관했습니다.');}catch(e){status('저장 실패 · JSON으로 백업해 주세요.');}};
$('play').onclick=()=>{if(saved.length)window.open('./?arena&brickBlocks=1','_blank','noopener');};$('export').onclick=()=>{if(!selected)return;const url=URL.createObjectURL(new Blob([JSON.stringify(selected,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`brick-street-${selected.seed}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>200000)throw Error('파일이 너무 큽니다.');const b=validateBrickBlock(JSON.parse(await f.text()));history.push(candidates);display([b]);choose(b);status('블록을 불러왔습니다. 보관하거나 여기서 변형할 수 있습니다.');}catch(e){status('불러오기 실패 · '+e.message);}e.target.value='';};
function render(){for(const v of views){if(!v.dirty)continue;const w=v.canvas.clientWidth,h=v.canvas.clientHeight;if(!w||!h)continue;renderer.setSize(w,h,false);v.camera.aspect=w/h;v.camera.updateProjectionMatrix();renderer.render(v.scene,v.camera);v.canvas.width=renderer.domElement.width;v.canvas.height=renderer.domElement.height;v.context.drawImage(renderer.domElement,0,0);v.dirty=false;}requestAnimationFrame(render);}render();
document.querySelectorAll('button,input').forEach(b=>b.disabled=true);try{library=await loadPurchasedModels();for(const [id,t]of createStreetProps())library.set(id,t);try{saved=JSON.parse(localStorage.getItem(BRICK_STORAGE)||'[]').map(validateBrickBlock);}catch{saved=[];}document.querySelectorAll('button,input').forEach(b=>b.disabled=false);regenerate(null);renderSaved();}catch(e){status('모델 로딩 실패 · '+e.message);console.error(e);}
