import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {loadPurchasedModels} from './purchased-model-library.js';
import {composeReferenceAssets,referenceAssetInfo} from './reference-buildings.js';
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;const views=[];
try{const library=await loadPurchasedModels(),composed=composeReferenceAssets(library);document.querySelector('.status').remove();for(const [index,info]of referenceAssetInfo.entries()){
 const template=composed.get(info.id),card=document.createElement('article');card.className='card';card.innerHTML=`<div class="viewport"><span class="badge">REFERENCE ${index+1} / ${info.id}</span><canvas tabindex="0" aria-label="${info.name} 드래그 회전"></canvas><button class="reset">시점 초기화</button></div><div class="info"><h2>${info.name}</h2><p>${info.description}</p><p class="source">사용한 구매 부품 · ${template.sources.join(', ')}</p><p class="source">${Math.round(template.parts.reduce((n,p)=>n+p.geometry.attributes.position.count/3,0)).toLocaleString()} 삼각형</p></div><div class="ref-label">참고 사진 ${index+1}</div><img class="reference" src="./references/city-${index+1}.png" alt="${info.name}의 참고 이미지">`;document.querySelector('#gallery').append(card);
 const canvas=card.querySelector('canvas'),ctx=canvas.getContext('2d'),scene=new T.Scene();scene.background=new T.Color(0xdce1d3);scene.add(new T.HemisphereLight(0xffecd3,0x78916c,2.3));const sun=new T.DirectionalLight(0xffe3ba,2.8);sun.position.set(-20,50,35);scene.add(sun);const root=new T.Group();for(const p of template.parts){root.add(new T.Mesh(p.geometry,p.material));}scene.add(root);const size=template.size,center=new T.Vector3(0,size.y*.47,0),radius=template.maxSize,camera=new T.PerspectiveCamera(40,1,.05,500);camera.position.set(radius*1.05,size.y*.8,radius*1.3);const floor=new T.Mesh(new T.CylinderGeometry(Math.max(size.x,size.z)*.68+1,Math.max(size.x,size.z)*.68+1,.2,64),new T.MeshStandardMaterial({color:0xc1c8b5}));floor.position.y=-.12;scene.add(floor);const controls=new OrbitControls(camera,canvas);controls.target.copy(center);controls.minDistance=radius*.45;controls.maxDistance=radius*4;controls.maxPolarAngle=Math.PI*.49;controls.enablePan=false;controls.update();controls.saveState();const v={scene,camera,controls,canvas,ctx,root,dirty:true};views.push(v);controls.addEventListener('change',()=>v.dirty=true);card.querySelector('button').onclick=()=>controls.reset();new ResizeObserver(()=>v.dirty=true).observe(canvas);
 }window.referenceGallery={views,composed};
}catch(e){document.querySelector('.status').textContent='모델 생성 실패 · '+e.message;console.error(e);}
document.getElementById('wire').onchange=e=>{for(const v of views){v.root.traverse(o=>{if(o.isMesh)o.material.wireframe=e.target.checked;});v.dirty=true;}};
function render(){for(const v of views){if(!v.dirty)continue;const w=v.canvas.clientWidth,h=v.canvas.clientHeight;renderer.setSize(w,h,false);v.camera.aspect=w/h;v.camera.updateProjectionMatrix();renderer.render(v.scene,v.camera);v.canvas.width=renderer.domElement.width;v.canvas.height=renderer.domElement.height;v.ctx.drawImage(renderer.domElement,0,0);v.dirty=false;}requestAnimationFrame(render);}render();
