import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {fleet,createFleetVehicle} from './ride-fleet-models.js';
const canvas=document.querySelector('canvas'),viewport=document.querySelector('#viewport');
const renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new T.Scene();scene.background=new T.Color('#727b70');scene.add(new T.HemisphereLight(0xe4edf0,0x484932,2));const sun=new T.DirectionalLight(0xfff0d9,2.3);sun.position.set(-8,12,6);scene.add(sun);
const floor=new T.Mesh(new T.PlaneGeometry(90,65),new T.MeshStandardMaterial({color:'#727668',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.02;scene.add(floor);
const camera=new T.OrthographicCamera(-10,10,10,-10,.1,160),controls=new OrbitControls(camera,canvas);controls.enableDamping=false;controls.maxPolarAngle=Math.PI*.49;controls.addEventListener('change',render);
const meshes=fleet.map(createFleetVehicle);let selected=-1;const box=new T.Box3(),target=new T.Vector3();let span=20;
meshes.forEach(m=>scene.add(m));
function render(){renderer.render(scene,camera);}
function fit(view='perspective'){box.makeEmpty();meshes.filter((m,i)=>selected<0||selected===i).forEach(m=>box.expandByObject(m));box.getCenter(target);controls.target.copy(target);let delta=view==='front'?new T.Vector3(0,.001,1):view==='side'?new T.Vector3(-1,.001,0):view==='top'?new T.Vector3(0,1,.001):selected<0?new T.Vector3(-1,.65,.9):new T.Vector3(-1,.62,1);camera.position.copy(target).addScaledVector(delta.normalize(),60);camera.lookAt(target);camera.updateMatrixWorld();const right=new T.Vector3(1,0,0).applyQuaternion(camera.quaternion),up=new T.Vector3(0,1,0).applyQuaternion(camera.quaternion);let ex=0,ey=0;for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const v=new T.Vector3(x,y,z).sub(target);ex=Math.max(ex,Math.abs(v.dot(right)));ey=Math.max(ey,Math.abs(v.dot(up)));}const aspect=viewport.clientWidth/viewport.clientHeight,h=Math.max(ey,ex/aspect)*1.12;camera.top=h;camera.bottom=-h;camera.left=-h*aspect;camera.right=h*aspect;camera.zoom=1;camera.updateProjectionMatrix();controls.update();render();}
function select(index){selected=index;meshes.forEach((m,i)=>{m.visible=index<0||i===index;m.position.set(index<0?(i%5-2)*1.5:0,0,index<0?(Math.floor(i/5)-.5)*3.4:0);});document.querySelectorAll('.choose').forEach((b,i)=>b.classList.toggle('active',i===index));document.querySelector('#all').classList.toggle('active',index<0);document.querySelector('#paint').disabled=index<0;if(index>=0)document.querySelector('#paint').value=fleet[index].color;document.querySelector('#caption').textContent=index<0?'오토바이 4종 · 자전거 4종 · 킥보드 2종 / 동일 축척':fleet[index].name+' · '+fleet[index].id;document.querySelector('#stats').textContent=index<0?'10종 / 동일 축척':`${meshes[index].geometry.attributes.position.count/3} 삼각형 · 1 메시 · 1 재질`;fit();}
document.querySelector('#list').innerHTML=fleet.map((d,i)=>`<article class="card"><button class="choose" data-index="${i}">${String(i+1).padStart(2,'0')} · ${d.name}</button><h2>${d.id.split('-').map(x=>x.toUpperCase()).join(' ')}</h2><p>${d.length} × ${d.width} × ${d.height} m</p><a href="${d.source}" target="_blank" rel="noopener">참고 도면 ↗</a> · <a href="./textures/vehicles/rides/${d.id}.jpg" target="_blank">텍스처 ↗</a></article>`).join('');
document.querySelectorAll('.choose').forEach(b=>b.onclick=()=>select(Number(b.dataset.index)));document.querySelector('#all').onclick=()=>select(-1); const quick=document.createElement('nav');quick.innerHTML=fleet.map((d,i)=>`<button data-quick="${i}">${d.name}</button>`).join('');viewport.before(quick);quick.querySelectorAll('button').forEach(b=>b.onclick=()=>select(Number(b.dataset.quick)));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>fit(b.dataset.view));document.querySelector('#paint').oninput=e=>{if(selected>=0){meshes[selected].material.userData.paint.value.set(e.target.value);render();}};document.querySelector('#wire').onchange=e=>{meshes.forEach(m=>m.material.wireframe=e.target.checked);render();};
function resize(){renderer.setSize(viewport.clientWidth,viewport.clientHeight,false);camera.aspect=viewport.clientWidth/viewport.clientHeight;camera.updateProjectionMatrix();fit();}new ResizeObserver(resize).observe(viewport);T.DefaultLoadingManager.onLoad=render;select(-1);resize();
window.rideFleetReview={count:fleet.length,meshes,select};
