import {PARTS,frameStats,partDescription} from './salvage-campaign.js';
import {createRoadRoute} from './road-route.js';
export function createBaseUI(campaign,{prepare,appearance}){
 const root=document.createElement('section');root.id='baseCamp';root.setAttribute('aria-label','본거지 원격 조종실');document.body.appendChild(root);
 const briefing=document.createElement('section');briefing.id='sortieBriefing';briefing.hidden=true;document.body.appendChild(briefing);
 const toast=document.createElement('div');toast.id='baseReturnToast';toast.hidden=true;toast.setAttribute('role','status');document.body.appendChild(toast);let toastTimer;
 const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let panel='frames',sort='recent';
 const icon=p=>`<img class="partImage" src="./images/parts/${p.type}.svg" alt="${PARTS[p.type].name}">`;
 function show(report=null){root.hidden=false;briefing.hidden=true;render();if(report){clearTimeout(toastTimer);toast.hidden=false;toast.innerHTML=`<b>${report.success?'원격 기체 귀환':'원격 기체 전손'} · ${safe(report.frame)}</b><p>${safe(report.reason)} · ${report.kills}개체 파괴 · ${report.success?report.parts.length+'개 부품 회수':report.lost+'개 수집품 소실'}</p><button aria-label="결과 알림 닫기">×</button>`;toast.querySelector('button').onclick=()=>toast.hidden=true;toastTimer=setTimeout(()=>toast.hidden=true,9000);}}
 function hide(){root.hidden=true;toast.hidden=true;}
 function sorted(items){const list=[...items];if(sort==='recent')return list.reverse();return list.sort((a,b)=>{if(sort==='levelDown')return b.level-a.level;if(sort==='levelUp')return a.level-b.level;if(sort==='type')return PARTS[a.type].slot.localeCompare(PARTS[b.type].slot)||PARTS[a.type].name.localeCompare(PARTS[b.type].name,'ko');return (a.identified?PARTS[a.type].name:'미감정').localeCompare(b.identified?PARTS[b.type].name:'미감정','ko');});}
 function card(p){const state=campaign.state,matches=state.stash.filter(q=>q.identified&&q.type===p.type&&q.level===p.level).length,cost=8*p.level;
  return `<article class="partCard">${p.identified?icon(p):'<div class="sealedPart" aria-label="미감정 부품">?</div>'}<div class="partInfo"><div class="partTitle"><h3>${p.identified?PARTS[p.type].name:'봉인된 기계 부품'}</h3><small>${p.identified?'Lv. '+p.level:'미감정'}</small><button class="partEquip" data-${p.identified?'install':'identify'}="${safe(p.id)}">${p.identified?(p.type==='repair'?'수리':'장착'):'감정'}</button></div><p>${p.identified?partDescription(p):'감정하면 부품 종류와 효과를 확인할 수 있습니다.'}</p>${p.identified?`<div class="partActions"><button data-combine="${safe(p.id)}" ${matches<3?'disabled':''}>합성 (${matches}/3)</button><button data-upgrade="${safe(p.id)}" ${state.materials<cost?'disabled':''}>강화 · 재료 ${cost}</button><button data-dismantle="${safe(p.id)}">분해 · +${4*p.level}</button></div>`:''}</div></article>`;
 }
 function render(){const state=campaign.state,robot=campaign.frame(),stats=frameStats(robot);
 root.innerHTML=`<div class="baseShell"><header class="compactBaseHeader"><h1>본거지</h1><a href="./settings.html" target="_blank" rel="noopener">동작 편집 ↗</a></header><nav><button data-tab="frames" aria-pressed="${panel==='frames'}">기체 격납고 (${state.frames.length})</button><button data-tab="stash" aria-pressed="${panel==='stash'}">부품 창고 (${state.stash.length})</button>${panel==='stash'?`<label class="stashSort">정렬 <select id="stashSort" aria-label="부품 정렬 방식">${[['recent','최근 획득순'],['name','이름순'],['type','부위별'],['levelDown','레벨 높은순'],['levelUp','레벨 낮은순']].map(([v,label])=>`<option value="${v}" ${v===sort?'selected':''}>${label}</option>`).join('')}</select></label>`:''}</nav><div class="baseColumns"><div class="baseInventory ${panel==='stash'?'stashInventory':''}">${panel==='frames'?state.frames.map(f=>{const s=frameStats(f);return `<button class="frameCard ${f.id===robot.id?'selected':''}" data-frame="${f.id}"><small>${f.id===robot.id?'출격 선택':'대기 기체'}</small><h3>${safe(f.name)}</h3><p>HP ${Math.ceil(f.hp)} / 100 · 배터리 ${s.battery}</p><span>${f.parts.length?f.parts.map(p=>PARTS[p.type].name+' Lv.'+p.level).join(' · '):'기본 뼈대 / 장착 부품 없음'}</span></button>`;}).join('')+`<button id="buildFrame" class="secondary" ${state.stash.some(p=>p.identified)?'':'disabled'}>감정한 부품 1개로 예비 기체 조립</button>`:state.stash.length?sorted(state.stash).map(card).join(''):'<p class="emptyStash">아직 회수한 부품이 없습니다.<br>적 잔해에서 수집한 뒤 살아 돌아오세요.</p>'}</div><aside><small>REMOTE UNIT</small><h2>${safe(robot.name)}</h2><div class="frameSilhouette"><div class="silHead"></div><div class="silBody"></div><div class="silArms"></div><div class="silLegs"></div></div><dl><div><dt>구조 상태</dt><dd>${Math.ceil(robot.hp)} / 100</dd></div><div><dt>배터리 용량</dt><dd>${stats.battery}</dd></div><div><dt>피해 / 이동</dt><dd>×${stats.damage.toFixed(2)} / ×${stats.speed.toFixed(2)}</dd></div><div><dt>추진 기능</dt><dd>${stats.jet?'대시 · 이단 점프':'미장착'}</dd></div></dl><div class="materialBalance">보유 재료 <b>${state.materials}</b><button id="repairFrame" ${robot.hp>=100||state.materials<1?'disabled':''}>HP 회복 · +${Math.min(100-robot.hp,Math.min(5,state.materials)*5)} / 재료 ${Math.min(5,state.materials,Math.ceil((100-robot.hp)/5))}</button><small>재료 1개당 HP 5 · 본거지 정비</small></div>${robot.parts.map(p=>`<button class="detachPart" data-remove="${safe(p.id)}">${PARTS[p.type].name} · Lv.${p.level} · 분리</button>`).join('')}<button id="prepareSortie">무기 2개 선택 · 출격 준비 →</button><p class="baseWarning">현장 체력 회복 불가 · 전손 시 기체와 적재품 소실<br>창고와 다른 기체는 보존됩니다.<br>출격 중 창 닫기·새로고침은 연결 종료로 기체를 잃습니다.</p>${campaign.storageError?'<p class="saveWarning">브라우저 저장에 실패했습니다.</p>':'<small>기체·창고는 이 브라우저에 저장됩니다.</small>'}</aside></div></div>`;
 root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{panel=b.dataset.tab;render();});root.querySelectorAll('[data-frame]').forEach(b=>b.onclick=()=>{campaign.select(Number(b.dataset.frame));render();});
 for(const action of['identify','install','remove','combine','upgrade','dismantle'])root.querySelectorAll(`[data-${action}]`).forEach(b=>b.onclick=()=>{campaign[action==='remove'?'uninstall':action](b.dataset[action]);render();});
 root.querySelector('#stashSort')?.addEventListener('change',e=>{sort=e.target.value;render();});root.querySelector('#buildFrame')?.addEventListener('click',()=>{campaign.build();render();});root.querySelector('#repairFrame').onclick=()=>{campaign.repair();render();};root.querySelector('#prepareSortie').onclick=prepare;
 const image=appearance(robot,stats);if(image)root.querySelector('.frameSilhouette').innerHTML=`<img class="framePreview" src="${image}" alt="선택한 원격 기체 모델">`;
 }
 function showBrief(weapons,launch){hide();briefing.hidden=false;const route=createRoadRoute(),project=p=>[40+(route.start.z-p.z)/(route.start.z-route.end.z)*520,110+p.x*1.4],points=route.points.map(p=>project(p).join(',')).join(' ');
 briefing.innerHTML=`<div class="briefShell"><small>입수한 정보 / OLD CITY 07</small><h1>무너진 대로 끝, 발전 코어</h1><p class="operatorLine"><b>OPERATOR</b> 야생 기체가 점거한 발전 시설에 고밀도 코어가 남아 있습니다. 수호 개체를 파괴해 코어를 회수한 뒤, 진입했던 도로로 돌아오세요.</p><svg class="missionMap" viewBox="0 0 600 240" role="img" aria-label="굽은 380m 도로 지도. 왼쪽 철수 지점에서 오른쪽 수호 개체와 코어 광장까지 진입 후 같은 길로 귀환합니다."><rect width="600" height="240" rx="12" fill="#14211e"/>${route.segments.flatMap(seg=>[.2,.6].map(t=>{const p=project({x:seg.a.x+(seg.b.x-seg.a.x)*t,z:seg.a.z+(seg.b.z-seg.a.z)*t});return `<rect x="${p[0]-10}" y="${p[1]-45}" width="22" height="16" fill="#33423d"/><rect x="${p[0]-10}" y="${p[1]+30}" width="22" height="16" fill="#33423d"/>`;})).join('')}<polyline points="${points}" fill="none" stroke="#465650" stroke-width="24" stroke-linejoin="round"/><polyline points="${points}" fill="none" stroke="#a8c882" stroke-width="2" stroke-dasharray="6 5"/><circle cx="40" cy="110" r="9" fill="#99dcbd"/><circle cx="560" cy="110" r="23" fill="#775b98"/><text x="30" y="160" fill="#d4ede0" font-size="12">진입 / 철수</text><text x="480" y="165" fill="#e3d6f3" font-size="12">수호 개체 / 코어 광장</text><text x="220" y="220" fill="#b4c8bd" font-size="12">경로 예시 · 실제 도로는 출격마다 변경</text></svg><div class="briefObjectives"><span>① 경계 중인 야생 기체를 돌파</span><span>② 보스 처치 후 보상 상자 개방</span><span>③ 코어 회수 · 귀환 적을 뚫고 복귀</span></div><p class="briefLoadout">출격 무기 · ${weapons.map(safe).join(' / ')}</p><div class="briefButtons"><button id="briefBack">← 무기 다시 선택</button><button id="deploySortie">원격 접속 · 출격 →</button></div></div>`;
 briefing.querySelector('#briefBack').onclick=()=>{briefing.hidden=true;prepare();};briefing.querySelector('#deploySortie').onclick=()=>{briefing.hidden=true;launch();};
 }
 return {show,hide,render,root,showBrief};
}
