import {sortieMission} from './sortie-mission.js';
import {BRICK_STORAGE} from './brick-street-layout.js';
import {EQUIPMENT,EQUIPMENT_SLOTS,equipmentDescription,equipmentIcon} from './equipment.js';
import {PARTS,frameStats,partDescription,weaponPerk} from './salvage-campaign.js';
export function createBaseUI(campaign,{prepare,appearance,weapons=[]}){
 const root=document.createElement('section');root.id='baseCamp';root.setAttribute('aria-label','본거지 원격 조종실');document.body.appendChild(root);
 const briefing=document.createElement('section');briefing.id='sortieBriefing';briefing.hidden=true;document.body.appendChild(briefing);
 const result=document.createElement('section');result.id='sortieResult';result.hidden=true;result.setAttribute('role','dialog');result.setAttribute('aria-modal','true');result.setAttribute('aria-labelledby','sortieResultTitle');document.body.appendChild(result);

 const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let panel=null,sort='recent',moduleSlot=null,weaponSlot=null,gearSlot=null,hangar=null,loadingHangar=false;let newModuleIds=new Set(),renderedPanel=null;
 const gunInfo=w=>weapons.find(v=>v.type===w?.type)||{name:'빈 무기 슬롯',image:''};
 function gunDescription(item){
  const w=gunInfo(item),details=[],number=n=>Number(n.toFixed(3));
  if(item.type==='bow')details.push('기본 피해 120~480 · 완충 2.2초');
  else if(item.type==='rail')details.push(`기본 피해 ${w.damageMin}~${w.damageMax} · 완충 2초`);
  else if(item.type==='laser')details.push('초당 피해 80→120→180→260→360');
  else if(item.type==='flame')details.push(`초당 연소 피해 ${w.damage}`);
  else if(item.type==='chainsaw')details.push(`초당 피해 ${w.damage}`);
  else if(w.pellets>1)details.push(`기본 피해 ${w.damage} × ${w.pellets}발 (최대 ${w.damage*w.pellets})`);
  else if(Number.isFinite(w.damage))details.push(`기본 피해 ${w.damage}`);
  if(!['laser','flame','chainsaw','bow','rail'].includes(item.type)&&w.rate)details.push(`공격 간격 ${number(w.rate)}초`);
  if(w.headshotMultiplier)details.push(`헤드샷 ${w.damage*w.headshotMultiplier}`);
  if(w.range)details.push(`사거리 ${w.range}m`);
  details.push(`${item.type==='knife'?'내구도':['flame','chainsaw'].includes(item.type)?'연료':'탄약'} ${w.ammo??'무한'}`);
  if(item.level>1)details.push(`강화 피해 +${(item.level-1)*10}%`);
  const perk=weaponPerk(item);if(perk.name)details.push(`${perk.name} · ${perk.description}`);return safe(details.join(' · '));
 }
 const moduleIcon=p=>`<img class="partImage" src="./images/parts/${p.type}.svg" alt="${safe(PARTS[p.type].name)}">`;
 const gunIcon=w=>`<img class="partImage gunItem" src="${gunInfo(w).image}" alt="${safe(gunInfo(w).name)}">`;
 function acknowledgeModules(){if(newModuleIds.size)campaign.markModulesSeen([...newModuleIds]);newModuleIds.clear();}
 function rotate(step){acknowledgeModules();const frames=campaign.state.frames,index=frames.findIndex(f=>f.id===campaign.frame().id);campaign.select(frames[(index+step+frames.length)%frames.length].id);panel=null;render();}
 function open(which){if(panel==='stash'&&which!=='stash')acknowledgeModules();if(which==='stash'&&panel!=='stash')newModuleIds=new Set(campaign.state.stash.filter(p=>p.isNew).map(p=>p.id));panel=which;moduleSlot=weaponSlot=gearSlot=null;render();}
 function closeResult(){result.hidden=true;root.querySelector('#hangarDeploy')?.focus();}
 function showResult(report){
  const number=v=>Number.isFinite(v)?Math.round(v*10)/10:'—',duration=v=>`${Math.floor((v||0)/60)}분 ${Math.floor((v||0)%60)}초`,groups=new Map();
  for(const item of report.items||[]){const key=[item.kind,item.type,item.level||1,item.perk||''].join(':');if(!groups.has(key))groups.set(key,{...item,count:0});groups.get(key).count++;}
  const recovered=[...groups.values()].map(p=>{const name=p.kind==='weapon'?gunInfo(p).name:p.kind==='equipment'?EQUIPMENT[p.type]?.name:PARTS[p.type]?.name,icon=p.kind==='weapon'?gunIcon(p):p.kind==='equipment'?gearIcon(p):moduleIcon(p);return `<li>${icon}<div><b>${safe(name||'회수 아이템')}</b><span>Lv.${p.level||1} · ${p.count}개${p.kind==='weapon'?' · '+safe(weaponPerk(p).name||''):''}</span></div></li>`;}).join('');
  result.innerHTML=`<div class="sortieResultCard"><button class="resultClose" aria-label="출격 결과 닫기">×</button><header><small>REMOTE UNIT / MISSION REPORT</small><h1 id="sortieResultTitle">${report.success?'본거지 복귀 완료':'원격 기체 유실'}</h1><p>${safe(report.frame)} · ${safe(report.reason)}</p></header><div class="resultStats">${[['파괴한 적',report.kills+' KILLS'],['출격 시간',duration(report.time)],['잃은 HP',number(report.hpLost)],['사용 에너지',number(report.energyUsed)],['복귀 HP',`${number(report.finalHP)} / ${number(report.maxHP)}`],['남은 배터리',`${number(report.energyRemaining)} / ${number(report.energyCapacity)}`]].map(([label,value])=>`<div><span>${label}</span><strong>${value}</strong></div>`).join('')}</div><p class="resultAccounting">받은 피해 ${number(report.damageReceived)} HP · 회복 ${number(report.hpRecovered)} HP · 현장 충전 +${number(report.energyRecovered)} 에너지</p><section><h2>${report.success?'확보한 아이템':'유실된 수집품'} <small>${report.success?(report.items?.length??report.parts.length+(report.weaponCount||0)+(report.equipmentCount||0)):report.lost}개</small></h2>${report.success?'<p>수집품이 창고에 보관되었습니다.</p>':'<p>기체와 장착품, 이번 출격에서 수집한 아이템을 잃었습니다.</p>'}<ul class="resultLoot">${recovered||'<li class="resultEmpty">'+(report.items?'수집한 아이템이 없습니다.':'이전 기록에는 아이템 상세 정보가 없습니다.')+'</li>'}</ul></section>${Object.keys(report.ammoRecovered||{}).length?`<section class="resultSupplies"><h2>현장에서 보급한 탄약</h2>${Object.entries(report.ammoRecovered).map(([type,count])=>`<span>${safe(gunInfo({type}).name)} +${count}</span>`).join('')}<p>전투 중 소비한 보급품은 창고 아이템에 포함되지 않습니다.</p></section>`:''}<footer><button id="confirmSortieResult">확인 · 기체 정비로</button></footer></div>`;
  result.hidden=false;result.querySelector('.resultClose').onclick=closeResult;result.querySelector('#confirmSortieResult').onclick=closeResult;result.querySelector('#confirmSortieResult').focus({preventScroll:true});
 }
 result.addEventListener('keydown',e=>{if(e.code==='Escape'){e.preventDefault();closeResult();}if(e.code==='Tab'){const first=result.querySelector('.resultClose'),last=result.querySelector('#confirmSortieResult');if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 function show(report=null){acknowledgeModules();root.hidden=false;briefing.hidden=true;result.hidden=true;panel=null;render();if(report)showResult(report);}
 function hide(){acknowledgeModules();root.hidden=true;result.hidden=true;}

 function sorted(items,isGun=false,isGear=false){const list=[...items],name=p=>isGear?EQUIPMENT[p.type].name:isGun?gunInfo(p).name:PARTS[p.type].name;if(sort==='recent')return list.reverse();return list.sort((a,b)=>sort==='levelDown'?b.level-a.level:sort==='levelUp'?a.level-b.level:sort==='type'?a.type.localeCompare(b.type):name(a).localeCompare(name(b),'ko'));}
 function card(p,isGun=false){const list=isGun?campaign.state.stashWeapons:campaign.state.stash,matches=list.filter(q=>q.type===p.type&&q.level===p.level).length,cost=8*p.level,fresh=!isGun&&newModuleIds.has(p.id);
 return `<article class="partCard ${fresh?'newModule':''}" ${fresh?'aria-label="새로 획득한 모듈"':''}>${isGun?gunIcon(p):moduleIcon(p)}<div class="partInfo"><div class="partTitle"><h3>${safe(isGun?gunInfo(p).name:PARTS[p.type].name)}</h3><small>Lv. ${p.level}</small>${fresh?'<span class="newModuleBadge">NEW · 새로 획득</span>':''}</div><p>${isGun?gunDescription(p):partDescription(p)}</p><div class="partActions">${(isGun?['upgrade','dismantle']:['combine','upgrade','dismantle']).map(action=>{const i=['combine','upgrade','dismantle'].indexOf(action);return `<button data-${isGun?'gun-':''}${action}="${safe(p.id)}" ${i===0&&matches<3||i===1&&campaign.state.materials<cost?'disabled':''}>${['합성 ('+matches+'/3)','강화 · 재료 '+cost,'분해 · +'+4*p.level][i]}</button>`;}).join('')}</div></div></article>`;
 }

 const gearIcon=p=>`<img class="partImage" src="${equipmentIcon(p)}" alt="${safe(EQUIPMENT[p.type].name)}">`;
 function gearCard(p){const matches=campaign.state.stashEquipment.filter(q=>q.type===p.type&&q.level===p.level).length;return `<article class="partCard">${gearIcon(p)}<div class="partInfo"><div class="partTitle"><h3>${safe(EQUIPMENT[p.type].name)}</h3><small>Lv. ${p.level} · ${EQUIPMENT_SLOTS[EQUIPMENT[p.type].slot]}</small></div><p>${equipmentDescription(p)}</p><div class="partActions">${['upgrade','dismantle'].map(action=>{const i=['combine','upgrade','dismantle'].indexOf(action);return `<button data-gear-${action}="${safe(p.id)}" ${i===0&&matches<3||i===1&&campaign.state.materials<8*p.level?'disabled':''}>${['합성 ('+matches+'/3)','강화 · 재료 '+8*p.level,'분해 · +'+4*p.level][i]}</button>`;}).join('')}</div></div></article>`;}
 function content(robot){
 if(panel==='equipment')return `<h2>${safe(robot.name)} · 외장 장비</h2><p>부위별 장비 1개 · 모듈 3칸과 별도 · 전손 시 장착 장비도 소실됩니다.</p><div class="moduleSockets gearSockets">${Object.entries(EQUIPMENT_SLOTS).map(([slot,name])=>{const p=robot.equipment[slot];return `<div><button data-gear-slot="${slot}"><small>${name}</small>${p?gearIcon(p)+`<b>${EQUIPMENT[p.type].name} · Lv.${p.level}</b><span>${equipmentDescription(p)}</span>`:'<b>빈 장비 슬롯 +</b>'}</button>${p?`<button data-gear-remove="${slot}">장비 분리</button>`:''}</div>`;}).join('')}</div>${gearSlot?`<h3>${EQUIPMENT_SLOTS[gearSlot]} · 장착 가능한 장비</h3><div class="socketChoices">${campaign.state.stashEquipment.filter(p=>EQUIPMENT[p.type].slot===gearSlot).map(p=>`<button data-gear-equip="${safe(p.id)}">${gearIcon(p)}<b>${EQUIPMENT[p.type].name} · Lv.${p.level}</b><span>${equipmentDescription(p)}</span></button>`).join('')||'<p>회수한 장비가 없습니다. 적에게서 장비를 획득한 뒤 귀환하세요.</p>'}</div>`:''}<header class="warehouseHeader"><h3>장비 창고 · 재료 ${campaign.state.materials}</h3><label>정렬 <select id="stashSort">${[['recent','최근 획득순'],['name','이름순'],['type','종류별'],['levelDown','레벨 높은순'],['levelUp','레벨 낮은순']].map(([v,n])=>`<option value="${v}" ${v===sort?'selected':''}>${n}</option>`).join('')}</select></label></header><div class="warehouseInventory">${sorted(campaign.state.stashEquipment,false,true).map(gearCard).join('')||'<p>아직 회수한 장비가 없습니다.</p>'}</div>`;
 if(panel==='modules')return `<h2>${safe(robot.name)} · 장착 모듈</h2><p>로봇 강화 모듈은 최대 3개 장착합니다.</p><div class="moduleSockets">${[0,1,2].map(slot=>{const p=robot.parts.find(p=>p.slot===slot);return `<div><button data-module-slot="${slot}"><small>MODULE ${slot+1}</small>${p?moduleIcon(p)+`<b>${PARTS[p.type].name} · Lv.${p.level}</b><span>${partDescription(p)}</span>`:'<b>빈 장착 칸 +</b><span>장착 가능한 모듈 보기</span>'}</button>${p?`<button data-remove="${safe(p.id)}">모듈 분리</button>`:''}</div>`;}).join('')}</div>${moduleSlot!==null?`<h3>${moduleSlot+1}번 칸 · 장착 가능한 모듈</h3><div class="socketChoices">${campaign.state.stash.map(p=>`<button data-install="${safe(p.id)}">${moduleIcon(p)}<b>${PARTS[p.type].name} · Lv.${p.level}</b><span>${partDescription(p)}</span></button>`).join('')||'<p>장착 가능한 모듈이 없습니다. 모듈을 회수하고 귀환해 주세요.</p>'}</div>`:''}`;
 if(panel==='mountWeapons')return `<h2>${safe(robot.name)} · 무기 걸이</h2><p>무기 1개만으로도 출격할 수 있습니다. 빈칸을 눌러 회수한 무기를 장착하세요.</p><div class="moduleSockets gunSockets">${robot.weaponSlots.map((w,slot)=>`<div><button data-weapon-slot="${slot}"><small>WEAPON ${slot+1}</small>${w?gunIcon(w)+`<b>${gunInfo(w).name} · Lv.${w.level}</b>`:'<b>빈 무기 걸이 +</b>'}</button>${w?`<button data-unmount="${slot}">무기 분리</button>`:''}</div>`).join('')}</div>${weaponSlot!==null?`<h3>${weaponSlot+1}번 걸이 · 장착 가능한 무기</h3><div class="socketChoices">${campaign.state.stashWeapons.filter(w=>!robot.weaponSlots.some((q,i)=>i!==weaponSlot&&q?.type===w.type)).map(w=>`<button data-equip="${safe(w.id)}">${gunIcon(w)}<b>${gunInfo(w).name} · Lv.${w.level}</b><span>${safe(weaponPerk(w).name||'')} · ${safe(weaponPerk(w).description||'')} · 강화 피해 +${(w.level-1)*10}%</span></button>`).join('')||'<p>장착 가능한 무기가 없습니다. 적에게서 무기를 회수하고 귀환하세요.</p>'}</div>`:''}`;
 const isGun=panel==='guns',items=isGun?campaign.state.stashWeapons:campaign.state.stash;
 return `<header class="warehouseHeader"><h2>${isGun?'수집 무기 창고':'모듈 창고'}</h2><label>정렬 <select id="stashSort">${[['recent','최근 획득순'],['name','이름순'],['type','종류별'],['levelDown','레벨 높은순'],['levelUp','레벨 낮은순']].map(([v,n])=>`<option value="${v}" ${v===sort?'selected':''}>${n}</option>`).join('')}</select></label></header><p>보유 재료 ${campaign.state.materials} · ${isGun?'재료를 사용해 강화':'같은 종류 / 같은 레벨 3개 합성'} · 장착품은 분리 후 강화</p><div class="warehouseInventory">${sorted(items,isGun).map(p=>card(p,isGun)).join('')||'<p>아직 회수한 '+(isGun?'무기':'모듈')+'가 없습니다.</p>'}</div>${!isGun?`<button id="repairFrame" ${robot.hp>=100||campaign.state.materials<1?'disabled':''}>재료로 기체 HP 회복 · 재료 1개당 HP 5</button>`:''}`;
 }
 function effects(stats){const pct=v=>`${Math.round(v*1000)/10}%`,rows=[['방어막',stats.shield,'+'],['자동 사격 피해',stats.autoDamage,'+'],['사냥개 공격력',stats.houndDamage,'+'],['최대 HP',stats.maxHP-100,'+'],['배터리 용량',stats.battery-100,'+'],['공격력',stats.damage-1],['이동 속도',stats.speed-1],['피해 감소',1-stats.damageTaken],['에너지 절약',1-stats.drain],['에임 보정',stats.accuracy],['헤드샷 보너스',stats.headshot],['치명타율',stats.crit],['회피율',stats.evasion],['HP 회복',stats.regen,'regen'],['근접 공격력',stats.melee-1],['대시 에너지 절약',1-stats.dashEfficiency]].filter(([,v])=>v>0.0001);if(stats.jet)rows.push(['제트팩',1,'jet']);return `<div class="hangarEffects"><small>장착 효과 · 기본 기체 대비</small><div>${rows.map(([name,v,type])=>`<span>${name}<b>${type==='+'?'+'+Math.round(v):type==='regen'?'+'+v.toFixed(1)+' HP/s':type==='jet'?'활성':pct(v)}</b></span>`).join('')||'<span>장착으로 증가한 수치가 없습니다.</span>'}</div></div>`;}
 function render(){const scrollPositions=renderedPanel===panel?[...root.querySelectorAll('.hangarModal,.equipmentWorkshop,.warehouseInventory,.socketChoices')].map(el=>({selector:'.'+el.classList[0],top:el.scrollTop,left:el.scrollLeft})):[];renderedPanel=panel;const state=campaign.state,robot=campaign.frame(),stats=frameStats(robot);
 root.innerHTML=`<div class="hangarView"><div id="hangarCanvas" aria-label="회전 거치대의 로봇과 모듈·무기·장비 장착기"></div><header class="hangarHeader"><span>REMOTE HANGAR <small>기체 정비실</small></span>${state.lastReport?'<button id="viewSortieResult">최근 출격 결과</button>':''}<a href="./robot-workshop.html" target="_blank" rel="noopener">로봇 프레임 ↗</a><a href="./asset-review.html" target="_blank" rel="noopener">에셋 교체 검토 ↗</a><a href="./settings.html" target="_blank" rel="noopener">동작 편집 ↗</a></header><button class="hangarArrow prev" aria-label="이전 로봇 선택"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 5 8 12l7 7"/></svg></button><button class="hangarArrow next" aria-label="다음 로봇 선택"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg></button><div class="hangarIdentity"><small>${state.frames.findIndex(f=>f.id===robot.id)+1} / ${state.frames.length}</small><h1><button id="renameFrame" aria-label="기체 이름 수정" title="클릭하여 이름 수정">${safe(robot.name)} <i>✎</i></button></h1><div class="hangarVitals"><span>HP<b>${Math.round(robot.hp/100*stats.maxHP)} <em>/ ${Math.round(stats.maxHP)}</em></b></span><span>배터리<b>${Math.round(stats.battery)}</b></span><span>모듈<b>${robot.parts.length} <em>/ 3</em></b></span></div>${effects(stats)}</div><button id="openModules" class="hangarStation computerStation"><small>MODULE TERMINAL</small><b>모듈 장착기</b><span>${robot.parts.length} / 3 장착</span></button><button id="openMountWeapons" class="hangarStation mountedWeaponStation"><small>UNIT WEAPONS</small><b>무기 장착기</b><span>${robot.weaponSlots.map(w=>w?gunInfo(w).name+' Lv.'+w.level:'빈칸').join(' / ')}</span></button><button id="openParts" class="hangarStation partsStation"><small>MODULE STORAGE</small><b>모듈 상자</b><span>보유 ${state.stash.length}개 / 재료 ${state.materials}</span></button><button id="openGuns" class="hangarStation weaponsStation"><small>WEAPON STORAGE</small><b>수집 무기 창고</b><span>보유 ${state.stashWeapons.length}개 · 강화 / 분해</span></button><button id="openEquipment" class="hangarStation equipmentStation"><small>BODY EQUIPMENT</small><b>장비 장착기</b><span>${Object.keys(robot.equipment).length} / 5 장착 · 보유 ${state.stashEquipment.length}개</span></button><footer class="hangarFooter"><button id="newFrame" ${state.stash.length>0?'':'disabled'}>예비 기체 조립</button><button id="hangarDeploy" ${robot.weaponSlots.some(Boolean)?'':'disabled'}>출격 준비 →</button></footer></div>${panel?`<div class="hangarModal" role="dialog" aria-label="${{equipment:'외장 장비',modules:'모듈 장착',mountWeapons:'무기 장착',stash:'모듈 창고',guns:'무기 창고'}[panel]}"><div class="equipmentWorkshop"><button id="closeEquipment" aria-label="정비 창 닫기">×</button>${content(robot)}</div></div>`:''}`;
 root.querySelector('#renameFrame').onclick=()=>{const button=root.querySelector('#renameFrame'),input=document.createElement('input');input.className='frameNameInput';input.value=robot.name;input.maxLength=24;input.setAttribute('aria-label','기체 이름');button.replaceWith(input);input.focus();input.select();let done=false;const finish=commit=>{if(done)return;done=true;if(commit)campaign.rename(input.value);render();};input.onblur=()=>finish(true);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();finish(true);}if(e.key==='Escape'){e.preventDefault();finish(false);}};};
 root.querySelector('#viewSortieResult')?.addEventListener('click',()=>showResult(campaign.state.lastReport));
 root.querySelector('.prev').onclick=()=>rotate(-1);root.querySelector('.next').onclick=()=>rotate(1);
 for(const [id,which]of [['openEquipment','equipment'],['openModules','modules'],['openMountWeapons','mountWeapons'],['openParts','stash'],['openGuns','guns']])root.querySelector('#'+id).onclick=()=>open(which);
 root.querySelector('#closeEquipment')?.addEventListener('click',()=>open(null));
 root.querySelectorAll('[data-module-slot]').forEach(b=>b.onclick=()=>{moduleSlot=Number(b.dataset.moduleSlot);render();});root.querySelectorAll('[data-weapon-slot]').forEach(b=>b.onclick=()=>{weaponSlot=Number(b.dataset.weaponSlot);render();});
 root.querySelectorAll('[data-install]').forEach(b=>b.onclick=()=>{campaign.install(b.dataset.install,moduleSlot);moduleSlot=null;render();});root.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{campaign.equipWeapon(b.dataset.equip,weaponSlot);weaponSlot=null;render();});root.querySelectorAll('[data-unmount]').forEach(b=>b.onclick=()=>{campaign.unequipWeapon(Number(b.dataset.unmount));render();});
 for(const action of['remove','combine','upgrade','dismantle'])root.querySelectorAll(`[data-${action}]`).forEach(b=>b.onclick=()=>{campaign[action==='remove'?'uninstall':action](b.dataset[action]);render();});
 for(const action of['combine','upgrade','dismantle'])root.querySelectorAll(`[data-gun-${action}]`).forEach(b=>b.onclick=()=>{campaign.craftWeapon(action,b.getAttribute('data-gun-'+action));render();});
 root.querySelectorAll('[data-gear-slot]').forEach(b=>b.onclick=()=>{gearSlot=b.dataset.gearSlot;render();});root.querySelectorAll('[data-gear-equip]').forEach(b=>b.onclick=()=>{campaign.equipEquipment(b.dataset.gearEquip);gearSlot=null;render();});root.querySelectorAll('[data-gear-remove]').forEach(b=>b.onclick=()=>{campaign.unequipEquipment(b.dataset.gearRemove);render();});for(const action of ['combine','upgrade','dismantle'])root.querySelectorAll(`[data-gear-${action}]`).forEach(b=>b.onclick=()=>{campaign.craftEquipment(action,b.getAttribute('data-gear-'+action));render();});
 root.querySelector('#stashSort')?.addEventListener('change',e=>{sort=e.target.value;render();});root.querySelector('#repairFrame')?.addEventListener('click',()=>{campaign.repair();render();});root.querySelector('#newFrame').onclick=()=>{campaign.build();render();};root.querySelector('#hangarDeploy').onclick=prepare;
 const host=root.querySelector('#hangarCanvas');if(hangar){hangar.attach(host);hangar.update(state.frames,state.selected,state.stashWeapons);}else if(!loadingHangar){loadingHangar=true;import('./hangar-scene.js').then(({createHangarScene})=>{hangar=createHangarScene(root.querySelector('#hangarCanvas'),open);hangar.update(campaign.state.frames,campaign.state.selected,campaign.state.stashWeapons);}).catch(error=>{console.error('Hangar scene failed',error);loadingHangar=false;root.querySelector('#hangarCanvas').textContent='격납고 화면을 불러오지 못했습니다. 새로고침해 주세요.';});}appearance(robot,stats);for(const position of scrollPositions){const element=root.querySelector(position.selector);if(element){element.scrollTop=position.top;element.scrollLeft=position.left;}}
 }
 function showBrief(weapons,launch){hide();briefing.hidden=false;let hasSaved=false;try{hasSaved=JSON.parse(localStorage.getItem(BRICK_STORAGE)||'[]').length>0;}catch{}
 briefing.innerHTML=`<div class="briefShell"><small>REMOTE SORTIE / 출격 계획</small><h1>어디로 출격할까요?</h1><p class="operatorLine">폐허 거리를 돌파해 마지막 블록의 보스를 처치하고, 발전 코어를 회수한 뒤 귀환하세요.</p><label class="missionField">목적지<select id="missionDestination"><option value="brick">붉은 벽돌 주거지 · 새 랜덤 거리</option><option value="saved" ${hasSaved?'':'disabled'}>보관한 거리 블록 ${hasSaved?'':'· 먼저 거리 생성기에서 보관하세요'}</option></select></label><label class="missionField">거리 블록 수<input id="missionBlocks" type="number" min="1" max="12" step="1" value="4"></label><div id="missionSummary" class="briefObjectives" aria-live="polite"></div><p>블록이 많아질수록 적 체력·공격력·공격 속도가 올라갑니다. 마지막 구간은 보스 전투 공간으로 비워집니다.</p><p class="briefLoadout">출격 무기 · ${weapons.map(safe).join(' / ')}</p><div class="briefButtons"><button id="briefBack">← 기체 정비로</button><button id="deploySortie">원격 접속 · 출격 →</button></div></div>`;
 const selection=()=>sortieMission({destination:briefing.querySelector('#missionDestination').value,blocks:briefing.querySelector('#missionBlocks').value}),summary=()=>{const m=selection();briefing.querySelector('#missionSummary').innerHTML=`<span>${m.blocks}블록 · 진행 거리 ${m.length}m</span><span>적 체력·공격력 ×${m.difficulty.toFixed(2)}</span><span>마지막 블록 · 보스 1체</span>`;};briefing.querySelector('#missionBlocks').oninput=summary;briefing.querySelector('#missionDestination').onchange=summary;summary();
 briefing.querySelector('#briefBack').onclick=()=>{briefing.hidden=true;show();};briefing.querySelector('#deploySortie').onclick=async()=>{const button=briefing.querySelector('#deploySortie');button.disabled=true;button.textContent='거리 준비 중…';try{await launch(selection());briefing.hidden=true;}catch(error){button.disabled=false;button.textContent='다시 출격';briefing.querySelector('#missionSummary').textContent='거리를 불러오지 못했습니다. '+error.message;}};
 }
 return {show,hide,render,root,showBrief};
}
