import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {createThreeSedan} from './sedan-mesh.js';
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const views=[],target=new T.Vector3(0,.9,0),initial=new T.Vector3(6,3.5,7);let updating=false;
function setup(id){const card=document.getElementById(id),canvas=card.querySelector('canvas'),ctx=canvas.getContext('2d'),scene=new T.Scene();scene.background=new T.Color(0xdce1d3);scene.add(new T.HemisphereLight(0xffeedb,0x7d9586,2));const key=new T.DirectionalLight(0xffead1,2.7);key.position.set(-3,7,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-5,right:5,top:5,bottom:-5});key.shadow.bias=-.0005;scene.add(key);const ground=new T.Mesh(new T.CylinderGeometry(3.25,3.25,.1,64),new T.MeshStandardMaterial({color:0xc6cdbb,roughness:1}));ground.position.y=-.06;ground.receiveShadow=true;scene.add(ground);const camera=new T.PerspectiveCamera(37,1,.05,100);camera.position.copy(initial);const controls=new OrbitControls(camera,canvas);controls.target.copy(target);controls.enablePan=false;controls.minDistance=3;controls.maxDistance=16;controls.maxPolarAngle=Math.PI*.495;controls.update();const v={id,card,canvas,ctx,scene,camera,controls,model:null,dirty:true};views.push(v);new ResizeObserver(()=>v.dirty=true).observe(canvas);controls.addEventListener('change',()=>{v.dirty=true;if(updating||!document.querySelector('#sync').checked)return;updating=true;for(const other of views)if(other!==v){other.camera.position.copy(camera.position);other.controls.target.copy(controls.target);other.controls.update();other.dirty=true;}updating=false;});canvas.addEventListener('keydown',e=>{const dirs={ArrowLeft:[-.12,0],ArrowRight:[.12,0],ArrowUp:[0,-.1],ArrowDown:[0,.1]};if(!dirs[e.key])return;e.preventDefault();const s=new T.Spherical().setFromVector3(camera.position.clone().sub(controls.target));s.theta+=dirs[e.key][0];s.phi=T.MathUtils.clamp(s.phi+dirs[e.key][1],.1,controls.maxPolarAngle);camera.position.copy(controls.target).add(new T.Vector3().setFromSpherical(s));controls.update();});return v;}
function attach(v,model){v.model=model;let triangles=0,meshes=0;model.traverse(o=>{if(o.isMesh){meshes++;o.castShadow=o.receiveShadow=true;triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;}});v.scene.add(model);v.card.querySelector('.stats').textContent=`${Math.round(triangles).toLocaleString()} 삼각형 · ${meshes} 메시 · 약 4.8m 길이`;v.dirty=true;}
attach(setup('three'),createThreeSedan());const blender=setup('blender');new GLTFLoader().load(new URL('./models/sedan/blender-sedan.glb',document.baseURI).href,gltf=>{attach(blender,gltf.scene);blender.card.querySelector('.status').remove();applyWire();},undefined,error=>{blender.card.querySelector('.status').textContent='모델을 불러오지 못했습니다. 새로고침해 주세요.';console.error(error);});
function setCamera(pos){updating=true;for(const v of views){v.camera.position.copy(pos);v.controls.target.copy(target);v.controls.update();v.dirty=true;}updating=false;}
for(const[id,pos]of[['front',new T.Vector3(0,2.1,8)],['rear',new T.Vector3(0,2.1,-8)],['side',new T.Vector3(8,1.7,0)],['reset',initial]])document.getElementById(id).onclick=()=>setCamera(pos);
function applyWire(){for(const v of views){v.model?.traverse(o=>{if(o.isMesh)for(const m of(Array.isArray(o.material)?o.material:[o.material]))m.wireframe=document.getElementById('wire').checked;});v.dirty=true;}}document.getElementById('wire').onchange=applyWire;document.getElementById('sync').onchange=()=>{if(document.getElementById('sync').checked)setCamera(views[0].camera.position.clone());};
document.querySelector('.export').onclick=async()=>{const data=await new GLTFExporter().parseAsync(views[0].model,{binary:true});const url=URL.createObjectURL(new Blob([data],{type:'model/gltf-binary'}));const a=document.createElement('a');a.href=url;a.download='three-sedan.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function frame(){for(const v of views){if(!v.dirty)continue;const w=v.canvas.clientWidth,h=v.canvas.clientHeight;if(!w||!h)continue;renderer.setSize(w,h,false);v.camera.aspect=w/h;v.camera.updateProjectionMatrix();renderer.render(v.scene,v.camera);v.canvas.width=renderer.domElement.width;v.canvas.height=renderer.domElement.height;v.ctx.drawImage(renderer.domElement,0,0);v.dirty=false;}requestAnimationFrame(frame);}frame();window.sedanComparison={views,renderer};

window.addEventListener('vehicle-texture-ready',()=>views.forEach(v=>v.dirty=true));
