import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {loadPurchasedModels} from './purchased-model-library.js';
import {composeReferenceAssets,referenceAssetInfo} from './reference-buildings.js';
import {createStreetProps} from './street-props.js';
import {BLOCK_STORAGE,SURFACES,validateBlock,objectBounds,corridorIssues} from './street-blocks.js';
const $=id=>document.getElementById(id),clone=o=>JSON.parse(JSON.stringify(o)),uid=()=>crypto.randomUUID();
const names={car:'버려진 세단',pickup_1:'녹슨 픽업',pickup_2:'파손된 픽업',gas_Station_building_1:'주유소',pharmacy_building:'약국',gas_station_annex_1:'주유소 별관',bush_1:'무성한 관목',grass_green_1:'푸른 풀',leaf_1:'덩굴 잎',rubble_1:'콘크리트 잔해',rubble_2:'부서진 돌',road_barrier:'도로 방호벽',road_chunk_1:'파손 도로 조각 A',road_chunk_2:'파손 도로 조각 B',electric_pole_1:'전봇대',metal_wire_fence:'철망 울타리',wooden_spike_barricade:'목재 바리케이드',tire_cluster:'버려진 타이어',box_1:'보급 상자',barrel_damaged_blue:'파손 드럼통','wreck-bus':'버려진 버스','wreck-truck':'버려진 화물차','traffic-light':'신호등','street-lamp':'가로등','lush-tree':'무성한 큰 나무','pavement-break':'파손된 포장'};
for(const info of referenceAssetInfo)names[info.id]=info.name;
const category=id=>id.startsWith('ref-')||/building|annex|Bunker/.test(id)?'건물':/car|pickup|wreck/.test(id)?'차량':/tree|bush|grass|leaf/.test(id)?'식생':/wall|Wall|Floor/.test(id)?'건축 부품':/road|pavement/.test(id)?'도로·잔해':'소품';
const defaultSize=id=>id.startsWith('ref-')?23:id==='lush-tree'?13:id==='wreck-bus'?12:id==='wreck-truck'?9:/car|pickup/.test(id)?6.4:/traffic|lamp|pole/.test(id)?5.5:/tree/.test(id)?10:/building/.test(id)?12:/grass|bush|rubble|leaf/.test(id)?1.7:3;
const defaultSolid=id=>['건물','차량','건축 부품'].includes(category(id))||/barrier|barricade|fence|box|barrel/.test(id);
const blank=()=>({version:1,id:uid(),name:'나의 폐허 거리',size:40,roadWidth:10,surface:'asphalt',objects:[]});
let block=blank(),saved=[],library,selected=null,placement=null,activeCategory='건물',undo=[],redo=[],walking=false,walkingPosition=new T.Vector3(),walkYaw=0,walkPitch=0,lastTime=performance.now(),pointerStart;
let makingPreset=false;
const meshes=new Map(),thumbs=new Map(),keys=new Set();
const scene=new T.Scene();scene.background=new T.Color(0x9eaa97);scene.fog=new T.Fog(0x9eaa97,130,260);scene.add(new T.HemisphereLight(0xe9f0d4,0x53624b,2));const sun=new T.DirectionalLight(0xfff0d2,3);sun.position.set(-25,60,25);scene.add(sun);
const root=new T.Group(),ground=new T.Group(),overlay=new T.Group();scene.add(root,ground,overlay);const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('viewport').append(renderer.domElement);
const camera=new T.PerspectiveCamera(45,1,.1,400);camera.position.set(48,43,53);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,5,0);controls.maxDistance=150;controls.maxPolarAngle=Math.PI*.495;controls.enableDamping=true;controls.update();
const transform=new TransformControls(camera,renderer.domElement);scene.add(transform.getHelper());transform.setSize(.8);transform.addEventListener('dragging-changed',e=>controls.enabled=!e.value);transform.addEventListener('mouseDown',()=>remember());transform.addEventListener('objectChange',()=>{if(!selected)return;const obj=meshes.get(selected),data=block.objects.find(o=>o.uid===selected);data.x=T.MathUtils.clamp(obj.position.x,-block.size/2,block.size/2);data.y=T.MathUtils.clamp(obj.position.y,0,60);data.z=T.MathUtils.clamp(obj.position.z,-block.size/2,block.size/2);data.rotation=obj.rotation.y;data.scale=T.MathUtils.clamp(obj.scale.x,.05,10);applyObject(obj,data);refreshFields();draft();});
const ray=new T.Raycaster(),mouse=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),0);
function notice(text){$('notice').textContent=text;}
function draft(){if(makingPreset)return;try{localStorage.setItem('last-spark-street-draft-v1',JSON.stringify(block));}catch{notice('브라우저 저장 공간이 부족합니다. JSON으로 내보내 주세요.');}}
function remember(){undo.push(clone(block));if(undo.length>80)undo.shift();redo=[];updateUndo();}
function updateUndo(){$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;}
function history(from,to){if(!from.length)return;to.push(clone(block));block=from.pop();selected=null;rebuild();updateUndo();draft();}
function createMesh(id){const group=new T.Group();for(const p of library.get(id).parts){const mesh=new T.Mesh(p.geometry,p.material);mesh.receiveShadow=true;group.add(mesh);}return group;}
function applyObject(obj,o){obj.position.set(o.x,o.y,o.z);obj.rotation.set(0,o.rotation,0);obj.scale.setScalar(o.scale);obj.userData.uid=o.uid;}
function disposeGround(){ground.traverse(o=>{if(o.isMesh||o.isLineSegments){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});ground.clear();overlay.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});overlay.clear();}
function floorBox(w,h,d,x,y,z,color){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,roughness:1}));m.position.set(x,y,z);ground.add(m);}
function rebuildFloor(){disposeGround();const s=block.size,w=block.roadWidth;floorBox(s,.18,s,0,-.12,0,SURFACES[block.surface].color);floorBox(w,.08,s,0,.015,0,SURFACES[block.surface].color);for(const side of[-1,1])floorBox(2,.18,s,side*(w/2+1),.06,0,0x929985);for(let z=-s/2+3;z<s/2;z+=6)floorBox(.13,.015,2,0,.07,z,0xc5c4a3);const grid=new T.GridHelper(s,s,0x799366,0x74846c);grid.position.y=.075;grid.material.transparent=true;grid.material.opacity=.25;ground.add(grid);const path=new T.Mesh(new T.PlaneGeometry(3,s),new T.MeshBasicMaterial({color:0xbbe97f,transparent:true,opacity:.13,depthWrite:false}));path.rotation.x=-Math.PI/2;path.position.y=.09;path.visible=$('showPath').checked;overlay.add(path);for(const z of[-s/2+.4,s/2-.4]){const gate=new T.Mesh(new T.BoxGeometry(w,.08,.25),new T.MeshBasicMaterial({color:z>0?0xc7ed88:0x78c1d5}));gate.position.set(0,.13,z);overlay.add(gate);}$('viewport').querySelector('.view-label').innerHTML=`${s} × ${s} m <span>입구 남 / 출구 북 · 중앙 3m 통행로</span>`;}
function rebuild(){transform.detach();root.clear();meshes.clear();for(const o of block.objects){if(!library.has(o.asset))continue;const m=createMesh(o.asset);applyObject(m,o);root.add(m);meshes.set(o.uid,m);}rebuildFloor();$('blockName').value=block.name;$('blockSize').value=block.size;$('roadWidth').value=block.roadWidth;$('surface').value=block.surface;refreshObjects();refreshFields();}
function refreshObjects(){$('objectCount').textContent=block.objects.length;$('objects').replaceChildren();for(const o of block.objects){const b=document.createElement('button');b.textContent=names[o.asset]||o.asset;b.classList.toggle('active',o.uid===selected);b.onclick=()=>select(o.uid);$('objects').append(b);}}
function select(id){selected=id;placement=null;$('placement').hidden=true;document.querySelectorAll('.asset').forEach(b=>b.classList.remove('active'));if(id&&meshes.has(id))transform.attach(meshes.get(id));else transform.detach();refreshFields();refreshObjects();}
function refreshFields(){const o=block.objects.find(v=>v.uid===selected);$('objectFields').hidden=!o;$('selectedName').textContent=o?(names[o.asset]||o.asset):'물체를 선택하세요';if(!o)return;for(const [id,value]of Object.entries({posX:o.x,posY:o.y,posZ:o.z,rotation:o.rotation*180/Math.PI,objectScale:o.scale}))$(id).value=Number(value.toFixed(2));$('solid').checked=o.solid;}
function add(id,x=0,z=0,rotation=0){const o={uid:uid(),asset:id,x,y:0,z,rotation,scale:defaultSize(id)/library.get(id).maxSize,solid:defaultSolid(id)};block.objects.push(o);const m=createMesh(id);applyObject(m,o);root.add(m);meshes.set(o.uid,m);draft();return o;}
function thumbnail(id){if(thumbs.has(id))return thumbs.get(id);const ts=new T.Scene();ts.background=new T.Color(0x354033);ts.add(new T.HemisphereLight(0xffffe0,0x526245,3));const l=new T.DirectionalLight(0xffedd2,3);l.position.set(-20,30,30);ts.add(l);const m=createMesh(id);ts.add(m);const t=library.get(id),r=t.maxSize;const c=new T.PerspectiveCamera(35,1.3,.01,r*10);c.position.set(r*1.15,r*.95,r*1.3);c.lookAt(0,t.size.y*.45,0);renderer.setSize(130,100,false);renderer.render(ts,c);const url=renderer.domElement.toDataURL();thumbs.set(id,url);return url;}
function renderCatalog(){$('assets').replaceChildren();const term=$('search').value.toLowerCase();for(const id of library.keys()){if(id==='ruin-wall'||category(id)!==activeCategory||!(names[id]||id).toLowerCase().includes(term))continue;const b=document.createElement('button');b.className='asset';b.dataset.asset=id;const img=document.createElement('img');img.src=thumbnail(id);img.alt='';const label=document.createElement('span');label.textContent=names[id]||id;b.append(img,label);b.onclick=()=>{select(null);placement=id;b.classList.add('active');$('placement').hidden=false;$('placement').textContent=`${names[id]||id} · 바닥 클릭으로 배치 · ESC 취소`;notice('바닥을 클릭해 배치하세요. 배치 후 다시 선택하면 이동·회전할 수 있습니다.');};$('assets').append(b);}}
function renderSaved(){$('blocks').replaceChildren();for(const b of saved){const card=document.createElement('div');card.className='block-card';const title=document.createElement('strong');title.textContent=b.name;const desc=document.createElement('small');desc.textContent=`${b.size}m · ${b.objects.length}개 물체 · ${SURFACES[b.surface].name}`;const open=document.createElement('button');open.textContent='편집';open.onclick=()=>{remember();block=clone(b);selected=null;rebuild();draft();notice('저장한 블록을 불러왔습니다.');};const remove=document.createElement('button');remove.textContent='삭제';remove.onclick=()=>{saved=saved.filter(v=>v.id!==b.id);persist();renderSaved();notice('저장 목록에서 제거했습니다. 현재 작업과 JSON 백업은 유지됩니다.');};card.append(title,desc,open,remove);$('blocks').append(card);}}
function persist(){localStorage.setItem(BLOCK_STORAGE,JSON.stringify(saved));}
function save(){block=validateBlock(block);const i=saved.findIndex(b=>b.id===block.id);if(i<0)saved.push(clone(block));else saved[i]=clone(block);persist();renderSaved();notice(`“${block.name}” 저장 완료 · 이 브라우저에 보관됩니다.`);}
function makePreset(name,type){makingPreset=true;const old=block;block=blank();block.name=name;for(const side of[-1,1])for(const z of[-13,0,13]){const id=type===1?'ref-roofless':type===2?'ref-office':'ref-brownstone';const o=add(id,side*14,z,-side*Math.PI/2);o.scale=11.5/library.get(id).size.z;applyObject(meshes.get(o.uid),o);}for(const side of[-1,1]){add('lush-tree',side*6.5,side*11);add('street-lamp',side*6.4,-side*12,-side*Math.PI/2);for(let i=0;i<7;i++){add(i%3?'grass_green_1':'bush_1',side*(4+i%3),-17+i*5);add('rubble_1',side*5.8,-15+i*4);}}add(type===1?'wreck-bus':type===2?'wreck-truck':'car',4.9,0);add('car',-4.8,10);add('traffic-light',-6.3,-17,0);const result=clone(block);block=old;makingPreset=false;return result;}
function setMode(mode){transform.setMode(mode);for(const [id,m]of [['translate','translate'],['rotate','rotate'],['scaleTool','scale']])$(id).classList.toggle('active',m===mode);transform.showX=mode!=='rotate';transform.showY=true;transform.showZ=mode!=='rotate';if(mode==='scale'){transform.showY=false;transform.showZ=false;}updateSnap();}
function updateSnap(){transform.setTranslationSnap($('snap').checked?1:null);transform.setRotationSnap($('snap').checked?Math.PI/12:null);transform.setScaleSnap($('snap').checked?.1:null);}
renderer.domElement.addEventListener('pointerdown',e=>{pointerStart={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',e=>{if(walking||transform.dragging||!pointerStart||Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>4)return;const rect=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(mouse,camera);if(placement){const p=new T.Vector3();if(!ray.ray.intersectPlane(plane,p)||Math.abs(p.x)>block.size/2||Math.abs(p.z)>block.size/2)return;remember();const id=placement;const o=add(id,$('snap').checked?Math.round(p.x):p.x,$('snap').checked?Math.round(p.z):p.z);select(o.uid);notice('배치했습니다. 이동 화살표를 드래그해 위치를 바꿔보세요.');return;}if(transform.axis)return;const hit=ray.intersectObjects(root.children,true)[0];let obj=hit?.object;while(obj&&!obj.userData.uid)obj=obj.parent;select(obj?.userData.uid||null);});
$('translate').onclick=()=>setMode('translate');$('rotate').onclick=()=>setMode('rotate');$('scaleTool').onclick=()=>setMode('scale');$('selectTool').onclick=()=>select(null);$('undo').onclick=()=>history(undo,redo);$('redo').onclick=()=>history(redo,undo);$('snap').onchange=updateSnap;$('showPath').onchange=()=>rebuildFloor();$('search').oninput=()=>library&&renderCatalog();
$('top').onclick=()=>{controls.target.set(0,0,0);camera.position.set(0,block.size*1.6,.01);controls.update();};$('orbit').onclick=()=>{controls.target.set(0,5,0);camera.position.set(48,43,53);controls.update();};
for(const id of['blockName','blockSize','roadWidth','surface'])$(id).onchange=()=>{remember();const size=Number($('blockSize').value),width=Number($('roadWidth').value);block.name=$('blockName').value.trim()||'이름 없는 거리';block.size=size;block.roadWidth=T.MathUtils.clamp(width||10,6,14);block.surface=$('surface').value;for(const o of block.objects){o.x=T.MathUtils.clamp(o.x,-size/2,size/2);o.z=T.MathUtils.clamp(o.z,-size/2,size/2);}rebuild();draft();};
for(const id of['posX','posY','posZ','rotation','objectScale','solid'])$(id)[id==='solid'?'onchange':'oninput']=()=>{const o=block.objects.find(o=>o.uid===selected);if(!o)return;const values=['posX','posY','posZ','rotation','objectScale'].map(id=>Number($(id).value));if(values.some(n=>!Number.isFinite(n))||['posX','posY','posZ','rotation','objectScale'].some(id=>$(id).value===''))return;remember();Object.assign(o,{x:T.MathUtils.clamp(values[0],-block.size/2,block.size/2),y:T.MathUtils.clamp(values[1],0,60),z:T.MathUtils.clamp(values[2],-block.size/2,block.size/2),rotation:values[3]*Math.PI/180,scale:T.MathUtils.clamp(values[4],.05,10),solid:$('solid').checked});applyObject(meshes.get(o.uid),o);draft();};
$('duplicate').onclick=()=>{const o=block.objects.find(o=>o.uid===selected);if(!o)return;remember();const copy={...o,uid:uid(),z:Math.min(block.size/2,o.z+2)};block.objects.push(copy);const m=createMesh(copy.asset);applyObject(m,copy);root.add(m);meshes.set(copy.uid,m);select(copy.uid);draft();};$('delete').onclick=()=>{if(!selected)return;remember();block.objects=block.objects.filter(o=>o.uid!==selected);root.remove(meshes.get(selected));meshes.delete(selected);select(null);draft();};
$('buildRows').onclick=()=>{remember();let count=0;for(const [side,id]of[[-1,$('leftBuilding').value],[1,$('rightBuilding').value]]){if(!id)continue;const t=library.get(id),scale=12/t.size.z,span=t.size.x*scale;for(let z=-block.size/2+span/2;z+span/2<=block.size/2+.1;z+=span+.2){const x=side*(block.roadWidth/2+2+t.size.z*scale/2);if(Math.abs(x)>block.size/2)continue;if(block.objects.some(o=>category(o.asset)==='건물'&&Math.sign(o.x)===side&&Math.abs(o.z-z)<span*.8))continue;const o=add(id,x,z,-side*Math.PI/2);o.scale=scale;applyObject(meshes.get(o.uid),o);count++;}}refreshObjects();draft();notice(`좌우 건물 ${count}개를 배치했습니다.`);};
$('newBlock').onclick=()=>{remember();block=blank();selected=null;rebuild();draft();notice('빈 블록을 만들었습니다. 이전 작업은 실행 취소로 돌아갈 수 있습니다.');};$('save').onclick=()=>{try{save();}catch(e){notice(e.message);}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(validateBlock(block),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(block.name.replace(/[^\p{L}\p{N}\-_]/gu,'_')||'street-block')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('배치 정보를 JSON 파일로 내보냈습니다. 모델 파일은 포함되지 않습니다.');};
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('블록 파일은 2MB 이하만 지원합니다.');const data=validateBlock(JSON.parse(await file.text()));const missing=data.objects.filter(o=>!library.has(o.asset));if(missing.length)throw Error('사용할 수 없는 에셋: '+missing[0].asset);remember();block=data;selected=null;rebuild();draft();notice('블록을 불러왔습니다. 저장 버튼으로 목록에 추가하세요.');}catch(e){notice('불러오기 실패 · '+e.message);}e.target.value='';};
$('check').onclick=()=>{const issues=corridorIssues(block,library);notice(issues.length?`중앙 통행로를 막는 물체 ${issues.length}개 · ${names[issues[0].asset]||issues[0].asset} · 위치를 옮겨주세요.`:'통행 확인 완료 · 입구부터 출구까지 중앙 3m 통로가 열려 있습니다.');if(issues.length)select(issues[0].uid);};
$('game').onclick=()=>{try{const issues=corridorIssues(block,library);if(issues.length)throw Error('중앙 통행로를 먼저 비워주세요. 통행 확인 버튼으로 확인할 수 있습니다.');save();const compatible=saved.filter(b=>b.size===block.size&&b.roadWidth===block.roadWidth&&!corridorIssues(b,library).length);localStorage.setItem('last-spark-test-blocks-v1',JSON.stringify(compatible));window.open('./?arena&streetBlocks=1','_blank','noopener');notice(`같은 규격의 저장 블록 ${compatible.length}종을 연결한 게임을 열었습니다.`);}catch(e){notice(e.message);}};
let editPose,wasLocked=false;function exitWalk(){walking=false;keys.clear();document.body.classList.remove('walking');$('walkHelp').hidden=true;$('walk').textContent='직접 걸어보기';controls.enabled=true;if(editPose){camera.position.copy(editPose.position);camera.quaternion.copy(editPose.quaternion);controls.target.copy(editPose.target);}controls.update();if(selected)transform.attach(meshes.get(selected));}
$('walk').onclick=()=>{if(walking){exitWalk();if(document.pointerLockElement)document.exitPointerLock();return;}wasLocked=false;editPose={position:camera.position.clone(),quaternion:camera.quaternion.clone(),target:controls.target.clone()};walking=true;walkYaw=0;walkPitch=0;walkingPosition.set(0,1.7,block.size/2-2);controls.enabled=false;transform.detach();document.body.classList.add('walking');$('walkHelp').hidden=false;$('walk').textContent='편집으로 돌아가기';renderer.domElement.requestPointerLock()?.catch(()=>{$('walkHelp').textContent='WASD 이동 · 우클릭 드래그로 시점 · ESC 편집으로 돌아가기';notice('걸어보기 · WASD로 이동하고 우클릭 드래그로 둘러보세요.');});};document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement===renderer.domElement)wasLocked=true;else if(walking&&wasLocked)exitWalk();});document.addEventListener('mousemove',e=>{if(!walking||(document.pointerLockElement!==renderer.domElement&&e.buttons!==2))return;walkYaw-=e.movementX*.002;walkPitch=T.MathUtils.clamp(walkPitch-e.movementY*.002,-1.3,1.3);});
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;keys.add(e.code);if(walking){if(e.code==='Escape'){exitWalk();if(document.pointerLockElement)document.exitPointerLock();}return;}if((e.ctrlKey||e.metaKey)&&e.code==='KeyZ'){e.preventDefault();history(e.shiftKey?redo:undo,e.shiftKey?undo:redo);return;}if(e.code==='Escape')select(null);if(e.code==='Delete'||e.code==='Backspace'){e.preventDefault();$('delete').click();}if(e.code==='KeyW')setMode('translate');if(e.code==='KeyE')setMode('rotate');if(e.code==='KeyR')setMode('scale');});renderer.domElement.addEventListener('contextmenu',e=>{if(walking)e.preventDefault();});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());
function blocked(x,z){return block.objects.some(o=>{if(!o.solid||o.y>2||!library.has(o.asset))return false;const b=objectBounds(o,library.get(o.asset));return b.y+b.h>.2&&Math.abs(x-b.x)<b.w/2+.35&&Math.abs(z-b.z)<b.d/2+.35;});}
function tick(now){const dt=Math.min(.05,(now-lastTime)/1000);lastTime=now;if(walking){const dir=new T.Vector3((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),0,(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0));dir.normalize().applyAxisAngle(new T.Vector3(0,1,0),walkYaw).multiplyScalar(dt*5);const limit=block.size/2-.4,x=T.MathUtils.clamp(walkingPosition.x+dir.x,-limit,limit),z=T.MathUtils.clamp(walkingPosition.z+dir.z,-limit,limit);if(!blocked(x,walkingPosition.z))walkingPosition.x=x;if(!blocked(walkingPosition.x,z))walkingPosition.z=z;camera.position.copy(walkingPosition);camera.rotation.set(walkPitch,walkYaw,0,'YXZ');}else controls.update();const w=$('viewport').clientWidth,h=$('viewport').clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.render(scene,camera);requestAnimationFrame(tick);}requestAnimationFrame(tick);
document.querySelectorAll('input,select,button').forEach(e=>e.disabled=true);
try{library=await loadPurchasedModels();for(const [id,t]of createStreetProps())library.set(id,t);for(const [id,t]of composeReferenceAssets(library))library.set(id,t);for(const cat of['건물','차량','식생','도로·잔해','소품','건축 부품']){const b=document.createElement('button');b.textContent=cat;b.classList.toggle('active',cat===activeCategory);b.onclick=()=>{activeCategory=cat;document.querySelectorAll('#categories button').forEach(v=>v.classList.toggle('active',v===b));renderCatalog();};$('categories').append(b);}for(const selectId of['leftBuilding','rightBuilding']){const s=$(selectId);s.add(new Option('선택 안 함',''));for(const id of library.keys())if(category(id)==='건물'&&!['ref-bridge','ref-alley'].includes(id))s.add(new Option(names[id]||id,id));s.value=selectId==='leftBuilding'?'ref-brownstone':'ref-roofless';}
 try{const stored=localStorage.getItem(BLOCK_STORAGE);saved=stored?JSON.parse(stored).map(validateBlock):[makePreset('벽돌 주택과 버려진 차',0),makePreset('무너진 지붕과 버스',1),makePreset('오피스와 화물차',2)];if(!stored)persist();const draftData=localStorage.getItem('last-spark-street-draft-v1');block=draftData?validateBlock(JSON.parse(draftData)):clone(saved[0]||blank());}catch(e){notice('저장 데이터 복구 실패 · JSON 백업을 불러와 주세요.');block=blank();}
 rebuild();renderCatalog();renderSaved();setMode('translate');updateUndo();document.querySelectorAll('input,select,button').forEach(e=>e.disabled=false);updateUndo();$('loadStatus').textContent=`${library.size-1}종 에셋 준비 완료`;notice('예제 거리 3종으로 시작해 보세요 · 드래그로 시점 회전 · 휠로 확대 · 물체 선택 후 화살표로 이동');window.streetEditor={get block(){return clone(block);},get saved(){return clone(saved);},library,meshes,validate:()=>corridorIssues(block,library)};
}catch(e){$('loadStatus').textContent='에셋 로딩 실패';notice(e.message);console.error(e);}
