import * as T from 'three';
export function addStreetLife(root){let seed=(root.userData.seed^0x38171)>>>0;const r=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;},o=new T.Object3D();
 const petalGeo=new T.SphereGeometry(1,6,4),stemGeo=new T.CylinderGeometry(.009,.012,1,4),petalMat=new T.MeshStandardMaterial({color:0xffffff,roughness:1}),stemMat=new T.MeshStandardMaterial({color:0x53643a,roughness:1}),count=170,petals=new T.InstancedMesh(petalGeo,petalMat,count*6),stems=new T.InstancedMesh(stemGeo,stemMat,count),palette=[0xe8debd,0xd6afbf,0xbda5d0,0xe2c061];
 for(let i=0;i<count;i++){const side=r()<.5?-1:1,x=side*(3.9+r()*3.8),z=(r()-.5)*68,h=.55+r()*.55,ground=.21;o.position.set(x,ground+h/2,z);o.scale.set(1,h,1);o.rotation.set(0,0,(r()-.5)*.15);o.updateMatrix();stems.setMatrixAt(i,o.matrix);const color=new T.Color(palette[Math.floor(r()*palette.length)]);for(let j=0;j<6;j++){const a=j/5*Math.PI*2;o.position.set(x+(j===5?0:Math.cos(a)*.075),ground+h,z+(j===5?0:Math.sin(a)*.075));o.scale.set(j===5?.035:.07,.028,j===5?.035:.045);o.rotation.set(0,-a,0);o.updateMatrix();petals.setMatrixAt(i*6+j,o.matrix);petals.setColorAt(i*6+j,j===5?new T.Color(0xb89137):color);}}
 petals.receiveShadow=stems.receiveShadow=true;root.add(petals,stems);
 const wingGeo=new T.BufferGeometry();wingGeo.setAttribute('position',new T.Float32BufferAttribute([0,0,0,.17,0,.10,.21,0,-.07,0,0,0,.21,0,-.07,.10,0,-.16],3));wingGeo.computeVertexNormals();const wingMat=new T.MeshStandardMaterial({color:0xffffff,side:T.DoubleSide,roughness:1}),wings=new T.InstancedMesh(wingGeo,wingMat,16),flights=Array.from({length:8},()=>({x:(r()<.5?-1:1)*(3.1+r()*1.4),z:(r()-.5)*58,y:1.1+r()*1.8,phase:r()*Math.PI*2,speed:.35+r()*.3}));flights.forEach((f,i)=>{const color=new T.Color([0xd6b264,0xc2c9db,0xca9272][i%3]);wings.setColorAt(i*2,color);wings.setColorAt(i*2+1,color);});root.add(wings);
 const bugGeo=new T.BufferGeometry(),bugPositions=new Float32Array(24*3),bugs=Array.from({length:24},()=>({x:(r()<.5?-1:1)*(3.7+r()*1.8),z:(r()-.5)*65,y:.8+r()*2,phase:r()*6.28}));bugGeo.setAttribute('position',new T.BufferAttribute(bugPositions,3));const bugMat=new T.PointsMaterial({color:0xaba28d,size:.045,transparent:true,opacity:.55,sizeAttenuation:true}),dots=new T.Points(bugGeo,bugMat);dots.frustumCulled=false;root.add(dots);
 const localCamera=new T.Vector3();let lastUpdate=-Infinity;
 const update=(t,camera)=>{if(camera&&t-lastUpdate<1/30&&t>=lastUpdate)return;lastUpdate=t;if(camera)localCamera.copy(camera.position),root.worldToLocal(localCamera);flights.forEach((f,i)=>{const p=t*f.speed+f.phase,x=f.x+Math.sin(p)*.85,z=f.z+Math.cos(p*.8)*1.2,y=f.y+Math.sin(p*2)*.25,flap=Math.sin(t*12+f.phase)*.75;for(let j=0;j<2;j++){o.position.set(x,y,z);const visible=!camera||Math.hypot(localCamera.x-x,localCamera.z-z)<45;o.scale.set(visible?(j===0?1:-1):0,visible?1:0,visible?1:0);o.rotation.set(.12,Math.atan2(Math.cos(p),-Math.sin(p*.8)),j===0?flap:-flap);o.updateMatrix();wings.setMatrixAt(i*2+j,o.matrix);}});wings.instanceMatrix.needsUpdate=true;bugs.forEach((b,i)=>{bugPositions[i*3]=b.x+Math.sin(t*.7+b.phase)*.45;bugPositions[i*3+1]=camera&&Math.hypot(localCamera.x-b.x,localCamera.z-b.z)>35?-100:b.y+Math.sin(t*1.1+b.phase)*.25;bugPositions[i*3+2]=b.z+Math.cos(t*.5+b.phase)*.5;});bugGeo.attributes.position.needsUpdate=true;};update(0);
 root.userData.life={flowers:count,butterflies:8,insects:24};root.userData.updateLife=update;
 for(const mesh of [petals,stems,wings,dots])mesh.userData={ownedGeometry:true,ownedMaterial:true,...(mesh.isInstancedMesh?{ownedInstances:true}:{})};
}
